/*
 * Default/22.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import model.CustomField;
import model.Entity;
import model.FileLink;
import model.StringValue;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * ACAInfoDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-17T14:29:48.617Z")
public class ACAInfoDetail extends Entity {
  @SerializedName("CoverageType")
  private StringValue coverageType = null;

  @SerializedName("HealthPlanType")
  private StringValue healthPlanType = null;

  public ACAInfoDetail coverageType(StringValue coverageType) {
    this.coverageType = coverageType;
    return this;
  }

   /**
   * Get coverageType
   * @return coverageType
  **/
  @ApiModelProperty(value = "")
  public StringValue getCoverageType() {
    return coverageType;
  }

  public void setCoverageType(StringValue coverageType) {
    this.coverageType = coverageType;
  }

  public ACAInfoDetail healthPlanType(StringValue healthPlanType) {
    this.healthPlanType = healthPlanType;
    return this;
  }

   /**
   * Get healthPlanType
   * @return healthPlanType
  **/
  @ApiModelProperty(value = "")
  public StringValue getHealthPlanType() {
    return healthPlanType;
  }

  public void setHealthPlanType(StringValue healthPlanType) {
    this.healthPlanType = healthPlanType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ACAInfoDetail acAInfoDetail = (ACAInfoDetail) o;
    return Objects.equals(this.coverageType, acAInfoDetail.coverageType) &&
        Objects.equals(this.healthPlanType, acAInfoDetail.healthPlanType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coverageType, healthPlanType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ACAInfoDetail {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    coverageType: ").append(toIndentedString(coverageType)).append("\n");
    sb.append("    healthPlanType: ").append(toIndentedString(healthPlanType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

