/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * AppDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class AppDetails extends Entity {
  @SerializedName("Account")
  private StringValue account = null;

  @SerializedName("ActualAmount")
  private DecimalValue actualAmount = null;

  @SerializedName("ActualDuration")
  private StringValue actualDuration = null;

  @SerializedName("ActualQty")
  private DecimalValue actualQty = null;

  @SerializedName("AppointmentNbr")
  private StringValue appointmentNbr = null;

  @SerializedName("Billable")
  private BooleanValue billable = null;

  @SerializedName("BillableAmount")
  private DecimalValue billableAmount = null;

  @SerializedName("BillableQty")
  private DecimalValue billableQty = null;

  @SerializedName("BillingRule")
  private StringValue billingRule = null;

  @SerializedName("Branch")
  private StringValue branch = null;

  @SerializedName("ComponentID")
  private StringValue componentID = null;

  @SerializedName("ComponentLineRef")
  private StringValue componentLineRef = null;

  @SerializedName("CostCode")
  private StringValue costCode = null;

  @SerializedName("CoveredQty")
  private DecimalValue coveredQty = null;

  @SerializedName("CuryUnitCost")
  private DecimalValue curyUnitCost = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("DiscountAmount")
  private DecimalValue discountAmount = null;

  @SerializedName("DiscountPercent")
  private DecimalValue discountPercent = null;

  @SerializedName("EquipmentAction")
  private StringValue equipmentAction = null;

  @SerializedName("EquipmentActionComment")
  private StringValue equipmentActionComment = null;

  @SerializedName("EstimatedAmount")
  private DecimalValue estimatedAmount = null;

  @SerializedName("EstimatedDuration")
  private StringValue estimatedDuration = null;

  @SerializedName("EstimatedQty")
  private DecimalValue estimatedQty = null;

  @SerializedName("ExtPrice")
  private DecimalValue extPrice = null;

  @SerializedName("InventoryID")
  private StringValue inventoryID = null;

  @SerializedName("LineNbr")
  private IntValue lineNbr = null;

  @SerializedName("LineRef")
  private StringValue lineRef = null;

  @SerializedName("LineStatus")
  private StringValue lineStatus = null;

  @SerializedName("LineType")
  private StringValue lineType = null;

  @SerializedName("Location")
  private StringValue location = null;

  @SerializedName("LotSerialNbr")
  private StringValue lotSerialNbr = null;

  @SerializedName("ManualPrice")
  private BooleanValue manualPrice = null;

  @SerializedName("MarkforPO")
  private BooleanValue markforPO = null;

  @SerializedName("ModelEquipmentLineRef")
  private StringValue modelEquipmentLineRef = null;

  @SerializedName("OverageQty")
  private DecimalValue overageQty = null;

  @SerializedName("OverageUnitPrice")
  private DecimalValue overageUnitPrice = null;

  @SerializedName("PickupDeliveryAction")
  private StringValue pickupDeliveryAction = null;

  @SerializedName("PickupDeliveryLineRef")
  private StringValue pickupDeliveryLineRef = null;

  @SerializedName("PickupDeliveryServiceID")
  private StringValue pickupDeliveryServiceID = null;

  @SerializedName("POCompleted")
  private BooleanValue poCompleted = null;

  @SerializedName("PONbr")
  private StringValue poNbr = null;

  @SerializedName("POStatus")
  private StringValue poStatus = null;

  @SerializedName("PrepaidItem")
  private BooleanValue prepaidItem = null;

  @SerializedName("ProjectTask")
  private StringValue projectTask = null;

  @SerializedName("RelatedDocNbr")
  private StringValue relatedDocNbr = null;

  @SerializedName("ServiceContractItem")
  private BooleanValue serviceContractItem = null;

  @SerializedName("ServiceOrderLineRef")
  private StringValue serviceOrderLineRef = null;

  @SerializedName("ServiceOrderType")
  private StringValue serviceOrderType = null;

  @SerializedName("SortOrder")
  private IntValue sortOrder = null;

  @SerializedName("StaffMemberID")
  private StringValue staffMemberID = null;

  @SerializedName("Subaccount")
  private StringValue subaccount = null;

  @SerializedName("Subitem")
  private StringValue subitem = null;

  @SerializedName("TargetEquipmentID")
  private StringValue targetEquipmentID = null;

  @SerializedName("TaxCategory")
  private StringValue taxCategory = null;

  @SerializedName("UnitPrice")
  private DecimalValue unitPrice = null;

  @SerializedName("UOM")
  private StringValue UOM = null;

  @SerializedName("Warehouse")
  private StringValue warehouse = null;

  @SerializedName("Warranty")
  private BooleanValue warranty = null;

  public AppDetails account(StringValue account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @ApiModelProperty(value = "")
  public StringValue getAccount() {
    return account;
  }

  public void setAccount(StringValue account) {
    this.account = account;
  }

  public AppDetails actualAmount(DecimalValue actualAmount) {
    this.actualAmount = actualAmount;
    return this;
  }

   /**
   * Get actualAmount
   * @return actualAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getActualAmount() {
    return actualAmount;
  }

  public void setActualAmount(DecimalValue actualAmount) {
    this.actualAmount = actualAmount;
  }

  public AppDetails actualDuration(StringValue actualDuration) {
    this.actualDuration = actualDuration;
    return this;
  }

   /**
   * Get actualDuration
   * @return actualDuration
  **/
  @ApiModelProperty(value = "")
  public StringValue getActualDuration() {
    return actualDuration;
  }

  public void setActualDuration(StringValue actualDuration) {
    this.actualDuration = actualDuration;
  }

  public AppDetails actualQty(DecimalValue actualQty) {
    this.actualQty = actualQty;
    return this;
  }

   /**
   * Get actualQty
   * @return actualQty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getActualQty() {
    return actualQty;
  }

  public void setActualQty(DecimalValue actualQty) {
    this.actualQty = actualQty;
  }

  public AppDetails appointmentNbr(StringValue appointmentNbr) {
    this.appointmentNbr = appointmentNbr;
    return this;
  }

   /**
   * Get appointmentNbr
   * @return appointmentNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getAppointmentNbr() {
    return appointmentNbr;
  }

  public void setAppointmentNbr(StringValue appointmentNbr) {
    this.appointmentNbr = appointmentNbr;
  }

  public AppDetails billable(BooleanValue billable) {
    this.billable = billable;
    return this;
  }

   /**
   * Get billable
   * @return billable
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getBillable() {
    return billable;
  }

  public void setBillable(BooleanValue billable) {
    this.billable = billable;
  }

  public AppDetails billableAmount(DecimalValue billableAmount) {
    this.billableAmount = billableAmount;
    return this;
  }

   /**
   * Get billableAmount
   * @return billableAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getBillableAmount() {
    return billableAmount;
  }

  public void setBillableAmount(DecimalValue billableAmount) {
    this.billableAmount = billableAmount;
  }

  public AppDetails billableQty(DecimalValue billableQty) {
    this.billableQty = billableQty;
    return this;
  }

   /**
   * Get billableQty
   * @return billableQty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getBillableQty() {
    return billableQty;
  }

  public void setBillableQty(DecimalValue billableQty) {
    this.billableQty = billableQty;
  }

  public AppDetails billingRule(StringValue billingRule) {
    this.billingRule = billingRule;
    return this;
  }

   /**
   * Get billingRule
   * @return billingRule
  **/
  @ApiModelProperty(value = "")
  public StringValue getBillingRule() {
    return billingRule;
  }

  public void setBillingRule(StringValue billingRule) {
    this.billingRule = billingRule;
  }

  public AppDetails branch(StringValue branch) {
    this.branch = branch;
    return this;
  }

   /**
   * Get branch
   * @return branch
  **/
  @ApiModelProperty(value = "")
  public StringValue getBranch() {
    return branch;
  }

  public void setBranch(StringValue branch) {
    this.branch = branch;
  }

  public AppDetails componentID(StringValue componentID) {
    this.componentID = componentID;
    return this;
  }

   /**
   * Get componentID
   * @return componentID
  **/
  @ApiModelProperty(value = "")
  public StringValue getComponentID() {
    return componentID;
  }

  public void setComponentID(StringValue componentID) {
    this.componentID = componentID;
  }

  public AppDetails componentLineRef(StringValue componentLineRef) {
    this.componentLineRef = componentLineRef;
    return this;
  }

   /**
   * Get componentLineRef
   * @return componentLineRef
  **/
  @ApiModelProperty(value = "")
  public StringValue getComponentLineRef() {
    return componentLineRef;
  }

  public void setComponentLineRef(StringValue componentLineRef) {
    this.componentLineRef = componentLineRef;
  }

  public AppDetails costCode(StringValue costCode) {
    this.costCode = costCode;
    return this;
  }

   /**
   * Get costCode
   * @return costCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getCostCode() {
    return costCode;
  }

  public void setCostCode(StringValue costCode) {
    this.costCode = costCode;
  }

  public AppDetails coveredQty(DecimalValue coveredQty) {
    this.coveredQty = coveredQty;
    return this;
  }

   /**
   * Get coveredQty
   * @return coveredQty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getCoveredQty() {
    return coveredQty;
  }

  public void setCoveredQty(DecimalValue coveredQty) {
    this.coveredQty = coveredQty;
  }

  public AppDetails curyUnitCost(DecimalValue curyUnitCost) {
    this.curyUnitCost = curyUnitCost;
    return this;
  }

   /**
   * Get curyUnitCost
   * @return curyUnitCost
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getCuryUnitCost() {
    return curyUnitCost;
  }

  public void setCuryUnitCost(DecimalValue curyUnitCost) {
    this.curyUnitCost = curyUnitCost;
  }

  public AppDetails description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public AppDetails discountAmount(DecimalValue discountAmount) {
    this.discountAmount = discountAmount;
    return this;
  }

   /**
   * Get discountAmount
   * @return discountAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getDiscountAmount() {
    return discountAmount;
  }

  public void setDiscountAmount(DecimalValue discountAmount) {
    this.discountAmount = discountAmount;
  }

  public AppDetails discountPercent(DecimalValue discountPercent) {
    this.discountPercent = discountPercent;
    return this;
  }

   /**
   * Get discountPercent
   * @return discountPercent
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getDiscountPercent() {
    return discountPercent;
  }

  public void setDiscountPercent(DecimalValue discountPercent) {
    this.discountPercent = discountPercent;
  }

  public AppDetails equipmentAction(StringValue equipmentAction) {
    this.equipmentAction = equipmentAction;
    return this;
  }

   /**
   * Get equipmentAction
   * @return equipmentAction
  **/
  @ApiModelProperty(value = "")
  public StringValue getEquipmentAction() {
    return equipmentAction;
  }

  public void setEquipmentAction(StringValue equipmentAction) {
    this.equipmentAction = equipmentAction;
  }

  public AppDetails equipmentActionComment(StringValue equipmentActionComment) {
    this.equipmentActionComment = equipmentActionComment;
    return this;
  }

   /**
   * Get equipmentActionComment
   * @return equipmentActionComment
  **/
  @ApiModelProperty(value = "")
  public StringValue getEquipmentActionComment() {
    return equipmentActionComment;
  }

  public void setEquipmentActionComment(StringValue equipmentActionComment) {
    this.equipmentActionComment = equipmentActionComment;
  }

  public AppDetails estimatedAmount(DecimalValue estimatedAmount) {
    this.estimatedAmount = estimatedAmount;
    return this;
  }

   /**
   * Get estimatedAmount
   * @return estimatedAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getEstimatedAmount() {
    return estimatedAmount;
  }

  public void setEstimatedAmount(DecimalValue estimatedAmount) {
    this.estimatedAmount = estimatedAmount;
  }

  public AppDetails estimatedDuration(StringValue estimatedDuration) {
    this.estimatedDuration = estimatedDuration;
    return this;
  }

   /**
   * Get estimatedDuration
   * @return estimatedDuration
  **/
  @ApiModelProperty(value = "")
  public StringValue getEstimatedDuration() {
    return estimatedDuration;
  }

  public void setEstimatedDuration(StringValue estimatedDuration) {
    this.estimatedDuration = estimatedDuration;
  }

  public AppDetails estimatedQty(DecimalValue estimatedQty) {
    this.estimatedQty = estimatedQty;
    return this;
  }

   /**
   * Get estimatedQty
   * @return estimatedQty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getEstimatedQty() {
    return estimatedQty;
  }

  public void setEstimatedQty(DecimalValue estimatedQty) {
    this.estimatedQty = estimatedQty;
  }

  public AppDetails extPrice(DecimalValue extPrice) {
    this.extPrice = extPrice;
    return this;
  }

   /**
   * Get extPrice
   * @return extPrice
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getExtPrice() {
    return extPrice;
  }

  public void setExtPrice(DecimalValue extPrice) {
    this.extPrice = extPrice;
  }

  public AppDetails inventoryID(StringValue inventoryID) {
    this.inventoryID = inventoryID;
    return this;
  }

   /**
   * Get inventoryID
   * @return inventoryID
  **/
  @ApiModelProperty(value = "")
  public StringValue getInventoryID() {
    return inventoryID;
  }

  public void setInventoryID(StringValue inventoryID) {
    this.inventoryID = inventoryID;
  }

  public AppDetails lineNbr(IntValue lineNbr) {
    this.lineNbr = lineNbr;
    return this;
  }

   /**
   * Get lineNbr
   * @return lineNbr
  **/
  @ApiModelProperty(value = "")
  public IntValue getLineNbr() {
    return lineNbr;
  }

  public void setLineNbr(IntValue lineNbr) {
    this.lineNbr = lineNbr;
  }

  public AppDetails lineRef(StringValue lineRef) {
    this.lineRef = lineRef;
    return this;
  }

   /**
   * Get lineRef
   * @return lineRef
  **/
  @ApiModelProperty(value = "")
  public StringValue getLineRef() {
    return lineRef;
  }

  public void setLineRef(StringValue lineRef) {
    this.lineRef = lineRef;
  }

  public AppDetails lineStatus(StringValue lineStatus) {
    this.lineStatus = lineStatus;
    return this;
  }

   /**
   * Get lineStatus
   * @return lineStatus
  **/
  @ApiModelProperty(value = "")
  public StringValue getLineStatus() {
    return lineStatus;
  }

  public void setLineStatus(StringValue lineStatus) {
    this.lineStatus = lineStatus;
  }

  public AppDetails lineType(StringValue lineType) {
    this.lineType = lineType;
    return this;
  }

   /**
   * Get lineType
   * @return lineType
  **/
  @ApiModelProperty(value = "")
  public StringValue getLineType() {
    return lineType;
  }

  public void setLineType(StringValue lineType) {
    this.lineType = lineType;
  }

  public AppDetails location(StringValue location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(value = "")
  public StringValue getLocation() {
    return location;
  }

  public void setLocation(StringValue location) {
    this.location = location;
  }

  public AppDetails lotSerialNbr(StringValue lotSerialNbr) {
    this.lotSerialNbr = lotSerialNbr;
    return this;
  }

   /**
   * Get lotSerialNbr
   * @return lotSerialNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getLotSerialNbr() {
    return lotSerialNbr;
  }

  public void setLotSerialNbr(StringValue lotSerialNbr) {
    this.lotSerialNbr = lotSerialNbr;
  }

  public AppDetails manualPrice(BooleanValue manualPrice) {
    this.manualPrice = manualPrice;
    return this;
  }

   /**
   * Get manualPrice
   * @return manualPrice
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getManualPrice() {
    return manualPrice;
  }

  public void setManualPrice(BooleanValue manualPrice) {
    this.manualPrice = manualPrice;
  }

  public AppDetails markforPO(BooleanValue markforPO) {
    this.markforPO = markforPO;
    return this;
  }

   /**
   * Get markforPO
   * @return markforPO
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getMarkforPO() {
    return markforPO;
  }

  public void setMarkforPO(BooleanValue markforPO) {
    this.markforPO = markforPO;
  }

  public AppDetails modelEquipmentLineRef(StringValue modelEquipmentLineRef) {
    this.modelEquipmentLineRef = modelEquipmentLineRef;
    return this;
  }

   /**
   * Get modelEquipmentLineRef
   * @return modelEquipmentLineRef
  **/
  @ApiModelProperty(value = "")
  public StringValue getModelEquipmentLineRef() {
    return modelEquipmentLineRef;
  }

  public void setModelEquipmentLineRef(StringValue modelEquipmentLineRef) {
    this.modelEquipmentLineRef = modelEquipmentLineRef;
  }

  public AppDetails overageQty(DecimalValue overageQty) {
    this.overageQty = overageQty;
    return this;
  }

   /**
   * Get overageQty
   * @return overageQty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getOverageQty() {
    return overageQty;
  }

  public void setOverageQty(DecimalValue overageQty) {
    this.overageQty = overageQty;
  }

  public AppDetails overageUnitPrice(DecimalValue overageUnitPrice) {
    this.overageUnitPrice = overageUnitPrice;
    return this;
  }

   /**
   * Get overageUnitPrice
   * @return overageUnitPrice
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getOverageUnitPrice() {
    return overageUnitPrice;
  }

  public void setOverageUnitPrice(DecimalValue overageUnitPrice) {
    this.overageUnitPrice = overageUnitPrice;
  }

  public AppDetails pickupDeliveryAction(StringValue pickupDeliveryAction) {
    this.pickupDeliveryAction = pickupDeliveryAction;
    return this;
  }

   /**
   * Get pickupDeliveryAction
   * @return pickupDeliveryAction
  **/
  @ApiModelProperty(value = "")
  public StringValue getPickupDeliveryAction() {
    return pickupDeliveryAction;
  }

  public void setPickupDeliveryAction(StringValue pickupDeliveryAction) {
    this.pickupDeliveryAction = pickupDeliveryAction;
  }

  public AppDetails pickupDeliveryLineRef(StringValue pickupDeliveryLineRef) {
    this.pickupDeliveryLineRef = pickupDeliveryLineRef;
    return this;
  }

   /**
   * Get pickupDeliveryLineRef
   * @return pickupDeliveryLineRef
  **/
  @ApiModelProperty(value = "")
  public StringValue getPickupDeliveryLineRef() {
    return pickupDeliveryLineRef;
  }

  public void setPickupDeliveryLineRef(StringValue pickupDeliveryLineRef) {
    this.pickupDeliveryLineRef = pickupDeliveryLineRef;
  }

  public AppDetails pickupDeliveryServiceID(StringValue pickupDeliveryServiceID) {
    this.pickupDeliveryServiceID = pickupDeliveryServiceID;
    return this;
  }

   /**
   * Get pickupDeliveryServiceID
   * @return pickupDeliveryServiceID
  **/
  @ApiModelProperty(value = "")
  public StringValue getPickupDeliveryServiceID() {
    return pickupDeliveryServiceID;
  }

  public void setPickupDeliveryServiceID(StringValue pickupDeliveryServiceID) {
    this.pickupDeliveryServiceID = pickupDeliveryServiceID;
  }

  public AppDetails poCompleted(BooleanValue poCompleted) {
    this.poCompleted = poCompleted;
    return this;
  }

   /**
   * Get poCompleted
   * @return poCompleted
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getPoCompleted() {
    return poCompleted;
  }

  public void setPoCompleted(BooleanValue poCompleted) {
    this.poCompleted = poCompleted;
  }

  public AppDetails poNbr(StringValue poNbr) {
    this.poNbr = poNbr;
    return this;
  }

   /**
   * Get poNbr
   * @return poNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getPoNbr() {
    return poNbr;
  }

  public void setPoNbr(StringValue poNbr) {
    this.poNbr = poNbr;
  }

  public AppDetails poStatus(StringValue poStatus) {
    this.poStatus = poStatus;
    return this;
  }

   /**
   * Get poStatus
   * @return poStatus
  **/
  @ApiModelProperty(value = "")
  public StringValue getPoStatus() {
    return poStatus;
  }

  public void setPoStatus(StringValue poStatus) {
    this.poStatus = poStatus;
  }

  public AppDetails prepaidItem(BooleanValue prepaidItem) {
    this.prepaidItem = prepaidItem;
    return this;
  }

   /**
   * Get prepaidItem
   * @return prepaidItem
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getPrepaidItem() {
    return prepaidItem;
  }

  public void setPrepaidItem(BooleanValue prepaidItem) {
    this.prepaidItem = prepaidItem;
  }

  public AppDetails projectTask(StringValue projectTask) {
    this.projectTask = projectTask;
    return this;
  }

   /**
   * Get projectTask
   * @return projectTask
  **/
  @ApiModelProperty(value = "")
  public StringValue getProjectTask() {
    return projectTask;
  }

  public void setProjectTask(StringValue projectTask) {
    this.projectTask = projectTask;
  }

  public AppDetails relatedDocNbr(StringValue relatedDocNbr) {
    this.relatedDocNbr = relatedDocNbr;
    return this;
  }

   /**
   * Get relatedDocNbr
   * @return relatedDocNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getRelatedDocNbr() {
    return relatedDocNbr;
  }

  public void setRelatedDocNbr(StringValue relatedDocNbr) {
    this.relatedDocNbr = relatedDocNbr;
  }

  public AppDetails serviceContractItem(BooleanValue serviceContractItem) {
    this.serviceContractItem = serviceContractItem;
    return this;
  }

   /**
   * Get serviceContractItem
   * @return serviceContractItem
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getServiceContractItem() {
    return serviceContractItem;
  }

  public void setServiceContractItem(BooleanValue serviceContractItem) {
    this.serviceContractItem = serviceContractItem;
  }

  public AppDetails serviceOrderLineRef(StringValue serviceOrderLineRef) {
    this.serviceOrderLineRef = serviceOrderLineRef;
    return this;
  }

   /**
   * Get serviceOrderLineRef
   * @return serviceOrderLineRef
  **/
  @ApiModelProperty(value = "")
  public StringValue getServiceOrderLineRef() {
    return serviceOrderLineRef;
  }

  public void setServiceOrderLineRef(StringValue serviceOrderLineRef) {
    this.serviceOrderLineRef = serviceOrderLineRef;
  }

  public AppDetails serviceOrderType(StringValue serviceOrderType) {
    this.serviceOrderType = serviceOrderType;
    return this;
  }

   /**
   * Get serviceOrderType
   * @return serviceOrderType
  **/
  @ApiModelProperty(value = "")
  public StringValue getServiceOrderType() {
    return serviceOrderType;
  }

  public void setServiceOrderType(StringValue serviceOrderType) {
    this.serviceOrderType = serviceOrderType;
  }

  public AppDetails sortOrder(IntValue sortOrder) {
    this.sortOrder = sortOrder;
    return this;
  }

   /**
   * Get sortOrder
   * @return sortOrder
  **/
  @ApiModelProperty(value = "")
  public IntValue getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(IntValue sortOrder) {
    this.sortOrder = sortOrder;
  }

  public AppDetails staffMemberID(StringValue staffMemberID) {
    this.staffMemberID = staffMemberID;
    return this;
  }

   /**
   * Get staffMemberID
   * @return staffMemberID
  **/
  @ApiModelProperty(value = "")
  public StringValue getStaffMemberID() {
    return staffMemberID;
  }

  public void setStaffMemberID(StringValue staffMemberID) {
    this.staffMemberID = staffMemberID;
  }

  public AppDetails subaccount(StringValue subaccount) {
    this.subaccount = subaccount;
    return this;
  }

   /**
   * Get subaccount
   * @return subaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getSubaccount() {
    return subaccount;
  }

  public void setSubaccount(StringValue subaccount) {
    this.subaccount = subaccount;
  }

  public AppDetails subitem(StringValue subitem) {
    this.subitem = subitem;
    return this;
  }

   /**
   * Get subitem
   * @return subitem
  **/
  @ApiModelProperty(value = "")
  public StringValue getSubitem() {
    return subitem;
  }

  public void setSubitem(StringValue subitem) {
    this.subitem = subitem;
  }

  public AppDetails targetEquipmentID(StringValue targetEquipmentID) {
    this.targetEquipmentID = targetEquipmentID;
    return this;
  }

   /**
   * Get targetEquipmentID
   * @return targetEquipmentID
  **/
  @ApiModelProperty(value = "")
  public StringValue getTargetEquipmentID() {
    return targetEquipmentID;
  }

  public void setTargetEquipmentID(StringValue targetEquipmentID) {
    this.targetEquipmentID = targetEquipmentID;
  }

  public AppDetails taxCategory(StringValue taxCategory) {
    this.taxCategory = taxCategory;
    return this;
  }

   /**
   * Get taxCategory
   * @return taxCategory
  **/
  @ApiModelProperty(value = "")
  public StringValue getTaxCategory() {
    return taxCategory;
  }

  public void setTaxCategory(StringValue taxCategory) {
    this.taxCategory = taxCategory;
  }

  public AppDetails unitPrice(DecimalValue unitPrice) {
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getUnitPrice() {
    return unitPrice;
  }

  public void setUnitPrice(DecimalValue unitPrice) {
    this.unitPrice = unitPrice;
  }

  public AppDetails UOM(StringValue UOM) {
    this.UOM = UOM;
    return this;
  }

   /**
   * Get UOM
   * @return UOM
  **/
  @ApiModelProperty(value = "")
  public StringValue getUOM() {
    return UOM;
  }

  public void setUOM(StringValue UOM) {
    this.UOM = UOM;
  }

  public AppDetails warehouse(StringValue warehouse) {
    this.warehouse = warehouse;
    return this;
  }

   /**
   * Get warehouse
   * @return warehouse
  **/
  @ApiModelProperty(value = "")
  public StringValue getWarehouse() {
    return warehouse;
  }

  public void setWarehouse(StringValue warehouse) {
    this.warehouse = warehouse;
  }

  public AppDetails warranty(BooleanValue warranty) {
    this.warranty = warranty;
    return this;
  }

   /**
   * Get warranty
   * @return warranty
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getWarranty() {
    return warranty;
  }

  public void setWarranty(BooleanValue warranty) {
    this.warranty = warranty;
  }

}


