/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Approval
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class Approval extends Entity {
  @SerializedName("ApprovedBy")
  private StringValue approvedBy = null;

  @SerializedName("ApprovedByName")
  private StringValue approvedByName = null;

  @SerializedName("Approver")
  private StringValue approver = null;

  @SerializedName("ApproverName")
  private StringValue approverName = null;

  @SerializedName("Date")
  private DateTimeValue date = null;

  @SerializedName("Status")
  private StringValue status = null;

  @SerializedName("Workgroup")
  private StringValue workgroup = null;

  public Approval approvedBy(StringValue approvedBy) {
    this.approvedBy = approvedBy;
    return this;
  }

   /**
   * Get approvedBy
   * @return approvedBy
  **/
  @ApiModelProperty(value = "")
  public StringValue getApprovedBy() {
    return approvedBy;
  }

  public void setApprovedBy(StringValue approvedBy) {
    this.approvedBy = approvedBy;
  }

  public Approval approvedByName(StringValue approvedByName) {
    this.approvedByName = approvedByName;
    return this;
  }

   /**
   * Get approvedByName
   * @return approvedByName
  **/
  @ApiModelProperty(value = "")
  public StringValue getApprovedByName() {
    return approvedByName;
  }

  public void setApprovedByName(StringValue approvedByName) {
    this.approvedByName = approvedByName;
  }

  public Approval approver(StringValue approver) {
    this.approver = approver;
    return this;
  }

   /**
   * Get approver
   * @return approver
  **/
  @ApiModelProperty(value = "")
  public StringValue getApprover() {
    return approver;
  }

  public void setApprover(StringValue approver) {
    this.approver = approver;
  }

  public Approval approverName(StringValue approverName) {
    this.approverName = approverName;
    return this;
  }

   /**
   * Get approverName
   * @return approverName
  **/
  @ApiModelProperty(value = "")
  public StringValue getApproverName() {
    return approverName;
  }

  public void setApproverName(StringValue approverName) {
    this.approverName = approverName;
  }

  public Approval date(DateTimeValue date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getDate() {
    return date;
  }

  public void setDate(DateTimeValue date) {
    this.date = date;
  }

  public Approval status(StringValue status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StringValue getStatus() {
    return status;
  }

  public void setStatus(StringValue status) {
    this.status = status;
  }

  public Approval workgroup(StringValue workgroup) {
    this.workgroup = workgroup;
    return this;
  }

   /**
   * Get workgroup
   * @return workgroup
  **/
  @ApiModelProperty(value = "")
  public StringValue getWorkgroup() {
    return workgroup;
  }

  public void setWorkgroup(StringValue workgroup) {
    this.workgroup = workgroup;
  }

}

