/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * AttributeDefinition
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class AttributeDefinition extends Entity {
  @SerializedName("AttributeID")
  private StringValue attributeID = null;

  @SerializedName("ControlType")
  private StringValue controlType = null;

  @SerializedName("CreatedDateTime")
  private DateTimeValue createdDateTime = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("EntryMask")
  private StringValue entryMask = null;

  @SerializedName("Internal")
  private BooleanValue internal = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("RegExp")
  private StringValue regExp = null;

  @SerializedName("Values")
  private List<AttributeDefinitionValue> values = null;

  public AttributeDefinition attributeID(StringValue attributeID) {
    this.attributeID = attributeID;
    return this;
  }

   /**
   * Get attributeID
   * @return attributeID
  **/
  @ApiModelProperty(value = "")
  public StringValue getAttributeID() {
    return attributeID;
  }

  public void setAttributeID(StringValue attributeID) {
    this.attributeID = attributeID;
  }

  public AttributeDefinition controlType(StringValue controlType) {
    this.controlType = controlType;
    return this;
  }

   /**
   * Get controlType
   * @return controlType
  **/
  @ApiModelProperty(value = "")
  public StringValue getControlType() {
    return controlType;
  }

  public void setControlType(StringValue controlType) {
    this.controlType = controlType;
  }

  public AttributeDefinition createdDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public AttributeDefinition description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public AttributeDefinition entryMask(StringValue entryMask) {
    this.entryMask = entryMask;
    return this;
  }

   /**
   * Get entryMask
   * @return entryMask
  **/
  @ApiModelProperty(value = "")
  public StringValue getEntryMask() {
    return entryMask;
  }

  public void setEntryMask(StringValue entryMask) {
    this.entryMask = entryMask;
  }

  public AttributeDefinition internal(BooleanValue internal) {
    this.internal = internal;
    return this;
  }

   /**
   * Get internal
   * @return internal
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getInternal() {
    return internal;
  }

  public void setInternal(BooleanValue internal) {
    this.internal = internal;
  }

  public AttributeDefinition lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public AttributeDefinition regExp(StringValue regExp) {
    this.regExp = regExp;
    return this;
  }

   /**
   * Get regExp
   * @return regExp
  **/
  @ApiModelProperty(value = "")
  public StringValue getRegExp() {
    return regExp;
  }

  public void setRegExp(StringValue regExp) {
    this.regExp = regExp;
  }

  public AttributeDefinition values(List<AttributeDefinitionValue> values) {
    this.values = values;
    return this;
  }

  public AttributeDefinition addValuesItem(AttributeDefinitionValue valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<>();
    }
    this.values.add(valuesItem);
    return this;
  }

   /**
   * Get values
   * @return values
  **/
  @ApiModelProperty(value = "")
  public List<AttributeDefinitionValue> getValues() {
    return values;
  }

  public void setValues(List<AttributeDefinitionValue> values) {
    this.values = values;
  }

}

