/*
 * Default/22.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import model.BooleanValue;
import model.CustomField;
import model.DateTimeValue;
import model.DecimalValue;
import model.Entity;
import model.FileLink;
import model.StringValue;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * BatchEarningDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-17T14:29:48.617Z")
public class BatchEarningDetail extends Entity {
  @SerializedName("Account")
  private StringValue account = null;

  @SerializedName("AllowCopy")
  private BooleanValue allowCopy = null;

  @SerializedName("Amount")
  private DecimalValue amount = null;

  @SerializedName("Branch")
  private StringValue branch = null;

  @SerializedName("CertifiedJob")
  private BooleanValue certifiedJob = null;

  @SerializedName("Code")
  private StringValue code = null;

  @SerializedName("CostCode")
  private StringValue costCode = null;

  @SerializedName("Date")
  private DateTimeValue date = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("Employee")
  private StringValue employee = null;

  @SerializedName("EmployeeName")
  private StringValue employeeName = null;

  @SerializedName("Hours")
  private DecimalValue hours = null;

  @SerializedName("LaborItem")
  private StringValue laborItem = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("Location")
  private StringValue location = null;

  @SerializedName("ManualRate")
  private BooleanValue manualRate = null;

  @SerializedName("Project")
  private StringValue project = null;

  @SerializedName("Rate")
  private DecimalValue rate = null;

  @SerializedName("ExcelRecordID")
  private StringValue excelRecordID = null;

  @SerializedName("ShiftCode")
  private StringValue shiftCode = null;

  @SerializedName("Subaccount")
  private StringValue subaccount = null;

  @SerializedName("Task")
  private StringValue task = null;

  @SerializedName("TimeActivity")
  private StringValue timeActivity = null;

  @SerializedName("UnionLocal")
  private StringValue unionLocal = null;

  @SerializedName("Units")
  private DecimalValue units = null;

  @SerializedName("UnitType")
  private StringValue unitType = null;

  @SerializedName("WCCCode")
  private StringValue wcCCode = null;

  public BatchEarningDetail account(StringValue account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @ApiModelProperty(value = "")
  public StringValue getAccount() {
    return account;
  }

  public void setAccount(StringValue account) {
    this.account = account;
  }

  public BatchEarningDetail allowCopy(BooleanValue allowCopy) {
    this.allowCopy = allowCopy;
    return this;
  }

   /**
   * Get allowCopy
   * @return allowCopy
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getAllowCopy() {
    return allowCopy;
  }

  public void setAllowCopy(BooleanValue allowCopy) {
    this.allowCopy = allowCopy;
  }

  public BatchEarningDetail amount(DecimalValue amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getAmount() {
    return amount;
  }

  public void setAmount(DecimalValue amount) {
    this.amount = amount;
  }

  public BatchEarningDetail branch(StringValue branch) {
    this.branch = branch;
    return this;
  }

   /**
   * Get branch
   * @return branch
  **/
  @ApiModelProperty(value = "")
  public StringValue getBranch() {
    return branch;
  }

  public void setBranch(StringValue branch) {
    this.branch = branch;
  }

  public BatchEarningDetail certifiedJob(BooleanValue certifiedJob) {
    this.certifiedJob = certifiedJob;
    return this;
  }

   /**
   * Get certifiedJob
   * @return certifiedJob
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getCertifiedJob() {
    return certifiedJob;
  }

  public void setCertifiedJob(BooleanValue certifiedJob) {
    this.certifiedJob = certifiedJob;
  }

  public BatchEarningDetail code(StringValue code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public StringValue getCode() {
    return code;
  }

  public void setCode(StringValue code) {
    this.code = code;
  }

  public BatchEarningDetail costCode(StringValue costCode) {
    this.costCode = costCode;
    return this;
  }

   /**
   * Get costCode
   * @return costCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getCostCode() {
    return costCode;
  }

  public void setCostCode(StringValue costCode) {
    this.costCode = costCode;
  }

  public BatchEarningDetail date(DateTimeValue date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getDate() {
    return date;
  }

  public void setDate(DateTimeValue date) {
    this.date = date;
  }

  public BatchEarningDetail description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public BatchEarningDetail employee(StringValue employee) {
    this.employee = employee;
    return this;
  }

   /**
   * Get employee
   * @return employee
  **/
  @ApiModelProperty(value = "")
  public StringValue getEmployee() {
    return employee;
  }

  public void setEmployee(StringValue employee) {
    this.employee = employee;
  }

  public BatchEarningDetail employeeName(StringValue employeeName) {
    this.employeeName = employeeName;
    return this;
  }

   /**
   * Get employeeName
   * @return employeeName
  **/
  @ApiModelProperty(value = "")
  public StringValue getEmployeeName() {
    return employeeName;
  }

  public void setEmployeeName(StringValue employeeName) {
    this.employeeName = employeeName;
  }

  public BatchEarningDetail hours(DecimalValue hours) {
    this.hours = hours;
    return this;
  }

   /**
   * Get hours
   * @return hours
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getHours() {
    return hours;
  }

  public void setHours(DecimalValue hours) {
    this.hours = hours;
  }

  public BatchEarningDetail laborItem(StringValue laborItem) {
    this.laborItem = laborItem;
    return this;
  }

   /**
   * Get laborItem
   * @return laborItem
  **/
  @ApiModelProperty(value = "")
  public StringValue getLaborItem() {
    return laborItem;
  }

  public void setLaborItem(StringValue laborItem) {
    this.laborItem = laborItem;
  }

  public BatchEarningDetail lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public BatchEarningDetail location(StringValue location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(value = "")
  public StringValue getLocation() {
    return location;
  }

  public void setLocation(StringValue location) {
    this.location = location;
  }

  public BatchEarningDetail manualRate(BooleanValue manualRate) {
    this.manualRate = manualRate;
    return this;
  }

   /**
   * Get manualRate
   * @return manualRate
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getManualRate() {
    return manualRate;
  }

  public void setManualRate(BooleanValue manualRate) {
    this.manualRate = manualRate;
  }

  public BatchEarningDetail project(StringValue project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @ApiModelProperty(value = "")
  public StringValue getProject() {
    return project;
  }

  public void setProject(StringValue project) {
    this.project = project;
  }

  public BatchEarningDetail rate(DecimalValue rate) {
    this.rate = rate;
    return this;
  }

   /**
   * Get rate
   * @return rate
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getRate() {
    return rate;
  }

  public void setRate(DecimalValue rate) {
    this.rate = rate;
  }

  public BatchEarningDetail excelRecordID(StringValue excelRecordID) {
    this.excelRecordID = excelRecordID;
    return this;
  }

   /**
   * Get excelRecordID
   * @return excelRecordID
  **/
  @ApiModelProperty(value = "")
  public StringValue getExcelRecordID() {
    return excelRecordID;
  }

  public void setExcelRecordID(StringValue excelRecordID) {
    this.excelRecordID = excelRecordID;
  }

  public BatchEarningDetail shiftCode(StringValue shiftCode) {
    this.shiftCode = shiftCode;
    return this;
  }

   /**
   * Get shiftCode
   * @return shiftCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getShiftCode() {
    return shiftCode;
  }

  public void setShiftCode(StringValue shiftCode) {
    this.shiftCode = shiftCode;
  }

  public BatchEarningDetail subaccount(StringValue subaccount) {
    this.subaccount = subaccount;
    return this;
  }

   /**
   * Get subaccount
   * @return subaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getSubaccount() {
    return subaccount;
  }

  public void setSubaccount(StringValue subaccount) {
    this.subaccount = subaccount;
  }

  public BatchEarningDetail task(StringValue task) {
    this.task = task;
    return this;
  }

   /**
   * Get task
   * @return task
  **/
  @ApiModelProperty(value = "")
  public StringValue getTask() {
    return task;
  }

  public void setTask(StringValue task) {
    this.task = task;
  }

  public BatchEarningDetail timeActivity(StringValue timeActivity) {
    this.timeActivity = timeActivity;
    return this;
  }

   /**
   * Get timeActivity
   * @return timeActivity
  **/
  @ApiModelProperty(value = "")
  public StringValue getTimeActivity() {
    return timeActivity;
  }

  public void setTimeActivity(StringValue timeActivity) {
    this.timeActivity = timeActivity;
  }

  public BatchEarningDetail unionLocal(StringValue unionLocal) {
    this.unionLocal = unionLocal;
    return this;
  }

   /**
   * Get unionLocal
   * @return unionLocal
  **/
  @ApiModelProperty(value = "")
  public StringValue getUnionLocal() {
    return unionLocal;
  }

  public void setUnionLocal(StringValue unionLocal) {
    this.unionLocal = unionLocal;
  }

  public BatchEarningDetail units(DecimalValue units) {
    this.units = units;
    return this;
  }

   /**
   * Get units
   * @return units
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getUnits() {
    return units;
  }

  public void setUnits(DecimalValue units) {
    this.units = units;
  }

  public BatchEarningDetail unitType(StringValue unitType) {
    this.unitType = unitType;
    return this;
  }

   /**
   * Get unitType
   * @return unitType
  **/
  @ApiModelProperty(value = "")
  public StringValue getUnitType() {
    return unitType;
  }

  public void setUnitType(StringValue unitType) {
    this.unitType = unitType;
  }

  public BatchEarningDetail wcCCode(StringValue wcCCode) {
    this.wcCCode = wcCCode;
    return this;
  }

   /**
   * Get wcCCode
   * @return wcCCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getWcCCode() {
    return wcCCode;
  }

  public void setWcCCode(StringValue wcCCode) {
    this.wcCCode = wcCCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchEarningDetail batchEarningDetail = (BatchEarningDetail) o;
    return Objects.equals(this.account, batchEarningDetail.account) &&
        Objects.equals(this.allowCopy, batchEarningDetail.allowCopy) &&
        Objects.equals(this.amount, batchEarningDetail.amount) &&
        Objects.equals(this.branch, batchEarningDetail.branch) &&
        Objects.equals(this.certifiedJob, batchEarningDetail.certifiedJob) &&
        Objects.equals(this.code, batchEarningDetail.code) &&
        Objects.equals(this.costCode, batchEarningDetail.costCode) &&
        Objects.equals(this.date, batchEarningDetail.date) &&
        Objects.equals(this.description, batchEarningDetail.description) &&
        Objects.equals(this.employee, batchEarningDetail.employee) &&
        Objects.equals(this.employeeName, batchEarningDetail.employeeName) &&
        Objects.equals(this.hours, batchEarningDetail.hours) &&
        Objects.equals(this.laborItem, batchEarningDetail.laborItem) &&
        Objects.equals(this.lastModifiedDateTime, batchEarningDetail.lastModifiedDateTime) &&
        Objects.equals(this.location, batchEarningDetail.location) &&
        Objects.equals(this.manualRate, batchEarningDetail.manualRate) &&
        Objects.equals(this.project, batchEarningDetail.project) &&
        Objects.equals(this.rate, batchEarningDetail.rate) &&
        Objects.equals(this.excelRecordID, batchEarningDetail.excelRecordID) &&
        Objects.equals(this.shiftCode, batchEarningDetail.shiftCode) &&
        Objects.equals(this.subaccount, batchEarningDetail.subaccount) &&
        Objects.equals(this.task, batchEarningDetail.task) &&
        Objects.equals(this.timeActivity, batchEarningDetail.timeActivity) &&
        Objects.equals(this.unionLocal, batchEarningDetail.unionLocal) &&
        Objects.equals(this.units, batchEarningDetail.units) &&
        Objects.equals(this.unitType, batchEarningDetail.unitType) &&
        Objects.equals(this.wcCCode, batchEarningDetail.wcCCode) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, allowCopy, amount, branch, certifiedJob, code, costCode, date, description, employee, employeeName, hours, laborItem, lastModifiedDateTime, location, manualRate, project, rate, excelRecordID, shiftCode, subaccount, task, timeActivity, unionLocal, units, unitType, wcCCode, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchEarningDetail {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    allowCopy: ").append(toIndentedString(allowCopy)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("    certifiedJob: ").append(toIndentedString(certifiedJob)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    costCode: ").append(toIndentedString(costCode)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    employee: ").append(toIndentedString(employee)).append("\n");
    sb.append("    employeeName: ").append(toIndentedString(employeeName)).append("\n");
    sb.append("    hours: ").append(toIndentedString(hours)).append("\n");
    sb.append("    laborItem: ").append(toIndentedString(laborItem)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    manualRate: ").append(toIndentedString(manualRate)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    excelRecordID: ").append(toIndentedString(excelRecordID)).append("\n");
    sb.append("    shiftCode: ").append(toIndentedString(shiftCode)).append("\n");
    sb.append("    subaccount: ").append(toIndentedString(subaccount)).append("\n");
    sb.append("    task: ").append(toIndentedString(task)).append("\n");
    sb.append("    timeActivity: ").append(toIndentedString(timeActivity)).append("\n");
    sb.append("    unionLocal: ").append(toIndentedString(unionLocal)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    unitType: ").append(toIndentedString(unitType)).append("\n");
    sb.append("    wcCCode: ").append(toIndentedString(wcCCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

