/*
 * Default/22.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import model.BooleanValue;
import model.CustomField;
import model.DateTimeValue;
import model.DecimalValue;
import model.Entity;
import model.FileLink;
import model.StringValue;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * BatchOvertimeRulesDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-17T14:29:48.617Z")
public class BatchOvertimeRulesDetail extends Entity {
  @SerializedName("DayofWeek")
  private StringValue dayofWeek = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("DisbursingEarningType")
  private StringValue disbursingEarningType = null;

  @SerializedName("Enabled")
  private BooleanValue enabled = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("Multiplier")
  private DecimalValue multiplier = null;

  @SerializedName("OvertimeRule")
  private StringValue overtimeRule = null;

  @SerializedName("Project")
  private StringValue project = null;

  @SerializedName("State")
  private StringValue state = null;

  @SerializedName("ThresholdforOvertimehours")
  private DecimalValue thresholdforOvertimehours = null;

  @SerializedName("Type")
  private StringValue type = null;

  @SerializedName("UnionLocal")
  private StringValue unionLocal = null;

  public BatchOvertimeRulesDetail dayofWeek(StringValue dayofWeek) {
    this.dayofWeek = dayofWeek;
    return this;
  }

   /**
   * Get dayofWeek
   * @return dayofWeek
  **/
  @ApiModelProperty(value = "")
  public StringValue getDayofWeek() {
    return dayofWeek;
  }

  public void setDayofWeek(StringValue dayofWeek) {
    this.dayofWeek = dayofWeek;
  }

  public BatchOvertimeRulesDetail description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public BatchOvertimeRulesDetail disbursingEarningType(StringValue disbursingEarningType) {
    this.disbursingEarningType = disbursingEarningType;
    return this;
  }

   /**
   * Get disbursingEarningType
   * @return disbursingEarningType
  **/
  @ApiModelProperty(value = "")
  public StringValue getDisbursingEarningType() {
    return disbursingEarningType;
  }

  public void setDisbursingEarningType(StringValue disbursingEarningType) {
    this.disbursingEarningType = disbursingEarningType;
  }

  public BatchOvertimeRulesDetail enabled(BooleanValue enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getEnabled() {
    return enabled;
  }

  public void setEnabled(BooleanValue enabled) {
    this.enabled = enabled;
  }

  public BatchOvertimeRulesDetail lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public BatchOvertimeRulesDetail multiplier(DecimalValue multiplier) {
    this.multiplier = multiplier;
    return this;
  }

   /**
   * Get multiplier
   * @return multiplier
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getMultiplier() {
    return multiplier;
  }

  public void setMultiplier(DecimalValue multiplier) {
    this.multiplier = multiplier;
  }

  public BatchOvertimeRulesDetail overtimeRule(StringValue overtimeRule) {
    this.overtimeRule = overtimeRule;
    return this;
  }

   /**
   * Get overtimeRule
   * @return overtimeRule
  **/
  @ApiModelProperty(value = "")
  public StringValue getOvertimeRule() {
    return overtimeRule;
  }

  public void setOvertimeRule(StringValue overtimeRule) {
    this.overtimeRule = overtimeRule;
  }

  public BatchOvertimeRulesDetail project(StringValue project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @ApiModelProperty(value = "")
  public StringValue getProject() {
    return project;
  }

  public void setProject(StringValue project) {
    this.project = project;
  }

  public BatchOvertimeRulesDetail state(StringValue state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public StringValue getState() {
    return state;
  }

  public void setState(StringValue state) {
    this.state = state;
  }

  public BatchOvertimeRulesDetail thresholdforOvertimehours(DecimalValue thresholdforOvertimehours) {
    this.thresholdforOvertimehours = thresholdforOvertimehours;
    return this;
  }

   /**
   * Get thresholdforOvertimehours
   * @return thresholdforOvertimehours
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getThresholdforOvertimehours() {
    return thresholdforOvertimehours;
  }

  public void setThresholdforOvertimehours(DecimalValue thresholdforOvertimehours) {
    this.thresholdforOvertimehours = thresholdforOvertimehours;
  }

  public BatchOvertimeRulesDetail type(StringValue type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public StringValue getType() {
    return type;
  }

  public void setType(StringValue type) {
    this.type = type;
  }

  public BatchOvertimeRulesDetail unionLocal(StringValue unionLocal) {
    this.unionLocal = unionLocal;
    return this;
  }

   /**
   * Get unionLocal
   * @return unionLocal
  **/
  @ApiModelProperty(value = "")
  public StringValue getUnionLocal() {
    return unionLocal;
  }

  public void setUnionLocal(StringValue unionLocal) {
    this.unionLocal = unionLocal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchOvertimeRulesDetail batchOvertimeRulesDetail = (BatchOvertimeRulesDetail) o;
    return Objects.equals(this.dayofWeek, batchOvertimeRulesDetail.dayofWeek) &&
        Objects.equals(this.description, batchOvertimeRulesDetail.description) &&
        Objects.equals(this.disbursingEarningType, batchOvertimeRulesDetail.disbursingEarningType) &&
        Objects.equals(this.enabled, batchOvertimeRulesDetail.enabled) &&
        Objects.equals(this.lastModifiedDateTime, batchOvertimeRulesDetail.lastModifiedDateTime) &&
        Objects.equals(this.multiplier, batchOvertimeRulesDetail.multiplier) &&
        Objects.equals(this.overtimeRule, batchOvertimeRulesDetail.overtimeRule) &&
        Objects.equals(this.project, batchOvertimeRulesDetail.project) &&
        Objects.equals(this.state, batchOvertimeRulesDetail.state) &&
        Objects.equals(this.thresholdforOvertimehours, batchOvertimeRulesDetail.thresholdforOvertimehours) &&
        Objects.equals(this.type, batchOvertimeRulesDetail.type) &&
        Objects.equals(this.unionLocal, batchOvertimeRulesDetail.unionLocal) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dayofWeek, description, disbursingEarningType, enabled, lastModifiedDateTime, multiplier, overtimeRule, project, state, thresholdforOvertimehours, type, unionLocal, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchOvertimeRulesDetail {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    dayofWeek: ").append(toIndentedString(dayofWeek)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    disbursingEarningType: ").append(toIndentedString(disbursingEarningType)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    lastModifiedDateTime: ").append(toIndentedString(lastModifiedDateTime)).append("\n");
    sb.append("    multiplier: ").append(toIndentedString(multiplier)).append("\n");
    sb.append("    overtimeRule: ").append(toIndentedString(overtimeRule)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    thresholdforOvertimehours: ").append(toIndentedString(thresholdforOvertimehours)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    unionLocal: ").append(toIndentedString(unionLocal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

