/*
 * Default/22.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import model.BooleanValue;
import model.CustomField;
import model.Entity;
import model.FileLink;
import model.StringValue;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * BigCommerceStores
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-17T14:29:48.617Z")
public class BigCommerceStores extends Entity {
  @SerializedName("AccessToken")
  private StringValue accessToken = null;

  @SerializedName("Active")
  private BooleanValue active = null;

  @SerializedName("APIPath")
  private StringValue apIPath = null;

  @SerializedName("ClientID")
  private StringValue clientID = null;

  @SerializedName("Connector")
  private StringValue connector = null;

  @SerializedName("Default")
  private BooleanValue _default = null;

  @SerializedName("StoreAdminPath")
  private StringValue storeAdminPath = null;

  @SerializedName("StoreName")
  private StringValue storeName = null;

  @SerializedName("WebDAVPassword")
  private StringValue webDAVPassword = null;

  @SerializedName("WebDAVPath")
  private StringValue webDAVPath = null;

  @SerializedName("WebDAVUsername")
  private StringValue webDAVUsername = null;

  public BigCommerceStores accessToken(StringValue accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * Get accessToken
   * @return accessToken
  **/
  @ApiModelProperty(value = "")
  public StringValue getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(StringValue accessToken) {
    this.accessToken = accessToken;
  }

  public BigCommerceStores active(BooleanValue active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getActive() {
    return active;
  }

  public void setActive(BooleanValue active) {
    this.active = active;
  }

  public BigCommerceStores apIPath(StringValue apIPath) {
    this.apIPath = apIPath;
    return this;
  }

   /**
   * Get apIPath
   * @return apIPath
  **/
  @ApiModelProperty(value = "")
  public StringValue getApIPath() {
    return apIPath;
  }

  public void setApIPath(StringValue apIPath) {
    this.apIPath = apIPath;
  }

  public BigCommerceStores clientID(StringValue clientID) {
    this.clientID = clientID;
    return this;
  }

   /**
   * Get clientID
   * @return clientID
  **/
  @ApiModelProperty(value = "")
  public StringValue getClientID() {
    return clientID;
  }

  public void setClientID(StringValue clientID) {
    this.clientID = clientID;
  }

  public BigCommerceStores connector(StringValue connector) {
    this.connector = connector;
    return this;
  }

   /**
   * Get connector
   * @return connector
  **/
  @ApiModelProperty(value = "")
  public StringValue getConnector() {
    return connector;
  }

  public void setConnector(StringValue connector) {
    this.connector = connector;
  }

  public BigCommerceStores _default(BooleanValue _default) {
    this._default = _default;
    return this;
  }

   /**
   * Get _default
   * @return _default
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getDefault() {
    return _default;
  }

  public void setDefault(BooleanValue _default) {
    this._default = _default;
  }

  public BigCommerceStores storeAdminPath(StringValue storeAdminPath) {
    this.storeAdminPath = storeAdminPath;
    return this;
  }

   /**
   * Get storeAdminPath
   * @return storeAdminPath
  **/
  @ApiModelProperty(value = "")
  public StringValue getStoreAdminPath() {
    return storeAdminPath;
  }

  public void setStoreAdminPath(StringValue storeAdminPath) {
    this.storeAdminPath = storeAdminPath;
  }

  public BigCommerceStores storeName(StringValue storeName) {
    this.storeName = storeName;
    return this;
  }

   /**
   * Get storeName
   * @return storeName
  **/
  @ApiModelProperty(value = "")
  public StringValue getStoreName() {
    return storeName;
  }

  public void setStoreName(StringValue storeName) {
    this.storeName = storeName;
  }

  public BigCommerceStores webDAVPassword(StringValue webDAVPassword) {
    this.webDAVPassword = webDAVPassword;
    return this;
  }

   /**
   * Get webDAVPassword
   * @return webDAVPassword
  **/
  @ApiModelProperty(value = "")
  public StringValue getWebDAVPassword() {
    return webDAVPassword;
  }

  public void setWebDAVPassword(StringValue webDAVPassword) {
    this.webDAVPassword = webDAVPassword;
  }

  public BigCommerceStores webDAVPath(StringValue webDAVPath) {
    this.webDAVPath = webDAVPath;
    return this;
  }

   /**
   * Get webDAVPath
   * @return webDAVPath
  **/
  @ApiModelProperty(value = "")
  public StringValue getWebDAVPath() {
    return webDAVPath;
  }

  public void setWebDAVPath(StringValue webDAVPath) {
    this.webDAVPath = webDAVPath;
  }

  public BigCommerceStores webDAVUsername(StringValue webDAVUsername) {
    this.webDAVUsername = webDAVUsername;
    return this;
  }

   /**
   * Get webDAVUsername
   * @return webDAVUsername
  **/
  @ApiModelProperty(value = "")
  public StringValue getWebDAVUsername() {
    return webDAVUsername;
  }

  public void setWebDAVUsername(StringValue webDAVUsername) {
    this.webDAVUsername = webDAVUsername;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BigCommerceStores bigCommerceStores = (BigCommerceStores) o;
    return Objects.equals(this.accessToken, bigCommerceStores.accessToken) &&
        Objects.equals(this.active, bigCommerceStores.active) &&
        Objects.equals(this.apIPath, bigCommerceStores.apIPath) &&
        Objects.equals(this.clientID, bigCommerceStores.clientID) &&
        Objects.equals(this.connector, bigCommerceStores.connector) &&
        Objects.equals(this._default, bigCommerceStores._default) &&
        Objects.equals(this.storeAdminPath, bigCommerceStores.storeAdminPath) &&
        Objects.equals(this.storeName, bigCommerceStores.storeName) &&
        Objects.equals(this.webDAVPassword, bigCommerceStores.webDAVPassword) &&
        Objects.equals(this.webDAVPath, bigCommerceStores.webDAVPath) &&
        Objects.equals(this.webDAVUsername, bigCommerceStores.webDAVUsername) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, active, apIPath, clientID, connector, _default, storeAdminPath, storeName, webDAVPassword, webDAVPath, webDAVUsername, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BigCommerceStores {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    apIPath: ").append(toIndentedString(apIPath)).append("\n");
    sb.append("    clientID: ").append(toIndentedString(clientID)).append("\n");
    sb.append("    connector: ").append(toIndentedString(connector)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    storeAdminPath: ").append(toIndentedString(storeAdminPath)).append("\n");
    sb.append("    storeName: ").append(toIndentedString(storeName)).append("\n");
    sb.append("    webDAVPassword: ").append(toIndentedString(webDAVPassword)).append("\n");
    sb.append("    webDAVPath: ").append(toIndentedString(webDAVPath)).append("\n");
    sb.append("    webDAVUsername: ").append(toIndentedString(webDAVUsername)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

