/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * BusinessAccountShippingContact
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class BusinessAccountShippingContact extends Entity {
  @SerializedName("Attention")
  private StringValue attention = null;

  @SerializedName("Email")
  private StringValue email = null;

  @SerializedName("Fax")
  private StringValue fax = null;

  @SerializedName("JobTitle")
  private StringValue jobTitle = null;

  @SerializedName("Phone1")
  private StringValue phone1 = null;

  @SerializedName("Phone2")
  private StringValue phone2 = null;

  @SerializedName("Override")
  private BooleanValue override = null;

  public BusinessAccountShippingContact attention(StringValue attention) {
    this.attention = attention;
    return this;
  }

   /**
   * Get attention
   * @return attention
  **/
  @ApiModelProperty(value = "")
  public StringValue getAttention() {
    return attention;
  }

  public void setAttention(StringValue attention) {
    this.attention = attention;
  }

  public BusinessAccountShippingContact email(StringValue email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public StringValue getEmail() {
    return email;
  }

  public void setEmail(StringValue email) {
    this.email = email;
  }

  public BusinessAccountShippingContact fax(StringValue fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Get fax
   * @return fax
  **/
  @ApiModelProperty(value = "")
  public StringValue getFax() {
    return fax;
  }

  public void setFax(StringValue fax) {
    this.fax = fax;
  }

  public BusinessAccountShippingContact jobTitle(StringValue jobTitle) {
    this.jobTitle = jobTitle;
    return this;
  }

   /**
   * Get jobTitle
   * @return jobTitle
  **/
  @ApiModelProperty(value = "")
  public StringValue getJobTitle() {
    return jobTitle;
  }

  public void setJobTitle(StringValue jobTitle) {
    this.jobTitle = jobTitle;
  }

  public BusinessAccountShippingContact phone1(StringValue phone1) {
    this.phone1 = phone1;
    return this;
  }

   /**
   * Get phone1
   * @return phone1
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone1() {
    return phone1;
  }

  public void setPhone1(StringValue phone1) {
    this.phone1 = phone1;
  }

  public BusinessAccountShippingContact phone2(StringValue phone2) {
    this.phone2 = phone2;
    return this;
  }

   /**
   * Get phone2
   * @return phone2
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone2() {
    return phone2;
  }

  public void setPhone2(StringValue phone2) {
    this.phone2 = phone2;
  }

  public BusinessAccountShippingContact override(BooleanValue override) {
    this.override = override;
    return this;
  }

   /**
   * Get override
   * @return override
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getOverride() {
    return override;
  }

  public void setOverride(BooleanValue override) {
    this.override = override;
  }

}

