/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * ChangeOrderClass
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class ChangeOrderClass extends Entity {
  @SerializedName("Active")
  private BooleanValue active = null;

  @SerializedName("Attributes")
  private List<BusinessAccountClassAttributeDetail> attributes = null;

  @SerializedName("ClassID")
  private StringValue classID = null;

  @SerializedName("Commitments")
  private BooleanValue commitments = null;

  @SerializedName("CostBudget")
  private BooleanValue costBudget = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("RevenueBudget")
  private BooleanValue revenueBudget = null;

  public ChangeOrderClass active(BooleanValue active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getActive() {
    return active;
  }

  public void setActive(BooleanValue active) {
    this.active = active;
  }

  public ChangeOrderClass attributes(List<BusinessAccountClassAttributeDetail> attributes) {
    this.attributes = attributes;
    return this;
  }

  public ChangeOrderClass addAttributesItem(BusinessAccountClassAttributeDetail attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(value = "")
  public List<BusinessAccountClassAttributeDetail> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<BusinessAccountClassAttributeDetail> attributes) {
    this.attributes = attributes;
  }

  public ChangeOrderClass classID(StringValue classID) {
    this.classID = classID;
    return this;
  }

   /**
   * Get classID
   * @return classID
  **/
  @ApiModelProperty(value = "")
  public StringValue getClassID() {
    return classID;
  }

  public void setClassID(StringValue classID) {
    this.classID = classID;
  }

  public ChangeOrderClass commitments(BooleanValue commitments) {
    this.commitments = commitments;
    return this;
  }

   /**
   * Get commitments
   * @return commitments
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getCommitments() {
    return commitments;
  }

  public void setCommitments(BooleanValue commitments) {
    this.commitments = commitments;
  }

  public ChangeOrderClass costBudget(BooleanValue costBudget) {
    this.costBudget = costBudget;
    return this;
  }

   /**
   * Get costBudget
   * @return costBudget
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getCostBudget() {
    return costBudget;
  }

  public void setCostBudget(BooleanValue costBudget) {
    this.costBudget = costBudget;
  }

  public ChangeOrderClass description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public ChangeOrderClass lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public ChangeOrderClass revenueBudget(BooleanValue revenueBudget) {
    this.revenueBudget = revenueBudget;
    return this;
  }

   /**
   * Get revenueBudget
   * @return revenueBudget
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getRevenueBudget() {
    return revenueBudget;
  }

  public void setRevenueBudget(BooleanValue revenueBudget) {
    this.revenueBudget = revenueBudget;
  }

}

