/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Contact
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class Contact extends Entity {
  @SerializedName("Active")
  private BooleanValue active = null;

  @SerializedName("Activities")
  private List<ActivityDetail> activities = null;

  @SerializedName("Address")
  private Address address = null;

  @SerializedName("OverrideAccountAddress")
  private BooleanValue overrideAccountAddress = null;

  @SerializedName("AddressValidated")
  private BooleanValue addressValidated = null;

  @SerializedName("Attention")
  private StringValue attention = null;

  @SerializedName("Attributes")
  private List<AttributeValue> attributes = null;

  @SerializedName("BusinessAccount")
  private StringValue businessAccount = null;

  @SerializedName("Campaigns")
  private List<CampaignDetail> campaigns = null;

  @SerializedName("Cases")
  private List<CaseDetail> cases = null;

  @SerializedName("CompanyName")
  private StringValue companyName = null;

  @SerializedName("ContactClass")
  private StringValue contactClass = null;

  @SerializedName("ContactID")
  private IntValue contactID = null;

  @SerializedName("ContactMethod")
  private StringValue contactMethod = null;

  @SerializedName("ConvertedBy")
  private StringValue convertedBy = null;

  @SerializedName("DateOfBirth")
  private DateTimeValue dateOfBirth = null;

  @SerializedName("DisplayName")
  private StringValue displayName = null;

  @SerializedName("DoNotCall")
  private BooleanValue doNotCall = null;

  @SerializedName("DoNotEmail")
  private BooleanValue doNotEmail = null;

  @SerializedName("DoNotFax")
  private BooleanValue doNotFax = null;

  @SerializedName("DoNotMail")
  private BooleanValue doNotMail = null;

  @SerializedName("Duplicate")
  private StringValue duplicate = null;

  @SerializedName("DuplicateFound")
  private BooleanValue duplicateFound = null;

  @SerializedName("Duplicates")
  private List<ContactDuplicateDetail> duplicates = null;

  @SerializedName("Email")
  private StringValue email = null;

  @SerializedName("Fax")
  private StringValue fax = null;

  @SerializedName("FaxType")
  private StringValue faxType = null;

  @SerializedName("FirstName")
  private StringValue firstName = null;

  @SerializedName("Gender")
  private StringValue gender = null;

  @SerializedName("Image")
  private StringValue image = null;

  @SerializedName("JobTitle")
  private StringValue jobTitle = null;

  @SerializedName("LanguageOrLocale")
  private StringValue languageOrLocale = null;

  @SerializedName("LastIncomingActivity")
  private DateTimeValue lastIncomingActivity = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("LastName")
  private StringValue lastName = null;

  @SerializedName("LastOutgoingActivity")
  private DateTimeValue lastOutgoingActivity = null;

  @SerializedName("MaritalStatus")
  private StringValue maritalStatus = null;

  @SerializedName("MarketingLists")
  private List<MarketingListDetail> marketingLists = null;

  @SerializedName("MiddleName")
  private StringValue middleName = null;

  @SerializedName("NoMarketing")
  private BooleanValue noMarketing = null;

  @SerializedName("NoMassMail")
  private BooleanValue noMassMail = null;

  @SerializedName("Notifications")
  private List<ContactNotification> notifications = null;

  @SerializedName("Opportunities")
  private List<OpportunityDetail> opportunities = null;

  @SerializedName("Owner")
  private StringValue owner = null;

  @SerializedName("OwnerEmployeeName")
  private StringValue ownerEmployeeName = null;

  @SerializedName("ParentAccount")
  private StringValue parentAccount = null;

  @SerializedName("Phone1")
  private StringValue phone1 = null;

  @SerializedName("Phone1Type")
  private StringValue phone1Type = null;

  @SerializedName("Phone2")
  private StringValue phone2 = null;

  @SerializedName("Phone2Type")
  private StringValue phone2Type = null;

  @SerializedName("Phone3")
  private StringValue phone3 = null;

  @SerializedName("Phone3Type")
  private StringValue phone3Type = null;

  @SerializedName("QualificationDate")
  private DateTimeValue qualificationDate = null;

  @SerializedName("Reason")
  private StringValue reason = null;

  @SerializedName("Relations")
  private List<RelationDetail> relations = null;

  @SerializedName("Source")
  private StringValue source = null;

  @SerializedName("SourceCampaign")
  private StringValue sourceCampaign = null;

  @SerializedName("SpouseOrPartnerName")
  private StringValue spouseOrPartnerName = null;

  @SerializedName("Status")
  private StringValue status = null;

  @SerializedName("Synchronize")
  private BooleanValue synchronize = null;

  @SerializedName("Title")
  private StringValue title = null;

  @SerializedName("Type")
  private StringValue type = null;

  @SerializedName("UserInfo")
  private ContactUserInfo userInfo = null;

  @SerializedName("WebSite")
  private StringValue webSite = null;

  @SerializedName("Workgroup")
  private StringValue workgroup = null;

  @SerializedName("WorkgroupDescription")
  private StringValue workgroupDescription = null;

  @SerializedName("NoteID")
  private GuidValue noteID = null;

  public Contact active(BooleanValue active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getActive() {
    return active;
  }

  public void setActive(BooleanValue active) {
    this.active = active;
  }

  public Contact activities(List<ActivityDetail> activities) {
    this.activities = activities;
    return this;
  }

  public Contact addActivitiesItem(ActivityDetail activitiesItem) {
    if (this.activities == null) {
      this.activities = new ArrayList<>();
    }
    this.activities.add(activitiesItem);
    return this;
  }

   /**
   * Get activities
   * @return activities
  **/
  @ApiModelProperty(value = "")
  public List<ActivityDetail> getActivities() {
    return activities;
  }

  public void setActivities(List<ActivityDetail> activities) {
    this.activities = activities;
  }

  public Contact address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public Contact overrideAccountAddress(BooleanValue overrideAccountAddress) {
    this.overrideAccountAddress = overrideAccountAddress;
    return this;
  }

   /**
   * Get overrideAccountAddress
   * @return overrideAccountAddress
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getOverrideAccountAddress() {
    return overrideAccountAddress;
  }

  public void setOverrideAccountAddress(BooleanValue overrideAccountAddress) {
    this.overrideAccountAddress = overrideAccountAddress;
  }

  public Contact addressValidated(BooleanValue addressValidated) {
    this.addressValidated = addressValidated;
    return this;
  }

   /**
   * Get addressValidated
   * @return addressValidated
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getAddressValidated() {
    return addressValidated;
  }

  public void setAddressValidated(BooleanValue addressValidated) {
    this.addressValidated = addressValidated;
  }

  public Contact attention(StringValue attention) {
    this.attention = attention;
    return this;
  }

   /**
   * Get attention
   * @return attention
  **/
  @ApiModelProperty(value = "")
  public StringValue getAttention() {
    return attention;
  }

  public void setAttention(StringValue attention) {
    this.attention = attention;
  }

  public Contact attributes(List<AttributeValue> attributes) {
    this.attributes = attributes;
    return this;
  }

  public Contact addAttributesItem(AttributeValue attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(value = "")
  public List<AttributeValue> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<AttributeValue> attributes) {
    this.attributes = attributes;
  }

  public Contact businessAccount(StringValue businessAccount) {
    this.businessAccount = businessAccount;
    return this;
  }

   /**
   * Get businessAccount
   * @return businessAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getBusinessAccount() {
    return businessAccount;
  }

  public void setBusinessAccount(StringValue businessAccount) {
    this.businessAccount = businessAccount;
  }

  public Contact campaigns(List<CampaignDetail> campaigns) {
    this.campaigns = campaigns;
    return this;
  }

  public Contact addCampaignsItem(CampaignDetail campaignsItem) {
    if (this.campaigns == null) {
      this.campaigns = new ArrayList<>();
    }
    this.campaigns.add(campaignsItem);
    return this;
  }

   /**
   * Get campaigns
   * @return campaigns
  **/
  @ApiModelProperty(value = "")
  public List<CampaignDetail> getCampaigns() {
    return campaigns;
  }

  public void setCampaigns(List<CampaignDetail> campaigns) {
    this.campaigns = campaigns;
  }

  public Contact cases(List<CaseDetail> cases) {
    this.cases = cases;
    return this;
  }

  public Contact addCasesItem(CaseDetail casesItem) {
    if (this.cases == null) {
      this.cases = new ArrayList<>();
    }
    this.cases.add(casesItem);
    return this;
  }

   /**
   * Get cases
   * @return cases
  **/
  @ApiModelProperty(value = "")
  public List<CaseDetail> getCases() {
    return cases;
  }

  public void setCases(List<CaseDetail> cases) {
    this.cases = cases;
  }

  public Contact companyName(StringValue companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @ApiModelProperty(value = "")
  public StringValue getCompanyName() {
    return companyName;
  }

  public void setCompanyName(StringValue companyName) {
    this.companyName = companyName;
  }

  public Contact contactClass(StringValue contactClass) {
    this.contactClass = contactClass;
    return this;
  }

   /**
   * Get contactClass
   * @return contactClass
  **/
  @ApiModelProperty(value = "")
  public StringValue getContactClass() {
    return contactClass;
  }

  public void setContactClass(StringValue contactClass) {
    this.contactClass = contactClass;
  }

  public Contact contactID(IntValue contactID) {
    this.contactID = contactID;
    return this;
  }

   /**
   * Get contactID
   * @return contactID
  **/
  @ApiModelProperty(value = "")
  public IntValue getContactID() {
    return contactID;
  }

  public void setContactID(IntValue contactID) {
    this.contactID = contactID;
  }

  public Contact contactMethod(StringValue contactMethod) {
    this.contactMethod = contactMethod;
    return this;
  }

   /**
   * Get contactMethod
   * @return contactMethod
  **/
  @ApiModelProperty(value = "")
  public StringValue getContactMethod() {
    return contactMethod;
  }

  public void setContactMethod(StringValue contactMethod) {
    this.contactMethod = contactMethod;
  }

  public Contact convertedBy(StringValue convertedBy) {
    this.convertedBy = convertedBy;
    return this;
  }

   /**
   * Get convertedBy
   * @return convertedBy
  **/
  @ApiModelProperty(value = "")
  public StringValue getConvertedBy() {
    return convertedBy;
  }

  public void setConvertedBy(StringValue convertedBy) {
    this.convertedBy = convertedBy;
  }

  public Contact dateOfBirth(DateTimeValue dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * Get dateOfBirth
   * @return dateOfBirth
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(DateTimeValue dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public Contact displayName(StringValue displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public StringValue getDisplayName() {
    return displayName;
  }

  public void setDisplayName(StringValue displayName) {
    this.displayName = displayName;
  }

  public Contact doNotCall(BooleanValue doNotCall) {
    this.doNotCall = doNotCall;
    return this;
  }

   /**
   * Get doNotCall
   * @return doNotCall
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getDoNotCall() {
    return doNotCall;
  }

  public void setDoNotCall(BooleanValue doNotCall) {
    this.doNotCall = doNotCall;
  }

  public Contact doNotEmail(BooleanValue doNotEmail) {
    this.doNotEmail = doNotEmail;
    return this;
  }

   /**
   * Get doNotEmail
   * @return doNotEmail
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getDoNotEmail() {
    return doNotEmail;
  }

  public void setDoNotEmail(BooleanValue doNotEmail) {
    this.doNotEmail = doNotEmail;
  }

  public Contact doNotFax(BooleanValue doNotFax) {
    this.doNotFax = doNotFax;
    return this;
  }

   /**
   * Get doNotFax
   * @return doNotFax
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getDoNotFax() {
    return doNotFax;
  }

  public void setDoNotFax(BooleanValue doNotFax) {
    this.doNotFax = doNotFax;
  }

  public Contact doNotMail(BooleanValue doNotMail) {
    this.doNotMail = doNotMail;
    return this;
  }

   /**
   * Get doNotMail
   * @return doNotMail
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getDoNotMail() {
    return doNotMail;
  }

  public void setDoNotMail(BooleanValue doNotMail) {
    this.doNotMail = doNotMail;
  }

  public Contact duplicate(StringValue duplicate) {
    this.duplicate = duplicate;
    return this;
  }

   /**
   * Get duplicate
   * @return duplicate
  **/
  @ApiModelProperty(value = "")
  public StringValue getDuplicate() {
    return duplicate;
  }

  public void setDuplicate(StringValue duplicate) {
    this.duplicate = duplicate;
  }

  public Contact duplicateFound(BooleanValue duplicateFound) {
    this.duplicateFound = duplicateFound;
    return this;
  }

   /**
   * Get duplicateFound
   * @return duplicateFound
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getDuplicateFound() {
    return duplicateFound;
  }

  public void setDuplicateFound(BooleanValue duplicateFound) {
    this.duplicateFound = duplicateFound;
  }

  public Contact duplicates(List<ContactDuplicateDetail> duplicates) {
    this.duplicates = duplicates;
    return this;
  }

  public Contact addDuplicatesItem(ContactDuplicateDetail duplicatesItem) {
    if (this.duplicates == null) {
      this.duplicates = new ArrayList<>();
    }
    this.duplicates.add(duplicatesItem);
    return this;
  }

   /**
   * Get duplicates
   * @return duplicates
  **/
  @ApiModelProperty(value = "")
  public List<ContactDuplicateDetail> getDuplicates() {
    return duplicates;
  }

  public void setDuplicates(List<ContactDuplicateDetail> duplicates) {
    this.duplicates = duplicates;
  }

  public Contact email(StringValue email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public StringValue getEmail() {
    return email;
  }

  public void setEmail(StringValue email) {
    this.email = email;
  }

  public Contact fax(StringValue fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Get fax
   * @return fax
  **/
  @ApiModelProperty(value = "")
  public StringValue getFax() {
    return fax;
  }

  public void setFax(StringValue fax) {
    this.fax = fax;
  }

  public Contact faxType(StringValue faxType) {
    this.faxType = faxType;
    return this;
  }

   /**
   * Get faxType
   * @return faxType
  **/
  @ApiModelProperty(value = "")
  public StringValue getFaxType() {
    return faxType;
  }

  public void setFaxType(StringValue faxType) {
    this.faxType = faxType;
  }

  public Contact firstName(StringValue firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public StringValue getFirstName() {
    return firstName;
  }

  public void setFirstName(StringValue firstName) {
    this.firstName = firstName;
  }

  public Contact gender(StringValue gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(value = "")
  public StringValue getGender() {
    return gender;
  }

  public void setGender(StringValue gender) {
    this.gender = gender;
  }

  public Contact image(StringValue image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @ApiModelProperty(value = "")
  public StringValue getImage() {
    return image;
  }

  public void setImage(StringValue image) {
    this.image = image;
  }

  public Contact jobTitle(StringValue jobTitle) {
    this.jobTitle = jobTitle;
    return this;
  }

   /**
   * Get jobTitle
   * @return jobTitle
  **/
  @ApiModelProperty(value = "")
  public StringValue getJobTitle() {
    return jobTitle;
  }

  public void setJobTitle(StringValue jobTitle) {
    this.jobTitle = jobTitle;
  }

  public Contact languageOrLocale(StringValue languageOrLocale) {
    this.languageOrLocale = languageOrLocale;
    return this;
  }

   /**
   * Get languageOrLocale
   * @return languageOrLocale
  **/
  @ApiModelProperty(value = "")
  public StringValue getLanguageOrLocale() {
    return languageOrLocale;
  }

  public void setLanguageOrLocale(StringValue languageOrLocale) {
    this.languageOrLocale = languageOrLocale;
  }

  public Contact lastIncomingActivity(DateTimeValue lastIncomingActivity) {
    this.lastIncomingActivity = lastIncomingActivity;
    return this;
  }

   /**
   * Get lastIncomingActivity
   * @return lastIncomingActivity
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastIncomingActivity() {
    return lastIncomingActivity;
  }

  public void setLastIncomingActivity(DateTimeValue lastIncomingActivity) {
    this.lastIncomingActivity = lastIncomingActivity;
  }

  public Contact lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public Contact lastName(StringValue lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public StringValue getLastName() {
    return lastName;
  }

  public void setLastName(StringValue lastName) {
    this.lastName = lastName;
  }

  public Contact lastOutgoingActivity(DateTimeValue lastOutgoingActivity) {
    this.lastOutgoingActivity = lastOutgoingActivity;
    return this;
  }

   /**
   * Get lastOutgoingActivity
   * @return lastOutgoingActivity
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastOutgoingActivity() {
    return lastOutgoingActivity;
  }

  public void setLastOutgoingActivity(DateTimeValue lastOutgoingActivity) {
    this.lastOutgoingActivity = lastOutgoingActivity;
  }

  public Contact maritalStatus(StringValue maritalStatus) {
    this.maritalStatus = maritalStatus;
    return this;
  }

   /**
   * Get maritalStatus
   * @return maritalStatus
  **/
  @ApiModelProperty(value = "")
  public StringValue getMaritalStatus() {
    return maritalStatus;
  }

  public void setMaritalStatus(StringValue maritalStatus) {
    this.maritalStatus = maritalStatus;
  }

  public Contact marketingLists(List<MarketingListDetail> marketingLists) {
    this.marketingLists = marketingLists;
    return this;
  }

  public Contact addMarketingListsItem(MarketingListDetail marketingListsItem) {
    if (this.marketingLists == null) {
      this.marketingLists = new ArrayList<>();
    }
    this.marketingLists.add(marketingListsItem);
    return this;
  }

   /**
   * Get marketingLists
   * @return marketingLists
  **/
  @ApiModelProperty(value = "")
  public List<MarketingListDetail> getMarketingLists() {
    return marketingLists;
  }

  public void setMarketingLists(List<MarketingListDetail> marketingLists) {
    this.marketingLists = marketingLists;
  }

  public Contact middleName(StringValue middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * Get middleName
   * @return middleName
  **/
  @ApiModelProperty(value = "")
  public StringValue getMiddleName() {
    return middleName;
  }

  public void setMiddleName(StringValue middleName) {
    this.middleName = middleName;
  }

  public Contact noMarketing(BooleanValue noMarketing) {
    this.noMarketing = noMarketing;
    return this;
  }

   /**
   * Get noMarketing
   * @return noMarketing
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getNoMarketing() {
    return noMarketing;
  }

  public void setNoMarketing(BooleanValue noMarketing) {
    this.noMarketing = noMarketing;
  }

  public Contact noMassMail(BooleanValue noMassMail) {
    this.noMassMail = noMassMail;
    return this;
  }

   /**
   * Get noMassMail
   * @return noMassMail
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getNoMassMail() {
    return noMassMail;
  }

  public void setNoMassMail(BooleanValue noMassMail) {
    this.noMassMail = noMassMail;
  }

  public Contact notifications(List<ContactNotification> notifications) {
    this.notifications = notifications;
    return this;
  }

  public Contact addNotificationsItem(ContactNotification notificationsItem) {
    if (this.notifications == null) {
      this.notifications = new ArrayList<>();
    }
    this.notifications.add(notificationsItem);
    return this;
  }

   /**
   * Get notifications
   * @return notifications
  **/
  @ApiModelProperty(value = "")
  public List<ContactNotification> getNotifications() {
    return notifications;
  }

  public void setNotifications(List<ContactNotification> notifications) {
    this.notifications = notifications;
  }

  public Contact opportunities(List<OpportunityDetail> opportunities) {
    this.opportunities = opportunities;
    return this;
  }

  public Contact addOpportunitiesItem(OpportunityDetail opportunitiesItem) {
    if (this.opportunities == null) {
      this.opportunities = new ArrayList<>();
    }
    this.opportunities.add(opportunitiesItem);
    return this;
  }

   /**
   * Get opportunities
   * @return opportunities
  **/
  @ApiModelProperty(value = "")
  public List<OpportunityDetail> getOpportunities() {
    return opportunities;
  }

  public void setOpportunities(List<OpportunityDetail> opportunities) {
    this.opportunities = opportunities;
  }

  public Contact owner(StringValue owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @ApiModelProperty(value = "")
  public StringValue getOwner() {
    return owner;
  }

  public void setOwner(StringValue owner) {
    this.owner = owner;
  }

  public Contact ownerEmployeeName(StringValue ownerEmployeeName) {
    this.ownerEmployeeName = ownerEmployeeName;
    return this;
  }

   /**
   * Get ownerEmployeeName
   * @return ownerEmployeeName
  **/
  @ApiModelProperty(value = "")
  public StringValue getOwnerEmployeeName() {
    return ownerEmployeeName;
  }

  public void setOwnerEmployeeName(StringValue ownerEmployeeName) {
    this.ownerEmployeeName = ownerEmployeeName;
  }

  public Contact parentAccount(StringValue parentAccount) {
    this.parentAccount = parentAccount;
    return this;
  }

   /**
   * Get parentAccount
   * @return parentAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getParentAccount() {
    return parentAccount;
  }

  public void setParentAccount(StringValue parentAccount) {
    this.parentAccount = parentAccount;
  }

  public Contact phone1(StringValue phone1) {
    this.phone1 = phone1;
    return this;
  }

   /**
   * Get phone1
   * @return phone1
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone1() {
    return phone1;
  }

  public void setPhone1(StringValue phone1) {
    this.phone1 = phone1;
  }

  public Contact phone1Type(StringValue phone1Type) {
    this.phone1Type = phone1Type;
    return this;
  }

   /**
   * Get phone1Type
   * @return phone1Type
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone1Type() {
    return phone1Type;
  }

  public void setPhone1Type(StringValue phone1Type) {
    this.phone1Type = phone1Type;
  }

  public Contact phone2(StringValue phone2) {
    this.phone2 = phone2;
    return this;
  }

   /**
   * Get phone2
   * @return phone2
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone2() {
    return phone2;
  }

  public void setPhone2(StringValue phone2) {
    this.phone2 = phone2;
  }

  public Contact phone2Type(StringValue phone2Type) {
    this.phone2Type = phone2Type;
    return this;
  }

   /**
   * Get phone2Type
   * @return phone2Type
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone2Type() {
    return phone2Type;
  }

  public void setPhone2Type(StringValue phone2Type) {
    this.phone2Type = phone2Type;
  }

  public Contact phone3(StringValue phone3) {
    this.phone3 = phone3;
    return this;
  }

   /**
   * Get phone3
   * @return phone3
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone3() {
    return phone3;
  }

  public void setPhone3(StringValue phone3) {
    this.phone3 = phone3;
  }

  public Contact phone3Type(StringValue phone3Type) {
    this.phone3Type = phone3Type;
    return this;
  }

   /**
   * Get phone3Type
   * @return phone3Type
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone3Type() {
    return phone3Type;
  }

  public void setPhone3Type(StringValue phone3Type) {
    this.phone3Type = phone3Type;
  }

  public Contact qualificationDate(DateTimeValue qualificationDate) {
    this.qualificationDate = qualificationDate;
    return this;
  }

   /**
   * Get qualificationDate
   * @return qualificationDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getQualificationDate() {
    return qualificationDate;
  }

  public void setQualificationDate(DateTimeValue qualificationDate) {
    this.qualificationDate = qualificationDate;
  }

  public Contact reason(StringValue reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty(value = "")
  public StringValue getReason() {
    return reason;
  }

  public void setReason(StringValue reason) {
    this.reason = reason;
  }

  public Contact relations(List<RelationDetail> relations) {
    this.relations = relations;
    return this;
  }

  public Contact addRelationsItem(RelationDetail relationsItem) {
    if (this.relations == null) {
      this.relations = new ArrayList<>();
    }
    this.relations.add(relationsItem);
    return this;
  }

   /**
   * Get relations
   * @return relations
  **/
  @ApiModelProperty(value = "")
  public List<RelationDetail> getRelations() {
    return relations;
  }

  public void setRelations(List<RelationDetail> relations) {
    this.relations = relations;
  }

  public Contact source(StringValue source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @ApiModelProperty(value = "")
  public StringValue getSource() {
    return source;
  }

  public void setSource(StringValue source) {
    this.source = source;
  }

  public Contact sourceCampaign(StringValue sourceCampaign) {
    this.sourceCampaign = sourceCampaign;
    return this;
  }

   /**
   * Get sourceCampaign
   * @return sourceCampaign
  **/
  @ApiModelProperty(value = "")
  public StringValue getSourceCampaign() {
    return sourceCampaign;
  }

  public void setSourceCampaign(StringValue sourceCampaign) {
    this.sourceCampaign = sourceCampaign;
  }

  public Contact spouseOrPartnerName(StringValue spouseOrPartnerName) {
    this.spouseOrPartnerName = spouseOrPartnerName;
    return this;
  }

   /**
   * Get spouseOrPartnerName
   * @return spouseOrPartnerName
  **/
  @ApiModelProperty(value = "")
  public StringValue getSpouseOrPartnerName() {
    return spouseOrPartnerName;
  }

  public void setSpouseOrPartnerName(StringValue spouseOrPartnerName) {
    this.spouseOrPartnerName = spouseOrPartnerName;
  }

  public Contact status(StringValue status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StringValue getStatus() {
    return status;
  }

  public void setStatus(StringValue status) {
    this.status = status;
  }

  public Contact synchronize(BooleanValue synchronize) {
    this.synchronize = synchronize;
    return this;
  }

   /**
   * Get synchronize
   * @return synchronize
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getSynchronize() {
    return synchronize;
  }

  public void setSynchronize(BooleanValue synchronize) {
    this.synchronize = synchronize;
  }

  public Contact title(StringValue title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public StringValue getTitle() {
    return title;
  }

  public void setTitle(StringValue title) {
    this.title = title;
  }

  public Contact type(StringValue type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public StringValue getType() {
    return type;
  }

  public void setType(StringValue type) {
    this.type = type;
  }

  public Contact userInfo(ContactUserInfo userInfo) {
    this.userInfo = userInfo;
    return this;
  }

   /**
   * Get userInfo
   * @return userInfo
  **/
  @ApiModelProperty(value = "")
  public ContactUserInfo getUserInfo() {
    return userInfo;
  }

  public void setUserInfo(ContactUserInfo userInfo) {
    this.userInfo = userInfo;
  }

  public Contact webSite(StringValue webSite) {
    this.webSite = webSite;
    return this;
  }

   /**
   * Get webSite
   * @return webSite
  **/
  @ApiModelProperty(value = "")
  public StringValue getWebSite() {
    return webSite;
  }

  public void setWebSite(StringValue webSite) {
    this.webSite = webSite;
  }

  public Contact workgroup(StringValue workgroup) {
    this.workgroup = workgroup;
    return this;
  }

   /**
   * Get workgroup
   * @return workgroup
  **/
  @ApiModelProperty(value = "")
  public StringValue getWorkgroup() {
    return workgroup;
  }

  public void setWorkgroup(StringValue workgroup) {
    this.workgroup = workgroup;
  }

  public Contact workgroupDescription(StringValue workgroupDescription) {
    this.workgroupDescription = workgroupDescription;
    return this;
  }

   /**
   * Get workgroupDescription
   * @return workgroupDescription
  **/
  @ApiModelProperty(value = "")
  public StringValue getWorkgroupDescription() {
    return workgroupDescription;
  }

  public void setWorkgroupDescription(StringValue workgroupDescription) {
    this.workgroupDescription = workgroupDescription;
  }

  public Contact noteID(GuidValue noteID) {
    this.noteID = noteID;
    return this;
  }

   /**
   * Get noteID
   * @return noteID
  **/
  @ApiModelProperty(value = "")
  public GuidValue getNoteID() {
    return noteID;
  }

  public void setNoteID(GuidValue noteID) {
    this.noteID = noteID;
  }

}

