/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * ContactUserInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class ContactUserInfo extends Entity {
  @SerializedName("GeneratePassword")
  private BooleanValue generatePassword = null;

  @SerializedName("Login")
  private StringValue login = null;

  @SerializedName("Password")
  private StringValue password = null;

  @SerializedName("Roles")
  private List<ContactRoles> roles = null;

  @SerializedName("Status")
  private StringValue status = null;

  @SerializedName("UserType")
  private StringValue userType = null;

  public ContactUserInfo generatePassword(BooleanValue generatePassword) {
    this.generatePassword = generatePassword;
    return this;
  }

   /**
   * Get generatePassword
   * @return generatePassword
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getGeneratePassword() {
    return generatePassword;
  }

  public void setGeneratePassword(BooleanValue generatePassword) {
    this.generatePassword = generatePassword;
  }

  public ContactUserInfo login(StringValue login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  @ApiModelProperty(value = "")
  public StringValue getLogin() {
    return login;
  }

  public void setLogin(StringValue login) {
    this.login = login;
  }

  public ContactUserInfo password(StringValue password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public StringValue getPassword() {
    return password;
  }

  public void setPassword(StringValue password) {
    this.password = password;
  }

  public ContactUserInfo roles(List<ContactRoles> roles) {
    this.roles = roles;
    return this;
  }

  public ContactUserInfo addRolesItem(ContactRoles rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(value = "")
  public List<ContactRoles> getRoles() {
    return roles;
  }

  public void setRoles(List<ContactRoles> roles) {
    this.roles = roles;
  }

  public ContactUserInfo status(StringValue status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StringValue getStatus() {
    return status;
  }

  public void setStatus(StringValue status) {
    this.status = status;
  }

  public ContactUserInfo userType(StringValue userType) {
    this.userType = userType;
    return this;
  }

   /**
   * Get userType
   * @return userType
  **/
  @ApiModelProperty(value = "")
  public StringValue getUserType() {
    return userType;
  }

  public void setUserType(StringValue userType) {
    this.userType = userType;
  }

}

