/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Currency
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class Currency extends Entity {
  @SerializedName("Active")
  private BooleanValue active = null;

  @SerializedName("CreatedDateTime")
  private DateTimeValue createdDateTime = null;

  @SerializedName("CurrencyID")
  private StringValue currencyID = null;

  @SerializedName("CurrencySymbol")
  private StringValue currencySymbol = null;

  @SerializedName("DecimalPrecision")
  private ShortValue decimalPrecision = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("UseForAccounting")
  private BooleanValue useForAccounting = null;

  public Currency active(BooleanValue active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getActive() {
    return active;
  }

  public void setActive(BooleanValue active) {
    this.active = active;
  }

  public Currency createdDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public Currency currencyID(StringValue currencyID) {
    this.currencyID = currencyID;
    return this;
  }

   /**
   * Get currencyID
   * @return currencyID
  **/
  @ApiModelProperty(value = "")
  public StringValue getCurrencyID() {
    return currencyID;
  }

  public void setCurrencyID(StringValue currencyID) {
    this.currencyID = currencyID;
  }

  public Currency currencySymbol(StringValue currencySymbol) {
    this.currencySymbol = currencySymbol;
    return this;
  }

   /**
   * Get currencySymbol
   * @return currencySymbol
  **/
  @ApiModelProperty(value = "")
  public StringValue getCurrencySymbol() {
    return currencySymbol;
  }

  public void setCurrencySymbol(StringValue currencySymbol) {
    this.currencySymbol = currencySymbol;
  }

  public Currency decimalPrecision(ShortValue decimalPrecision) {
    this.decimalPrecision = decimalPrecision;
    return this;
  }

   /**
   * Get decimalPrecision
   * @return decimalPrecision
  **/
  @ApiModelProperty(value = "")
  public ShortValue getDecimalPrecision() {
    return decimalPrecision;
  }

  public void setDecimalPrecision(ShortValue decimalPrecision) {
    this.decimalPrecision = decimalPrecision;
  }

  public Currency description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public Currency lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public Currency useForAccounting(BooleanValue useForAccounting) {
    this.useForAccounting = useForAccounting;
    return this;
  }

   /**
   * Get useForAccounting
   * @return useForAccounting
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getUseForAccounting() {
    return useForAccounting;
  }

  public void setUseForAccounting(BooleanValue useForAccounting) {
    this.useForAccounting = useForAccounting;
  }

}

