/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * CustomerClass
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class CustomerClass extends Entity {
  @SerializedName("ApplyOverdueCharges")
  private BooleanValue applyOverdueCharges = null;

  @SerializedName("ARAccount")
  private StringValue arAccount = null;

  @SerializedName("ARSubaccount")
  private StringValue arSubaccount = null;

  @SerializedName("Attributes")
  private List<BusinessAccountClassAttributeDetail> attributes = null;

  @SerializedName("AutoApplyPayments")
  private BooleanValue autoApplyPayments = null;

  @SerializedName("CashDiscountAccount")
  private StringValue cashDiscountAccount = null;

  @SerializedName("CashDiscountSubaccount")
  private StringValue cashDiscountSubaccount = null;

  @SerializedName("ClassID")
  private StringValue classID = null;

  @SerializedName("COGSAccount")
  private StringValue coGSAccount = null;

  @SerializedName("COGSSubaccount")
  private StringValue coGSSubaccount = null;

  @SerializedName("Country")
  private StringValue country = null;

  @SerializedName("CreatedDateTime")
  private DateTimeValue createdDateTime = null;

  @SerializedName("CreditDaysPastDue")
  private ShortValue creditDaysPastDue = null;

  @SerializedName("CreditLimit")
  private DecimalValue creditLimit = null;

  @SerializedName("CreditVerification")
  private StringValue creditVerification = null;

  @SerializedName("CurrencyID")
  private StringValue currencyID = null;

  @SerializedName("CurrencyRateType")
  private StringValue currencyRateType = null;

  @SerializedName("DefaultLocationIDfromBranch")
  private BooleanValue defaultLocationIDfromBranch = null;

  @SerializedName("DefaultRestrictionGroup")
  private StringValue defaultRestrictionGroup = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("DiscountAccount")
  private StringValue discountAccount = null;

  @SerializedName("DiscountSubaccount")
  private StringValue discountSubaccount = null;

  @SerializedName("EnableCurrencyOverride")
  private BooleanValue enableCurrencyOverride = null;

  @SerializedName("EnableRateOverride")
  private BooleanValue enableRateOverride = null;

  @SerializedName("EnableWriteOffs")
  private BooleanValue enableWriteOffs = null;

  @SerializedName("EntityUsageType")
  private StringValue entityUsageType = null;

  @SerializedName("FreightAccount")
  private StringValue freightAccount = null;

  @SerializedName("FreightSubaccount")
  private StringValue freightSubaccount = null;

  @SerializedName("GroupDocumentDiscountLimit")
  private DecimalValue groupDocumentDiscountLimit = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("MiscAccount")
  private StringValue miscAccount = null;

  @SerializedName("MiscSubaccount")
  private StringValue miscSubaccount = null;

  @SerializedName("MultiCurrencyStatements")
  private BooleanValue multiCurrencyStatements = null;

  @SerializedName("OverdueChargeID")
  private StringValue overdueChargeID = null;

  @SerializedName("OverLimitAmount")
  private DecimalValue overLimitAmount = null;

  @SerializedName("PaymentMethod")
  private StringValue paymentMethod = null;

  @SerializedName("PrepaymentAccount")
  private StringValue prepaymentAccount = null;

  @SerializedName("PrepaymentSubaccount")
  private StringValue prepaymentSubaccount = null;

  @SerializedName("PrintDunningLetters")
  private BooleanValue printDunningLetters = null;

  @SerializedName("PrintInvoices")
  private BooleanValue printInvoices = null;

  @SerializedName("PrintStatements")
  private BooleanValue printStatements = null;

  @SerializedName("RequireEntityUsageType")
  private BooleanValue requireEntityUsageType = null;

  @SerializedName("RequireTaxZone")
  private BooleanValue requireTaxZone = null;

  @SerializedName("SalesAccount")
  private StringValue salesAccount = null;

  @SerializedName("SalespersonID")
  private StringValue salespersonID = null;

  @SerializedName("SalesSubaccount")
  private StringValue salesSubaccount = null;

  @SerializedName("SendDunningLettersbyEmail")
  private BooleanValue sendDunningLettersbyEmail = null;

  @SerializedName("SendInvoicesbyEmail")
  private BooleanValue sendInvoicesbyEmail = null;

  @SerializedName("SendStatementsByEmail")
  private BooleanValue sendStatementsByEmail = null;

  @SerializedName("ShippingRule")
  private StringValue shippingRule = null;

  @SerializedName("ShippingTerms")
  private StringValue shippingTerms = null;

  @SerializedName("ShipVia")
  private StringValue shipVia = null;

  @SerializedName("StatementCycleID")
  private StringValue statementCycleID = null;

  @SerializedName("StatementType")
  private StringValue statementType = null;

  @SerializedName("TaxZoneID")
  private StringValue taxZoneID = null;

  @SerializedName("Terms")
  private StringValue terms = null;

  @SerializedName("UnrealizedGainAccount")
  private StringValue unrealizedGainAccount = null;

  @SerializedName("UnrealizedGainSubaccount")
  private StringValue unrealizedGainSubaccount = null;

  @SerializedName("UnrealizedLossAccount")
  private StringValue unrealizedLossAccount = null;

  @SerializedName("UnrealizedLossSubaccount")
  private StringValue unrealizedLossSubaccount = null;

  @SerializedName("WriteOffLimit")
  private DecimalValue writeOffLimit = null;

  public CustomerClass applyOverdueCharges(BooleanValue applyOverdueCharges) {
    this.applyOverdueCharges = applyOverdueCharges;
    return this;
  }

   /**
   * Get applyOverdueCharges
   * @return applyOverdueCharges
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getApplyOverdueCharges() {
    return applyOverdueCharges;
  }

  public void setApplyOverdueCharges(BooleanValue applyOverdueCharges) {
    this.applyOverdueCharges = applyOverdueCharges;
  }

  public CustomerClass arAccount(StringValue arAccount) {
    this.arAccount = arAccount;
    return this;
  }

   /**
   * Get arAccount
   * @return arAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getArAccount() {
    return arAccount;
  }

  public void setArAccount(StringValue arAccount) {
    this.arAccount = arAccount;
  }

  public CustomerClass arSubaccount(StringValue arSubaccount) {
    this.arSubaccount = arSubaccount;
    return this;
  }

   /**
   * Get arSubaccount
   * @return arSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getArSubaccount() {
    return arSubaccount;
  }

  public void setArSubaccount(StringValue arSubaccount) {
    this.arSubaccount = arSubaccount;
  }

  public CustomerClass attributes(List<BusinessAccountClassAttributeDetail> attributes) {
    this.attributes = attributes;
    return this;
  }

  public CustomerClass addAttributesItem(BusinessAccountClassAttributeDetail attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(value = "")
  public List<BusinessAccountClassAttributeDetail> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<BusinessAccountClassAttributeDetail> attributes) {
    this.attributes = attributes;
  }

  public CustomerClass autoApplyPayments(BooleanValue autoApplyPayments) {
    this.autoApplyPayments = autoApplyPayments;
    return this;
  }

   /**
   * Get autoApplyPayments
   * @return autoApplyPayments
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getAutoApplyPayments() {
    return autoApplyPayments;
  }

  public void setAutoApplyPayments(BooleanValue autoApplyPayments) {
    this.autoApplyPayments = autoApplyPayments;
  }

  public CustomerClass cashDiscountAccount(StringValue cashDiscountAccount) {
    this.cashDiscountAccount = cashDiscountAccount;
    return this;
  }

   /**
   * Get cashDiscountAccount
   * @return cashDiscountAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getCashDiscountAccount() {
    return cashDiscountAccount;
  }

  public void setCashDiscountAccount(StringValue cashDiscountAccount) {
    this.cashDiscountAccount = cashDiscountAccount;
  }

  public CustomerClass cashDiscountSubaccount(StringValue cashDiscountSubaccount) {
    this.cashDiscountSubaccount = cashDiscountSubaccount;
    return this;
  }

   /**
   * Get cashDiscountSubaccount
   * @return cashDiscountSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getCashDiscountSubaccount() {
    return cashDiscountSubaccount;
  }

  public void setCashDiscountSubaccount(StringValue cashDiscountSubaccount) {
    this.cashDiscountSubaccount = cashDiscountSubaccount;
  }

  public CustomerClass classID(StringValue classID) {
    this.classID = classID;
    return this;
  }

   /**
   * Get classID
   * @return classID
  **/
  @ApiModelProperty(value = "")
  public StringValue getClassID() {
    return classID;
  }

  public void setClassID(StringValue classID) {
    this.classID = classID;
  }

  public CustomerClass coGSAccount(StringValue coGSAccount) {
    this.coGSAccount = coGSAccount;
    return this;
  }

   /**
   * Get coGSAccount
   * @return coGSAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getCoGSAccount() {
    return coGSAccount;
  }

  public void setCoGSAccount(StringValue coGSAccount) {
    this.coGSAccount = coGSAccount;
  }

  public CustomerClass coGSSubaccount(StringValue coGSSubaccount) {
    this.coGSSubaccount = coGSSubaccount;
    return this;
  }

   /**
   * Get coGSSubaccount
   * @return coGSSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getCoGSSubaccount() {
    return coGSSubaccount;
  }

  public void setCoGSSubaccount(StringValue coGSSubaccount) {
    this.coGSSubaccount = coGSSubaccount;
  }

  public CustomerClass country(StringValue country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public StringValue getCountry() {
    return country;
  }

  public void setCountry(StringValue country) {
    this.country = country;
  }

  public CustomerClass createdDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public CustomerClass creditDaysPastDue(ShortValue creditDaysPastDue) {
    this.creditDaysPastDue = creditDaysPastDue;
    return this;
  }

   /**
   * Get creditDaysPastDue
   * @return creditDaysPastDue
  **/
  @ApiModelProperty(value = "")
  public ShortValue getCreditDaysPastDue() {
    return creditDaysPastDue;
  }

  public void setCreditDaysPastDue(ShortValue creditDaysPastDue) {
    this.creditDaysPastDue = creditDaysPastDue;
  }

  public CustomerClass creditLimit(DecimalValue creditLimit) {
    this.creditLimit = creditLimit;
    return this;
  }

   /**
   * Get creditLimit
   * @return creditLimit
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getCreditLimit() {
    return creditLimit;
  }

  public void setCreditLimit(DecimalValue creditLimit) {
    this.creditLimit = creditLimit;
  }

  public CustomerClass creditVerification(StringValue creditVerification) {
    this.creditVerification = creditVerification;
    return this;
  }

   /**
   * Get creditVerification
   * @return creditVerification
  **/
  @ApiModelProperty(value = "")
  public StringValue getCreditVerification() {
    return creditVerification;
  }

  public void setCreditVerification(StringValue creditVerification) {
    this.creditVerification = creditVerification;
  }

  public CustomerClass currencyID(StringValue currencyID) {
    this.currencyID = currencyID;
    return this;
  }

   /**
   * Get currencyID
   * @return currencyID
  **/
  @ApiModelProperty(value = "")
  public StringValue getCurrencyID() {
    return currencyID;
  }

  public void setCurrencyID(StringValue currencyID) {
    this.currencyID = currencyID;
  }

  public CustomerClass currencyRateType(StringValue currencyRateType) {
    this.currencyRateType = currencyRateType;
    return this;
  }

   /**
   * Get currencyRateType
   * @return currencyRateType
  **/
  @ApiModelProperty(value = "")
  public StringValue getCurrencyRateType() {
    return currencyRateType;
  }

  public void setCurrencyRateType(StringValue currencyRateType) {
    this.currencyRateType = currencyRateType;
  }

  public CustomerClass defaultLocationIDfromBranch(BooleanValue defaultLocationIDfromBranch) {
    this.defaultLocationIDfromBranch = defaultLocationIDfromBranch;
    return this;
  }

   /**
   * Get defaultLocationIDfromBranch
   * @return defaultLocationIDfromBranch
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getDefaultLocationIDfromBranch() {
    return defaultLocationIDfromBranch;
  }

  public void setDefaultLocationIDfromBranch(BooleanValue defaultLocationIDfromBranch) {
    this.defaultLocationIDfromBranch = defaultLocationIDfromBranch;
  }

  public CustomerClass defaultRestrictionGroup(StringValue defaultRestrictionGroup) {
    this.defaultRestrictionGroup = defaultRestrictionGroup;
    return this;
  }

   /**
   * Get defaultRestrictionGroup
   * @return defaultRestrictionGroup
  **/
  @ApiModelProperty(value = "")
  public StringValue getDefaultRestrictionGroup() {
    return defaultRestrictionGroup;
  }

  public void setDefaultRestrictionGroup(StringValue defaultRestrictionGroup) {
    this.defaultRestrictionGroup = defaultRestrictionGroup;
  }

  public CustomerClass description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public CustomerClass discountAccount(StringValue discountAccount) {
    this.discountAccount = discountAccount;
    return this;
  }

   /**
   * Get discountAccount
   * @return discountAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getDiscountAccount() {
    return discountAccount;
  }

  public void setDiscountAccount(StringValue discountAccount) {
    this.discountAccount = discountAccount;
  }

  public CustomerClass discountSubaccount(StringValue discountSubaccount) {
    this.discountSubaccount = discountSubaccount;
    return this;
  }

   /**
   * Get discountSubaccount
   * @return discountSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getDiscountSubaccount() {
    return discountSubaccount;
  }

  public void setDiscountSubaccount(StringValue discountSubaccount) {
    this.discountSubaccount = discountSubaccount;
  }

  public CustomerClass enableCurrencyOverride(BooleanValue enableCurrencyOverride) {
    this.enableCurrencyOverride = enableCurrencyOverride;
    return this;
  }

   /**
   * Get enableCurrencyOverride
   * @return enableCurrencyOverride
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getEnableCurrencyOverride() {
    return enableCurrencyOverride;
  }

  public void setEnableCurrencyOverride(BooleanValue enableCurrencyOverride) {
    this.enableCurrencyOverride = enableCurrencyOverride;
  }

  public CustomerClass enableRateOverride(BooleanValue enableRateOverride) {
    this.enableRateOverride = enableRateOverride;
    return this;
  }

   /**
   * Get enableRateOverride
   * @return enableRateOverride
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getEnableRateOverride() {
    return enableRateOverride;
  }

  public void setEnableRateOverride(BooleanValue enableRateOverride) {
    this.enableRateOverride = enableRateOverride;
  }

  public CustomerClass enableWriteOffs(BooleanValue enableWriteOffs) {
    this.enableWriteOffs = enableWriteOffs;
    return this;
  }

   /**
   * Get enableWriteOffs
   * @return enableWriteOffs
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getEnableWriteOffs() {
    return enableWriteOffs;
  }

  public void setEnableWriteOffs(BooleanValue enableWriteOffs) {
    this.enableWriteOffs = enableWriteOffs;
  }

  public CustomerClass entityUsageType(StringValue entityUsageType) {
    this.entityUsageType = entityUsageType;
    return this;
  }

   /**
   * Get entityUsageType
   * @return entityUsageType
  **/
  @ApiModelProperty(value = "")
  public StringValue getEntityUsageType() {
    return entityUsageType;
  }

  public void setEntityUsageType(StringValue entityUsageType) {
    this.entityUsageType = entityUsageType;
  }

  public CustomerClass freightAccount(StringValue freightAccount) {
    this.freightAccount = freightAccount;
    return this;
  }

   /**
   * Get freightAccount
   * @return freightAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getFreightAccount() {
    return freightAccount;
  }

  public void setFreightAccount(StringValue freightAccount) {
    this.freightAccount = freightAccount;
  }

  public CustomerClass freightSubaccount(StringValue freightSubaccount) {
    this.freightSubaccount = freightSubaccount;
    return this;
  }

   /**
   * Get freightSubaccount
   * @return freightSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getFreightSubaccount() {
    return freightSubaccount;
  }

  public void setFreightSubaccount(StringValue freightSubaccount) {
    this.freightSubaccount = freightSubaccount;
  }

  public CustomerClass groupDocumentDiscountLimit(DecimalValue groupDocumentDiscountLimit) {
    this.groupDocumentDiscountLimit = groupDocumentDiscountLimit;
    return this;
  }

   /**
   * Get groupDocumentDiscountLimit
   * @return groupDocumentDiscountLimit
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getGroupDocumentDiscountLimit() {
    return groupDocumentDiscountLimit;
  }

  public void setGroupDocumentDiscountLimit(DecimalValue groupDocumentDiscountLimit) {
    this.groupDocumentDiscountLimit = groupDocumentDiscountLimit;
  }

  public CustomerClass lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public CustomerClass miscAccount(StringValue miscAccount) {
    this.miscAccount = miscAccount;
    return this;
  }

   /**
   * Get miscAccount
   * @return miscAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getMiscAccount() {
    return miscAccount;
  }

  public void setMiscAccount(StringValue miscAccount) {
    this.miscAccount = miscAccount;
  }

  public CustomerClass miscSubaccount(StringValue miscSubaccount) {
    this.miscSubaccount = miscSubaccount;
    return this;
  }

   /**
   * Get miscSubaccount
   * @return miscSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getMiscSubaccount() {
    return miscSubaccount;
  }

  public void setMiscSubaccount(StringValue miscSubaccount) {
    this.miscSubaccount = miscSubaccount;
  }

  public CustomerClass multiCurrencyStatements(BooleanValue multiCurrencyStatements) {
    this.multiCurrencyStatements = multiCurrencyStatements;
    return this;
  }

   /**
   * Get multiCurrencyStatements
   * @return multiCurrencyStatements
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getMultiCurrencyStatements() {
    return multiCurrencyStatements;
  }

  public void setMultiCurrencyStatements(BooleanValue multiCurrencyStatements) {
    this.multiCurrencyStatements = multiCurrencyStatements;
  }

  public CustomerClass overdueChargeID(StringValue overdueChargeID) {
    this.overdueChargeID = overdueChargeID;
    return this;
  }

   /**
   * Get overdueChargeID
   * @return overdueChargeID
  **/
  @ApiModelProperty(value = "")
  public StringValue getOverdueChargeID() {
    return overdueChargeID;
  }

  public void setOverdueChargeID(StringValue overdueChargeID) {
    this.overdueChargeID = overdueChargeID;
  }

  public CustomerClass overLimitAmount(DecimalValue overLimitAmount) {
    this.overLimitAmount = overLimitAmount;
    return this;
  }

   /**
   * Get overLimitAmount
   * @return overLimitAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getOverLimitAmount() {
    return overLimitAmount;
  }

  public void setOverLimitAmount(DecimalValue overLimitAmount) {
    this.overLimitAmount = overLimitAmount;
  }

  public CustomerClass paymentMethod(StringValue paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  @ApiModelProperty(value = "")
  public StringValue getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(StringValue paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public CustomerClass prepaymentAccount(StringValue prepaymentAccount) {
    this.prepaymentAccount = prepaymentAccount;
    return this;
  }

   /**
   * Get prepaymentAccount
   * @return prepaymentAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getPrepaymentAccount() {
    return prepaymentAccount;
  }

  public void setPrepaymentAccount(StringValue prepaymentAccount) {
    this.prepaymentAccount = prepaymentAccount;
  }

  public CustomerClass prepaymentSubaccount(StringValue prepaymentSubaccount) {
    this.prepaymentSubaccount = prepaymentSubaccount;
    return this;
  }

   /**
   * Get prepaymentSubaccount
   * @return prepaymentSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getPrepaymentSubaccount() {
    return prepaymentSubaccount;
  }

  public void setPrepaymentSubaccount(StringValue prepaymentSubaccount) {
    this.prepaymentSubaccount = prepaymentSubaccount;
  }

  public CustomerClass printDunningLetters(BooleanValue printDunningLetters) {
    this.printDunningLetters = printDunningLetters;
    return this;
  }

   /**
   * Get printDunningLetters
   * @return printDunningLetters
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getPrintDunningLetters() {
    return printDunningLetters;
  }

  public void setPrintDunningLetters(BooleanValue printDunningLetters) {
    this.printDunningLetters = printDunningLetters;
  }

  public CustomerClass printInvoices(BooleanValue printInvoices) {
    this.printInvoices = printInvoices;
    return this;
  }

   /**
   * Get printInvoices
   * @return printInvoices
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getPrintInvoices() {
    return printInvoices;
  }

  public void setPrintInvoices(BooleanValue printInvoices) {
    this.printInvoices = printInvoices;
  }

  public CustomerClass printStatements(BooleanValue printStatements) {
    this.printStatements = printStatements;
    return this;
  }

   /**
   * Get printStatements
   * @return printStatements
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getPrintStatements() {
    return printStatements;
  }

  public void setPrintStatements(BooleanValue printStatements) {
    this.printStatements = printStatements;
  }

  public CustomerClass requireEntityUsageType(BooleanValue requireEntityUsageType) {
    this.requireEntityUsageType = requireEntityUsageType;
    return this;
  }

   /**
   * Get requireEntityUsageType
   * @return requireEntityUsageType
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getRequireEntityUsageType() {
    return requireEntityUsageType;
  }

  public void setRequireEntityUsageType(BooleanValue requireEntityUsageType) {
    this.requireEntityUsageType = requireEntityUsageType;
  }

  public CustomerClass requireTaxZone(BooleanValue requireTaxZone) {
    this.requireTaxZone = requireTaxZone;
    return this;
  }

   /**
   * Get requireTaxZone
   * @return requireTaxZone
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getRequireTaxZone() {
    return requireTaxZone;
  }

  public void setRequireTaxZone(BooleanValue requireTaxZone) {
    this.requireTaxZone = requireTaxZone;
  }

  public CustomerClass salesAccount(StringValue salesAccount) {
    this.salesAccount = salesAccount;
    return this;
  }

   /**
   * Get salesAccount
   * @return salesAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getSalesAccount() {
    return salesAccount;
  }

  public void setSalesAccount(StringValue salesAccount) {
    this.salesAccount = salesAccount;
  }

  public CustomerClass salespersonID(StringValue salespersonID) {
    this.salespersonID = salespersonID;
    return this;
  }

   /**
   * Get salespersonID
   * @return salespersonID
  **/
  @ApiModelProperty(value = "")
  public StringValue getSalespersonID() {
    return salespersonID;
  }

  public void setSalespersonID(StringValue salespersonID) {
    this.salespersonID = salespersonID;
  }

  public CustomerClass salesSubaccount(StringValue salesSubaccount) {
    this.salesSubaccount = salesSubaccount;
    return this;
  }

   /**
   * Get salesSubaccount
   * @return salesSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getSalesSubaccount() {
    return salesSubaccount;
  }

  public void setSalesSubaccount(StringValue salesSubaccount) {
    this.salesSubaccount = salesSubaccount;
  }

  public CustomerClass sendDunningLettersbyEmail(BooleanValue sendDunningLettersbyEmail) {
    this.sendDunningLettersbyEmail = sendDunningLettersbyEmail;
    return this;
  }

   /**
   * Get sendDunningLettersbyEmail
   * @return sendDunningLettersbyEmail
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getSendDunningLettersbyEmail() {
    return sendDunningLettersbyEmail;
  }

  public void setSendDunningLettersbyEmail(BooleanValue sendDunningLettersbyEmail) {
    this.sendDunningLettersbyEmail = sendDunningLettersbyEmail;
  }

  public CustomerClass sendInvoicesbyEmail(BooleanValue sendInvoicesbyEmail) {
    this.sendInvoicesbyEmail = sendInvoicesbyEmail;
    return this;
  }

   /**
   * Get sendInvoicesbyEmail
   * @return sendInvoicesbyEmail
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getSendInvoicesbyEmail() {
    return sendInvoicesbyEmail;
  }

  public void setSendInvoicesbyEmail(BooleanValue sendInvoicesbyEmail) {
    this.sendInvoicesbyEmail = sendInvoicesbyEmail;
  }

  public CustomerClass sendStatementsByEmail(BooleanValue sendStatementsByEmail) {
    this.sendStatementsByEmail = sendStatementsByEmail;
    return this;
  }

   /**
   * Get sendStatementsByEmail
   * @return sendStatementsByEmail
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getSendStatementsByEmail() {
    return sendStatementsByEmail;
  }

  public void setSendStatementsByEmail(BooleanValue sendStatementsByEmail) {
    this.sendStatementsByEmail = sendStatementsByEmail;
  }

  public CustomerClass shippingRule(StringValue shippingRule) {
    this.shippingRule = shippingRule;
    return this;
  }

   /**
   * Get shippingRule
   * @return shippingRule
  **/
  @ApiModelProperty(value = "")
  public StringValue getShippingRule() {
    return shippingRule;
  }

  public void setShippingRule(StringValue shippingRule) {
    this.shippingRule = shippingRule;
  }

  public CustomerClass shippingTerms(StringValue shippingTerms) {
    this.shippingTerms = shippingTerms;
    return this;
  }

   /**
   * Get shippingTerms
   * @return shippingTerms
  **/
  @ApiModelProperty(value = "")
  public StringValue getShippingTerms() {
    return shippingTerms;
  }

  public void setShippingTerms(StringValue shippingTerms) {
    this.shippingTerms = shippingTerms;
  }

  public CustomerClass shipVia(StringValue shipVia) {
    this.shipVia = shipVia;
    return this;
  }

   /**
   * Get shipVia
   * @return shipVia
  **/
  @ApiModelProperty(value = "")
  public StringValue getShipVia() {
    return shipVia;
  }

  public void setShipVia(StringValue shipVia) {
    this.shipVia = shipVia;
  }

  public CustomerClass statementCycleID(StringValue statementCycleID) {
    this.statementCycleID = statementCycleID;
    return this;
  }

   /**
   * Get statementCycleID
   * @return statementCycleID
  **/
  @ApiModelProperty(value = "")
  public StringValue getStatementCycleID() {
    return statementCycleID;
  }

  public void setStatementCycleID(StringValue statementCycleID) {
    this.statementCycleID = statementCycleID;
  }

  public CustomerClass statementType(StringValue statementType) {
    this.statementType = statementType;
    return this;
  }

   /**
   * Get statementType
   * @return statementType
  **/
  @ApiModelProperty(value = "")
  public StringValue getStatementType() {
    return statementType;
  }

  public void setStatementType(StringValue statementType) {
    this.statementType = statementType;
  }

  public CustomerClass taxZoneID(StringValue taxZoneID) {
    this.taxZoneID = taxZoneID;
    return this;
  }

   /**
   * Get taxZoneID
   * @return taxZoneID
  **/
  @ApiModelProperty(value = "")
  public StringValue getTaxZoneID() {
    return taxZoneID;
  }

  public void setTaxZoneID(StringValue taxZoneID) {
    this.taxZoneID = taxZoneID;
  }

  public CustomerClass terms(StringValue terms) {
    this.terms = terms;
    return this;
  }

   /**
   * Get terms
   * @return terms
  **/
  @ApiModelProperty(value = "")
  public StringValue getTerms() {
    return terms;
  }

  public void setTerms(StringValue terms) {
    this.terms = terms;
  }

  public CustomerClass unrealizedGainAccount(StringValue unrealizedGainAccount) {
    this.unrealizedGainAccount = unrealizedGainAccount;
    return this;
  }

   /**
   * Get unrealizedGainAccount
   * @return unrealizedGainAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getUnrealizedGainAccount() {
    return unrealizedGainAccount;
  }

  public void setUnrealizedGainAccount(StringValue unrealizedGainAccount) {
    this.unrealizedGainAccount = unrealizedGainAccount;
  }

  public CustomerClass unrealizedGainSubaccount(StringValue unrealizedGainSubaccount) {
    this.unrealizedGainSubaccount = unrealizedGainSubaccount;
    return this;
  }

   /**
   * Get unrealizedGainSubaccount
   * @return unrealizedGainSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getUnrealizedGainSubaccount() {
    return unrealizedGainSubaccount;
  }

  public void setUnrealizedGainSubaccount(StringValue unrealizedGainSubaccount) {
    this.unrealizedGainSubaccount = unrealizedGainSubaccount;
  }

  public CustomerClass unrealizedLossAccount(StringValue unrealizedLossAccount) {
    this.unrealizedLossAccount = unrealizedLossAccount;
    return this;
  }

   /**
   * Get unrealizedLossAccount
   * @return unrealizedLossAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getUnrealizedLossAccount() {
    return unrealizedLossAccount;
  }

  public void setUnrealizedLossAccount(StringValue unrealizedLossAccount) {
    this.unrealizedLossAccount = unrealizedLossAccount;
  }

  public CustomerClass unrealizedLossSubaccount(StringValue unrealizedLossSubaccount) {
    this.unrealizedLossSubaccount = unrealizedLossSubaccount;
    return this;
  }

   /**
   * Get unrealizedLossSubaccount
   * @return unrealizedLossSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getUnrealizedLossSubaccount() {
    return unrealizedLossSubaccount;
  }

  public void setUnrealizedLossSubaccount(StringValue unrealizedLossSubaccount) {
    this.unrealizedLossSubaccount = unrealizedLossSubaccount;
  }

  public CustomerClass writeOffLimit(DecimalValue writeOffLimit) {
    this.writeOffLimit = writeOffLimit;
    return this;
  }

   /**
   * Get writeOffLimit
   * @return writeOffLimit
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getWriteOffLimit() {
    return writeOffLimit;
  }

  public void setWriteOffLimit(DecimalValue writeOffLimit) {
    this.writeOffLimit = writeOffLimit;
  }

}

