/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * DefaultTaskForGLAccount
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class DefaultTaskForGLAccount extends Entity {
  @SerializedName("Account")
  private StringValue account = null;

  @SerializedName("DefaultTask")
  private StringValue defaultTask = null;

  public DefaultTaskForGLAccount account(StringValue account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @ApiModelProperty(value = "")
  public StringValue getAccount() {
    return account;
  }

  public void setAccount(StringValue account) {
    this.account = account;
  }

  public DefaultTaskForGLAccount defaultTask(StringValue defaultTask) {
    this.defaultTask = defaultTask;
    return this;
  }

   /**
   * Get defaultTask
   * @return defaultTask
  **/
  @ApiModelProperty(value = "")
  public StringValue getDefaultTask() {
    return defaultTask;
  }

  public void setDefaultTask(StringValue defaultTask) {
    this.defaultTask = defaultTask;
  }

}

