/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Discount
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class Discount extends Entity {
  @SerializedName("Active")
  private BooleanValue active = null;

  @SerializedName("BreakBy")
  private StringValue breakBy = null;

  @SerializedName("CreatedDateTime")
  private DateTimeValue createdDateTime = null;

  @SerializedName("CustomerPriceClasses")
  private List<DiscountCustomerPriceClassesDetail> customerPriceClasses = null;

  @SerializedName("Customers")
  private List<DiscountCustomerDetail> customers = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("DiscountBreakpoints")
  private List<DiscountBreakpointDetail> discountBreakpoints = null;

  @SerializedName("DiscountBy")
  private StringValue discountBy = null;

  @SerializedName("DiscountCode")
  private StringValue discountCode = null;

  @SerializedName("EffectiveDate")
  private DateTimeValue effectiveDate = null;

  @SerializedName("ExpirationDate")
  private DateTimeValue expirationDate = null;

  @SerializedName("ItemPriceClasses")
  private List<DiscountItemPriceClassesDetail> itemPriceClasses = null;

  @SerializedName("Items")
  private List<DiscountItemDetail> items = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("Promotional")
  private BooleanValue promotional = null;

  @SerializedName("ProrateDiscount")
  private BooleanValue prorateDiscount = null;

  @SerializedName("Sequence")
  private StringValue sequence = null;

  @SerializedName("ShowFreeItem")
  private BooleanValue showFreeItem = null;

  @SerializedName("Warehouses")
  private List<DiscountWarehouseDetail> warehouses = null;

  public Discount active(BooleanValue active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getActive() {
    return active;
  }

  public void setActive(BooleanValue active) {
    this.active = active;
  }

  public Discount breakBy(StringValue breakBy) {
    this.breakBy = breakBy;
    return this;
  }

   /**
   * Get breakBy
   * @return breakBy
  **/
  @ApiModelProperty(value = "")
  public StringValue getBreakBy() {
    return breakBy;
  }

  public void setBreakBy(StringValue breakBy) {
    this.breakBy = breakBy;
  }

  public Discount createdDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public Discount customerPriceClasses(List<DiscountCustomerPriceClassesDetail> customerPriceClasses) {
    this.customerPriceClasses = customerPriceClasses;
    return this;
  }

  public Discount addCustomerPriceClassesItem(DiscountCustomerPriceClassesDetail customerPriceClassesItem) {
    if (this.customerPriceClasses == null) {
      this.customerPriceClasses = new ArrayList<>();
    }
    this.customerPriceClasses.add(customerPriceClassesItem);
    return this;
  }

   /**
   * Get customerPriceClasses
   * @return customerPriceClasses
  **/
  @ApiModelProperty(value = "")
  public List<DiscountCustomerPriceClassesDetail> getCustomerPriceClasses() {
    return customerPriceClasses;
  }

  public void setCustomerPriceClasses(List<DiscountCustomerPriceClassesDetail> customerPriceClasses) {
    this.customerPriceClasses = customerPriceClasses;
  }

  public Discount customers(List<DiscountCustomerDetail> customers) {
    this.customers = customers;
    return this;
  }

  public Discount addCustomersItem(DiscountCustomerDetail customersItem) {
    if (this.customers == null) {
      this.customers = new ArrayList<>();
    }
    this.customers.add(customersItem);
    return this;
  }

   /**
   * Get customers
   * @return customers
  **/
  @ApiModelProperty(value = "")
  public List<DiscountCustomerDetail> getCustomers() {
    return customers;
  }

  public void setCustomers(List<DiscountCustomerDetail> customers) {
    this.customers = customers;
  }

  public Discount description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public Discount discountBreakpoints(List<DiscountBreakpointDetail> discountBreakpoints) {
    this.discountBreakpoints = discountBreakpoints;
    return this;
  }

  public Discount addDiscountBreakpointsItem(DiscountBreakpointDetail discountBreakpointsItem) {
    if (this.discountBreakpoints == null) {
      this.discountBreakpoints = new ArrayList<>();
    }
    this.discountBreakpoints.add(discountBreakpointsItem);
    return this;
  }

   /**
   * Get discountBreakpoints
   * @return discountBreakpoints
  **/
  @ApiModelProperty(value = "")
  public List<DiscountBreakpointDetail> getDiscountBreakpoints() {
    return discountBreakpoints;
  }

  public void setDiscountBreakpoints(List<DiscountBreakpointDetail> discountBreakpoints) {
    this.discountBreakpoints = discountBreakpoints;
  }

  public Discount discountBy(StringValue discountBy) {
    this.discountBy = discountBy;
    return this;
  }

   /**
   * Get discountBy
   * @return discountBy
  **/
  @ApiModelProperty(value = "")
  public StringValue getDiscountBy() {
    return discountBy;
  }

  public void setDiscountBy(StringValue discountBy) {
    this.discountBy = discountBy;
  }

  public Discount discountCode(StringValue discountCode) {
    this.discountCode = discountCode;
    return this;
  }

   /**
   * Get discountCode
   * @return discountCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getDiscountCode() {
    return discountCode;
  }

  public void setDiscountCode(StringValue discountCode) {
    this.discountCode = discountCode;
  }

  public Discount effectiveDate(DateTimeValue effectiveDate) {
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Get effectiveDate
   * @return effectiveDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getEffectiveDate() {
    return effectiveDate;
  }

  public void setEffectiveDate(DateTimeValue effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

  public Discount expirationDate(DateTimeValue expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(DateTimeValue expirationDate) {
    this.expirationDate = expirationDate;
  }

  public Discount itemPriceClasses(List<DiscountItemPriceClassesDetail> itemPriceClasses) {
    this.itemPriceClasses = itemPriceClasses;
    return this;
  }

  public Discount addItemPriceClassesItem(DiscountItemPriceClassesDetail itemPriceClassesItem) {
    if (this.itemPriceClasses == null) {
      this.itemPriceClasses = new ArrayList<>();
    }
    this.itemPriceClasses.add(itemPriceClassesItem);
    return this;
  }

   /**
   * Get itemPriceClasses
   * @return itemPriceClasses
  **/
  @ApiModelProperty(value = "")
  public List<DiscountItemPriceClassesDetail> getItemPriceClasses() {
    return itemPriceClasses;
  }

  public void setItemPriceClasses(List<DiscountItemPriceClassesDetail> itemPriceClasses) {
    this.itemPriceClasses = itemPriceClasses;
  }

  public Discount items(List<DiscountItemDetail> items) {
    this.items = items;
    return this;
  }

  public Discount addItemsItem(DiscountItemDetail itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(value = "")
  public List<DiscountItemDetail> getItems() {
    return items;
  }

  public void setItems(List<DiscountItemDetail> items) {
    this.items = items;
  }

  public Discount lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public Discount promotional(BooleanValue promotional) {
    this.promotional = promotional;
    return this;
  }

   /**
   * Get promotional
   * @return promotional
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getPromotional() {
    return promotional;
  }

  public void setPromotional(BooleanValue promotional) {
    this.promotional = promotional;
  }

  public Discount prorateDiscount(BooleanValue prorateDiscount) {
    this.prorateDiscount = prorateDiscount;
    return this;
  }

   /**
   * Get prorateDiscount
   * @return prorateDiscount
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getProrateDiscount() {
    return prorateDiscount;
  }

  public void setProrateDiscount(BooleanValue prorateDiscount) {
    this.prorateDiscount = prorateDiscount;
  }

  public Discount sequence(StringValue sequence) {
    this.sequence = sequence;
    return this;
  }

   /**
   * Get sequence
   * @return sequence
  **/
  @ApiModelProperty(value = "")
  public StringValue getSequence() {
    return sequence;
  }

  public void setSequence(StringValue sequence) {
    this.sequence = sequence;
  }

  public Discount showFreeItem(BooleanValue showFreeItem) {
    this.showFreeItem = showFreeItem;
    return this;
  }

   /**
   * Get showFreeItem
   * @return showFreeItem
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getShowFreeItem() {
    return showFreeItem;
  }

  public void setShowFreeItem(BooleanValue showFreeItem) {
    this.showFreeItem = showFreeItem;
  }

  public Discount warehouses(List<DiscountWarehouseDetail> warehouses) {
    this.warehouses = warehouses;
    return this;
  }

  public Discount addWarehousesItem(DiscountWarehouseDetail warehousesItem) {
    if (this.warehouses == null) {
      this.warehouses = new ArrayList<>();
    }
    this.warehouses.add(warehousesItem);
    return this;
  }

   /**
   * Get warehouses
   * @return warehouses
  **/
  @ApiModelProperty(value = "")
  public List<DiscountWarehouseDetail> getWarehouses() {
    return warehouses;
  }

  public void setWarehouses(List<DiscountWarehouseDetail> warehouses) {
    this.warehouses = warehouses;
  }

}

