/*
 * Default/22.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import model.CustomField;
import model.EarningIncreasingApplWageDetail;
import model.Entity;
import model.FileLink;
import model.StringValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * EarningIncreasingApplWage
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-17T14:29:48.617Z")
public class EarningIncreasingApplWage extends Entity {
  @SerializedName("EarningIncreasingApplWageDetails")
  private List<EarningIncreasingApplWageDetail> earningIncreasingApplWageDetails = null;

  @SerializedName("InclusionType")
  private StringValue inclusionType = null;

  public EarningIncreasingApplWage earningIncreasingApplWageDetails(List<EarningIncreasingApplWageDetail> earningIncreasingApplWageDetails) {
    this.earningIncreasingApplWageDetails = earningIncreasingApplWageDetails;
    return this;
  }

  public EarningIncreasingApplWage addEarningIncreasingApplWageDetailsItem(EarningIncreasingApplWageDetail earningIncreasingApplWageDetailsItem) {
    if (this.earningIncreasingApplWageDetails == null) {
      this.earningIncreasingApplWageDetails = new ArrayList<EarningIncreasingApplWageDetail>();
    }
    this.earningIncreasingApplWageDetails.add(earningIncreasingApplWageDetailsItem);
    return this;
  }

   /**
   * Get earningIncreasingApplWageDetails
   * @return earningIncreasingApplWageDetails
  **/
  @ApiModelProperty(value = "")
  public List<EarningIncreasingApplWageDetail> getEarningIncreasingApplWageDetails() {
    return earningIncreasingApplWageDetails;
  }

  public void setEarningIncreasingApplWageDetails(List<EarningIncreasingApplWageDetail> earningIncreasingApplWageDetails) {
    this.earningIncreasingApplWageDetails = earningIncreasingApplWageDetails;
  }

  public EarningIncreasingApplWage inclusionType(StringValue inclusionType) {
    this.inclusionType = inclusionType;
    return this;
  }

   /**
   * Get inclusionType
   * @return inclusionType
  **/
  @ApiModelProperty(value = "")
  public StringValue getInclusionType() {
    return inclusionType;
  }

  public void setInclusionType(StringValue inclusionType) {
    this.inclusionType = inclusionType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EarningIncreasingApplWage earningIncreasingApplWage = (EarningIncreasingApplWage) o;
    return Objects.equals(this.earningIncreasingApplWageDetails, earningIncreasingApplWage.earningIncreasingApplWageDetails) &&
        Objects.equals(this.inclusionType, earningIncreasingApplWage.inclusionType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(earningIncreasingApplWageDetails, inclusionType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EarningIncreasingApplWage {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    earningIncreasingApplWageDetails: ").append(toIndentedString(earningIncreasingApplWageDetails)).append("\n");
    sb.append("    inclusionType: ").append(toIndentedString(inclusionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

