/*
 * Default/22.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import model.CustomField;
import model.DateTimeValue;
import model.Entity;
import model.FileLink;
import model.StringValue;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * EmploymentDates
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-17T14:29:48.617Z")
public class EmploymentDates extends Entity {
  @SerializedName("HireDate")
  private DateTimeValue hireDate = null;

  @SerializedName("TerminationDate")
  private DateTimeValue terminationDate = null;

  public EmploymentDates hireDate(DateTimeValue hireDate) {
    this.hireDate = hireDate;
    return this;
  }

   /**
   * Get hireDate
   * @return hireDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getHireDate() {
    return hireDate;
  }

  public void setHireDate(DateTimeValue hireDate) {
    this.hireDate = hireDate;
  }

  public EmploymentDates terminationDate(DateTimeValue terminationDate) {
    this.terminationDate = terminationDate;
    return this;
  }

   /**
   * Get terminationDate
   * @return terminationDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getTerminationDate() {
    return terminationDate;
  }

  public void setTerminationDate(DateTimeValue terminationDate) {
    this.terminationDate = terminationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmploymentDates employmentDates = (EmploymentDates) o;
    return Objects.equals(this.hireDate, employmentDates.hireDate) &&
        Objects.equals(this.terminationDate, employmentDates.terminationDate) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hireDate, terminationDate, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmploymentDates {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    hireDate: ").append(toIndentedString(hireDate)).append("\n");
    sb.append("    terminationDate: ").append(toIndentedString(terminationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

