/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * EmployeeSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class EmployeeSettings extends Entity {
  @SerializedName("BranchID")
  private StringValue branchID = null;

  @SerializedName("Calendar")
  private StringValue calendar = null;

  @SerializedName("CurrencyID")
  private StringValue currencyID = null;

  @SerializedName("CurrencyRateTypeID")
  private StringValue currencyRateTypeID = null;

  @SerializedName("DepartmentID")
  private StringValue departmentID = null;

  @SerializedName("EmployeeClass")
  private StringValue employeeClass = null;

  @SerializedName("EmployeeRefNbr")
  private StringValue employeeRefNbr = null;

  @SerializedName("EnableCurrencyOverride")
  private BooleanValue enableCurrencyOverride = null;

  @SerializedName("EnableRateOverride")
  private BooleanValue enableRateOverride = null;

  @SerializedName("LaborItem")
  private StringValue laborItem = null;

  @SerializedName("RegularHoursValidation")
  private StringValue regularHoursValidation = null;

  @SerializedName("ReportsTo")
  private StringValue reportsTo = null;

  @SerializedName("RouteEmails")
  private BooleanValue routeEmails = null;

  @SerializedName("Salesperson")
  private StringValue salesperson = null;

  @SerializedName("TimeCardIsRequired")
  private BooleanValue timeCardIsRequired = null;

  @SerializedName("UnionLocalID")
  private StringValue unionLocalID = null;

  public EmployeeSettings branchID(StringValue branchID) {
    this.branchID = branchID;
    return this;
  }

   /**
   * Get branchID
   * @return branchID
  **/
  @ApiModelProperty(value = "")
  public StringValue getBranchID() {
    return branchID;
  }

  public void setBranchID(StringValue branchID) {
    this.branchID = branchID;
  }

  public EmployeeSettings calendar(StringValue calendar) {
    this.calendar = calendar;
    return this;
  }

   /**
   * Get calendar
   * @return calendar
  **/
  @ApiModelProperty(value = "")
  public StringValue getCalendar() {
    return calendar;
  }

  public void setCalendar(StringValue calendar) {
    this.calendar = calendar;
  }

  public EmployeeSettings currencyID(StringValue currencyID) {
    this.currencyID = currencyID;
    return this;
  }

   /**
   * Get currencyID
   * @return currencyID
  **/
  @ApiModelProperty(value = "")
  public StringValue getCurrencyID() {
    return currencyID;
  }

  public void setCurrencyID(StringValue currencyID) {
    this.currencyID = currencyID;
  }

  public EmployeeSettings currencyRateTypeID(StringValue currencyRateTypeID) {
    this.currencyRateTypeID = currencyRateTypeID;
    return this;
  }

   /**
   * Get currencyRateTypeID
   * @return currencyRateTypeID
  **/
  @ApiModelProperty(value = "")
  public StringValue getCurrencyRateTypeID() {
    return currencyRateTypeID;
  }

  public void setCurrencyRateTypeID(StringValue currencyRateTypeID) {
    this.currencyRateTypeID = currencyRateTypeID;
  }

  public EmployeeSettings departmentID(StringValue departmentID) {
    this.departmentID = departmentID;
    return this;
  }

   /**
   * Get departmentID
   * @return departmentID
  **/
  @ApiModelProperty(value = "")
  public StringValue getDepartmentID() {
    return departmentID;
  }

  public void setDepartmentID(StringValue departmentID) {
    this.departmentID = departmentID;
  }

  public EmployeeSettings employeeClass(StringValue employeeClass) {
    this.employeeClass = employeeClass;
    return this;
  }

   /**
   * Get employeeClass
   * @return employeeClass
  **/
  @ApiModelProperty(value = "")
  public StringValue getEmployeeClass() {
    return employeeClass;
  }

  public void setEmployeeClass(StringValue employeeClass) {
    this.employeeClass = employeeClass;
  }

  public EmployeeSettings employeeRefNbr(StringValue employeeRefNbr) {
    this.employeeRefNbr = employeeRefNbr;
    return this;
  }

   /**
   * Get employeeRefNbr
   * @return employeeRefNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getEmployeeRefNbr() {
    return employeeRefNbr;
  }

  public void setEmployeeRefNbr(StringValue employeeRefNbr) {
    this.employeeRefNbr = employeeRefNbr;
  }

  public EmployeeSettings enableCurrencyOverride(BooleanValue enableCurrencyOverride) {
    this.enableCurrencyOverride = enableCurrencyOverride;
    return this;
  }

   /**
   * Get enableCurrencyOverride
   * @return enableCurrencyOverride
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getEnableCurrencyOverride() {
    return enableCurrencyOverride;
  }

  public void setEnableCurrencyOverride(BooleanValue enableCurrencyOverride) {
    this.enableCurrencyOverride = enableCurrencyOverride;
  }

  public EmployeeSettings enableRateOverride(BooleanValue enableRateOverride) {
    this.enableRateOverride = enableRateOverride;
    return this;
  }

   /**
   * Get enableRateOverride
   * @return enableRateOverride
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getEnableRateOverride() {
    return enableRateOverride;
  }

  public void setEnableRateOverride(BooleanValue enableRateOverride) {
    this.enableRateOverride = enableRateOverride;
  }

  public EmployeeSettings laborItem(StringValue laborItem) {
    this.laborItem = laborItem;
    return this;
  }

   /**
   * Get laborItem
   * @return laborItem
  **/
  @ApiModelProperty(value = "")
  public StringValue getLaborItem() {
    return laborItem;
  }

  public void setLaborItem(StringValue laborItem) {
    this.laborItem = laborItem;
  }

  public EmployeeSettings regularHoursValidation(StringValue regularHoursValidation) {
    this.regularHoursValidation = regularHoursValidation;
    return this;
  }

   /**
   * Get regularHoursValidation
   * @return regularHoursValidation
  **/
  @ApiModelProperty(value = "")
  public StringValue getRegularHoursValidation() {
    return regularHoursValidation;
  }

  public void setRegularHoursValidation(StringValue regularHoursValidation) {
    this.regularHoursValidation = regularHoursValidation;
  }

  public EmployeeSettings reportsTo(StringValue reportsTo) {
    this.reportsTo = reportsTo;
    return this;
  }

   /**
   * Get reportsTo
   * @return reportsTo
  **/
  @ApiModelProperty(value = "")
  public StringValue getReportsTo() {
    return reportsTo;
  }

  public void setReportsTo(StringValue reportsTo) {
    this.reportsTo = reportsTo;
  }

  public EmployeeSettings routeEmails(BooleanValue routeEmails) {
    this.routeEmails = routeEmails;
    return this;
  }

   /**
   * Get routeEmails
   * @return routeEmails
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getRouteEmails() {
    return routeEmails;
  }

  public void setRouteEmails(BooleanValue routeEmails) {
    this.routeEmails = routeEmails;
  }

  public EmployeeSettings salesperson(StringValue salesperson) {
    this.salesperson = salesperson;
    return this;
  }

   /**
   * Get salesperson
   * @return salesperson
  **/
  @ApiModelProperty(value = "")
  public StringValue getSalesperson() {
    return salesperson;
  }

  public void setSalesperson(StringValue salesperson) {
    this.salesperson = salesperson;
  }

  public EmployeeSettings timeCardIsRequired(BooleanValue timeCardIsRequired) {
    this.timeCardIsRequired = timeCardIsRequired;
    return this;
  }

   /**
   * Get timeCardIsRequired
   * @return timeCardIsRequired
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getTimeCardIsRequired() {
    return timeCardIsRequired;
  }

  public void setTimeCardIsRequired(BooleanValue timeCardIsRequired) {
    this.timeCardIsRequired = timeCardIsRequired;
  }

  public EmployeeSettings unionLocalID(StringValue unionLocalID) {
    this.unionLocalID = unionLocalID;
    return this;
  }

   /**
   * Get unionLocalID
   * @return unionLocalID
  **/
  @ApiModelProperty(value = "")
  public StringValue getUnionLocalID() {
    return unionLocalID;
  }

  public void setUnionLocalID(StringValue unionLocalID) {
    this.unionLocalID = unionLocalID;
  }

}

