/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * EmploymentHistoryRecord
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class EmploymentHistoryRecord extends Entity {
  @SerializedName("Active")
  private BooleanValue active = null;

  @SerializedName("EndDate")
  private DateTimeValue endDate = null;

  @SerializedName("LineNbr")
  private IntValue lineNbr = null;

  @SerializedName("PositionID")
  private StringValue positionID = null;

  @SerializedName("RehireEligible")
  private BooleanValue rehireEligible = null;

  @SerializedName("StartDate")
  private DateTimeValue startDate = null;

  @SerializedName("StartReason")
  private StringValue startReason = null;

  @SerializedName("Terminated")
  private BooleanValue terminated = null;

  @SerializedName("TerminationReason")
  private StringValue terminationReason = null;

  public EmploymentHistoryRecord active(BooleanValue active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getActive() {
    return active;
  }

  public void setActive(BooleanValue active) {
    this.active = active;
  }

  public EmploymentHistoryRecord endDate(DateTimeValue endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getEndDate() {
    return endDate;
  }

  public void setEndDate(DateTimeValue endDate) {
    this.endDate = endDate;
  }

  public EmploymentHistoryRecord lineNbr(IntValue lineNbr) {
    this.lineNbr = lineNbr;
    return this;
  }

   /**
   * Get lineNbr
   * @return lineNbr
  **/
  @ApiModelProperty(value = "")
  public IntValue getLineNbr() {
    return lineNbr;
  }

  public void setLineNbr(IntValue lineNbr) {
    this.lineNbr = lineNbr;
  }

  public EmploymentHistoryRecord positionID(StringValue positionID) {
    this.positionID = positionID;
    return this;
  }

   /**
   * Get positionID
   * @return positionID
  **/
  @ApiModelProperty(value = "")
  public StringValue getPositionID() {
    return positionID;
  }

  public void setPositionID(StringValue positionID) {
    this.positionID = positionID;
  }

  public EmploymentHistoryRecord rehireEligible(BooleanValue rehireEligible) {
    this.rehireEligible = rehireEligible;
    return this;
  }

   /**
   * Get rehireEligible
   * @return rehireEligible
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getRehireEligible() {
    return rehireEligible;
  }

  public void setRehireEligible(BooleanValue rehireEligible) {
    this.rehireEligible = rehireEligible;
  }

  public EmploymentHistoryRecord startDate(DateTimeValue startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getStartDate() {
    return startDate;
  }

  public void setStartDate(DateTimeValue startDate) {
    this.startDate = startDate;
  }

  public EmploymentHistoryRecord startReason(StringValue startReason) {
    this.startReason = startReason;
    return this;
  }

   /**
   * Get startReason
   * @return startReason
  **/
  @ApiModelProperty(value = "")
  public StringValue getStartReason() {
    return startReason;
  }

  public void setStartReason(StringValue startReason) {
    this.startReason = startReason;
  }

  public EmploymentHistoryRecord terminated(BooleanValue terminated) {
    this.terminated = terminated;
    return this;
  }

   /**
   * Get terminated
   * @return terminated
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getTerminated() {
    return terminated;
  }

  public void setTerminated(BooleanValue terminated) {
    this.terminated = terminated;
  }

  public EmploymentHistoryRecord terminationReason(StringValue terminationReason) {
    this.terminationReason = terminationReason;
    return this;
  }

   /**
   * Get terminationReason
   * @return terminationReason
  **/
  @ApiModelProperty(value = "")
  public StringValue getTerminationReason() {
    return terminationReason;
  }

  public void setTerminationReason(StringValue terminationReason) {
    this.terminationReason = terminationReason;
  }

}

