/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * EventAttendee
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class EventAttendee extends Entity {
  @SerializedName("Comment")
  private StringValue comment = null;

  @SerializedName("Email")
  private StringValue email = null;

  @SerializedName("EventNoteID")
  private GuidValue eventNoteID = null;

  @SerializedName("InvitationStatus")
  private StringValue invitationStatus = null;

  @SerializedName("Key")
  private StringValue key = null;

  @SerializedName("Name")
  private StringValue name = null;

  @SerializedName("NameAttendeeName")
  private StringValue nameAttendeeName = null;

  @SerializedName("Type")
  private IntValue type = null;

  public EventAttendee comment(StringValue comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(value = "")
  public StringValue getComment() {
    return comment;
  }

  public void setComment(StringValue comment) {
    this.comment = comment;
  }

  public EventAttendee email(StringValue email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public StringValue getEmail() {
    return email;
  }

  public void setEmail(StringValue email) {
    this.email = email;
  }

  public EventAttendee eventNoteID(GuidValue eventNoteID) {
    this.eventNoteID = eventNoteID;
    return this;
  }

   /**
   * Get eventNoteID
   * @return eventNoteID
  **/
  @ApiModelProperty(value = "")
  public GuidValue getEventNoteID() {
    return eventNoteID;
  }

  public void setEventNoteID(GuidValue eventNoteID) {
    this.eventNoteID = eventNoteID;
  }

  public EventAttendee invitationStatus(StringValue invitationStatus) {
    this.invitationStatus = invitationStatus;
    return this;
  }

   /**
   * Get invitationStatus
   * @return invitationStatus
  **/
  @ApiModelProperty(value = "")
  public StringValue getInvitationStatus() {
    return invitationStatus;
  }

  public void setInvitationStatus(StringValue invitationStatus) {
    this.invitationStatus = invitationStatus;
  }

  public EventAttendee key(StringValue key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @ApiModelProperty(value = "")
  public StringValue getKey() {
    return key;
  }

  public void setKey(StringValue key) {
    this.key = key;
  }

  public EventAttendee name(StringValue name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public StringValue getName() {
    return name;
  }

  public void setName(StringValue name) {
    this.name = name;
  }

  public EventAttendee nameAttendeeName(StringValue nameAttendeeName) {
    this.nameAttendeeName = nameAttendeeName;
    return this;
  }

   /**
   * Get nameAttendeeName
   * @return nameAttendeeName
  **/
  @ApiModelProperty(value = "")
  public StringValue getNameAttendeeName() {
    return nameAttendeeName;
  }

  public void setNameAttendeeName(StringValue nameAttendeeName) {
    this.nameAttendeeName = nameAttendeeName;
  }

  public EventAttendee type(IntValue type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public IntValue getType() {
    return type;
  }

  public void setType(IntValue type) {
    this.type = type;
  }

}

