/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Event
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class Event extends Entity {
  @SerializedName("AllDay")
  private BooleanValue allDay = null;

  @SerializedName("Attendees")
  private List<EventAttendee> attendees = null;

  @SerializedName("Body")
  private StringValue body = null;

  @SerializedName("Category")
  private StringValue category = null;

  @SerializedName("EndDate")
  private DateTimeValue endDate = null;

  @SerializedName("EndTime")
  private DateTimeValue endTime = null;

  @SerializedName("Internal")
  private BooleanValue internal = null;

  @SerializedName("Location")
  private StringValue location = null;

  @SerializedName("NoteID")
  private GuidValue noteID = null;

  @SerializedName("Priority")
  private StringValue priority = null;

  @SerializedName("RelatedActivities")
  private List<ActivityDetail> relatedActivities = null;

  @SerializedName("Reminder")
  private ReminderDetail reminder = null;

  @SerializedName("ShowAs")
  private StringValue showAs = null;

  @SerializedName("StartDate")
  private DateTimeValue startDate = null;

  @SerializedName("Status")
  private StringValue status = null;

  @SerializedName("Summary")
  private StringValue summary = null;

  @SerializedName("TimeActivity")
  private EventTimeActivity timeActivity = null;

  @SerializedName("CreatedByID")
  private StringValue createdByID = null;

  @SerializedName("CreatedDateTime")
  private DateTimeValue createdDateTime = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("RelatedEntityType")
  private StringValue relatedEntityType = null;

  @SerializedName("RelatedEntityNoteID")
  private GuidValue relatedEntityNoteID = null;

  @SerializedName("RelatedEntityDescription")
  private StringValue relatedEntityDescription = null;

  public Event allDay(BooleanValue allDay) {
    this.allDay = allDay;
    return this;
  }

   /**
   * Get allDay
   * @return allDay
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getAllDay() {
    return allDay;
  }

  public void setAllDay(BooleanValue allDay) {
    this.allDay = allDay;
  }

  public Event attendees(List<EventAttendee> attendees) {
    this.attendees = attendees;
    return this;
  }

  public Event addAttendeesItem(EventAttendee attendeesItem) {
    if (this.attendees == null) {
      this.attendees = new ArrayList<>();
    }
    this.attendees.add(attendeesItem);
    return this;
  }

   /**
   * Get attendees
   * @return attendees
  **/
  @ApiModelProperty(value = "")
  public List<EventAttendee> getAttendees() {
    return attendees;
  }

  public void setAttendees(List<EventAttendee> attendees) {
    this.attendees = attendees;
  }

  public Event body(StringValue body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @ApiModelProperty(value = "")
  public StringValue getBody() {
    return body;
  }

  public void setBody(StringValue body) {
    this.body = body;
  }

  public Event category(StringValue category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(value = "")
  public StringValue getCategory() {
    return category;
  }

  public void setCategory(StringValue category) {
    this.category = category;
  }

  public Event endDate(DateTimeValue endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getEndDate() {
    return endDate;
  }

  public void setEndDate(DateTimeValue endDate) {
    this.endDate = endDate;
  }

  public Event endTime(DateTimeValue endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getEndTime() {
    return endTime;
  }

  public void setEndTime(DateTimeValue endTime) {
    this.endTime = endTime;
  }

  public Event internal(BooleanValue internal) {
    this.internal = internal;
    return this;
  }

   /**
   * Get internal
   * @return internal
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getInternal() {
    return internal;
  }

  public void setInternal(BooleanValue internal) {
    this.internal = internal;
  }

  public Event location(StringValue location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(value = "")
  public StringValue getLocation() {
    return location;
  }

  public void setLocation(StringValue location) {
    this.location = location;
  }

  public Event noteID(GuidValue noteID) {
    this.noteID = noteID;
    return this;
  }

   /**
   * Get noteID
   * @return noteID
  **/
  @ApiModelProperty(value = "")
  public GuidValue getNoteID() {
    return noteID;
  }

  public void setNoteID(GuidValue noteID) {
    this.noteID = noteID;
  }

  public Event priority(StringValue priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(value = "")
  public StringValue getPriority() {
    return priority;
  }

  public void setPriority(StringValue priority) {
    this.priority = priority;
  }

  public Event relatedActivities(List<ActivityDetail> relatedActivities) {
    this.relatedActivities = relatedActivities;
    return this;
  }

  public Event addRelatedActivitiesItem(ActivityDetail relatedActivitiesItem) {
    if (this.relatedActivities == null) {
      this.relatedActivities = new ArrayList<>();
    }
    this.relatedActivities.add(relatedActivitiesItem);
    return this;
  }

   /**
   * Get relatedActivities
   * @return relatedActivities
  **/
  @ApiModelProperty(value = "")
  public List<ActivityDetail> getRelatedActivities() {
    return relatedActivities;
  }

  public void setRelatedActivities(List<ActivityDetail> relatedActivities) {
    this.relatedActivities = relatedActivities;
  }

  public Event reminder(ReminderDetail reminder) {
    this.reminder = reminder;
    return this;
  }

   /**
   * Get reminder
   * @return reminder
  **/
  @ApiModelProperty(value = "")
  public ReminderDetail getReminder() {
    return reminder;
  }

  public void setReminder(ReminderDetail reminder) {
    this.reminder = reminder;
  }

  public Event showAs(StringValue showAs) {
    this.showAs = showAs;
    return this;
  }

   /**
   * Get showAs
   * @return showAs
  **/
  @ApiModelProperty(value = "")
  public StringValue getShowAs() {
    return showAs;
  }

  public void setShowAs(StringValue showAs) {
    this.showAs = showAs;
  }

  public Event startDate(DateTimeValue startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getStartDate() {
    return startDate;
  }

  public void setStartDate(DateTimeValue startDate) {
    this.startDate = startDate;
  }

  public Event status(StringValue status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StringValue getStatus() {
    return status;
  }

  public void setStatus(StringValue status) {
    this.status = status;
  }

  public Event summary(StringValue summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @ApiModelProperty(value = "")
  public StringValue getSummary() {
    return summary;
  }

  public void setSummary(StringValue summary) {
    this.summary = summary;
  }

  public Event timeActivity(EventTimeActivity timeActivity) {
    this.timeActivity = timeActivity;
    return this;
  }

   /**
   * Get timeActivity
   * @return timeActivity
  **/
  @ApiModelProperty(value = "")
  public EventTimeActivity getTimeActivity() {
    return timeActivity;
  }

  public void setTimeActivity(EventTimeActivity timeActivity) {
    this.timeActivity = timeActivity;
  }

  public Event createdByID(StringValue createdByID) {
    this.createdByID = createdByID;
    return this;
  }

   /**
   * Get createdByID
   * @return createdByID
  **/
  @ApiModelProperty(value = "")
  public StringValue getCreatedByID() {
    return createdByID;
  }

  public void setCreatedByID(StringValue createdByID) {
    this.createdByID = createdByID;
  }

  public Event createdDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public Event lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public Event relatedEntityType(StringValue relatedEntityType) {
    this.relatedEntityType = relatedEntityType;
    return this;
  }

   /**
   * Get relatedEntityType
   * @return relatedEntityType
  **/
  @ApiModelProperty(value = "")
  public StringValue getRelatedEntityType() {
    return relatedEntityType;
  }

  public void setRelatedEntityType(StringValue relatedEntityType) {
    this.relatedEntityType = relatedEntityType;
  }

  public Event relatedEntityNoteID(GuidValue relatedEntityNoteID) {
    this.relatedEntityNoteID = relatedEntityNoteID;
    return this;
  }

   /**
   * Get relatedEntityNoteID
   * @return relatedEntityNoteID
  **/
  @ApiModelProperty(value = "")
  public GuidValue getRelatedEntityNoteID() {
    return relatedEntityNoteID;
  }

  public void setRelatedEntityNoteID(GuidValue relatedEntityNoteID) {
    this.relatedEntityNoteID = relatedEntityNoteID;
  }

  public Event relatedEntityDescription(StringValue relatedEntityDescription) {
    this.relatedEntityDescription = relatedEntityDescription;
    return this;
  }

   /**
   * Get relatedEntityDescription
   * @return relatedEntityDescription
  **/
  @ApiModelProperty(value = "")
  public StringValue getRelatedEntityDescription() {
    return relatedEntityDescription;
  }

  public void setRelatedEntityDescription(StringValue relatedEntityDescription) {
    this.relatedEntityDescription = relatedEntityDescription;
  }

}

