/*
 * Default/22.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import model.CustomField;
import model.DateTimeValue;
import model.DecimalValue;
import model.Entity;
import model.FileLink;
import model.StringValue;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * GarnishmentDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-08-17T14:29:48.617Z")
public class GarnishmentDetails extends Entity {
  @SerializedName("GarnCourtDate")
  private DateTimeValue garnCourtDate = null;

  @SerializedName("GarnCourtName")
  private StringValue garnCourtName = null;

  @SerializedName("GarnDocRefNbr")
  private StringValue garnDocRefNbr = null;

  @SerializedName("GarnOrigAmount")
  private DecimalValue garnOrigAmount = null;

  @SerializedName("GarnPaidAmount")
  private DecimalValue garnPaidAmount = null;

  @SerializedName("GarnVendorID")
  private StringValue garnVendorID = null;

  @SerializedName("GarnVendorInvDescr")
  private StringValue garnVendorInvDescr = null;

  public GarnishmentDetails garnCourtDate(DateTimeValue garnCourtDate) {
    this.garnCourtDate = garnCourtDate;
    return this;
  }

   /**
   * Get garnCourtDate
   * @return garnCourtDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getGarnCourtDate() {
    return garnCourtDate;
  }

  public void setGarnCourtDate(DateTimeValue garnCourtDate) {
    this.garnCourtDate = garnCourtDate;
  }

  public GarnishmentDetails garnCourtName(StringValue garnCourtName) {
    this.garnCourtName = garnCourtName;
    return this;
  }

   /**
   * Get garnCourtName
   * @return garnCourtName
  **/
  @ApiModelProperty(value = "")
  public StringValue getGarnCourtName() {
    return garnCourtName;
  }

  public void setGarnCourtName(StringValue garnCourtName) {
    this.garnCourtName = garnCourtName;
  }

  public GarnishmentDetails garnDocRefNbr(StringValue garnDocRefNbr) {
    this.garnDocRefNbr = garnDocRefNbr;
    return this;
  }

   /**
   * Get garnDocRefNbr
   * @return garnDocRefNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getGarnDocRefNbr() {
    return garnDocRefNbr;
  }

  public void setGarnDocRefNbr(StringValue garnDocRefNbr) {
    this.garnDocRefNbr = garnDocRefNbr;
  }

  public GarnishmentDetails garnOrigAmount(DecimalValue garnOrigAmount) {
    this.garnOrigAmount = garnOrigAmount;
    return this;
  }

   /**
   * Get garnOrigAmount
   * @return garnOrigAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getGarnOrigAmount() {
    return garnOrigAmount;
  }

  public void setGarnOrigAmount(DecimalValue garnOrigAmount) {
    this.garnOrigAmount = garnOrigAmount;
  }

  public GarnishmentDetails garnPaidAmount(DecimalValue garnPaidAmount) {
    this.garnPaidAmount = garnPaidAmount;
    return this;
  }

   /**
   * Get garnPaidAmount
   * @return garnPaidAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getGarnPaidAmount() {
    return garnPaidAmount;
  }

  public void setGarnPaidAmount(DecimalValue garnPaidAmount) {
    this.garnPaidAmount = garnPaidAmount;
  }

  public GarnishmentDetails garnVendorID(StringValue garnVendorID) {
    this.garnVendorID = garnVendorID;
    return this;
  }

   /**
   * Get garnVendorID
   * @return garnVendorID
  **/
  @ApiModelProperty(value = "")
  public StringValue getGarnVendorID() {
    return garnVendorID;
  }

  public void setGarnVendorID(StringValue garnVendorID) {
    this.garnVendorID = garnVendorID;
  }

  public GarnishmentDetails garnVendorInvDescr(StringValue garnVendorInvDescr) {
    this.garnVendorInvDescr = garnVendorInvDescr;
    return this;
  }

   /**
   * Get garnVendorInvDescr
   * @return garnVendorInvDescr
  **/
  @ApiModelProperty(value = "")
  public StringValue getGarnVendorInvDescr() {
    return garnVendorInvDescr;
  }

  public void setGarnVendorInvDescr(StringValue garnVendorInvDescr) {
    this.garnVendorInvDescr = garnVendorInvDescr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GarnishmentDetails garnishmentDetails = (GarnishmentDetails) o;
    return Objects.equals(this.garnCourtDate, garnishmentDetails.garnCourtDate) &&
        Objects.equals(this.garnCourtName, garnishmentDetails.garnCourtName) &&
        Objects.equals(this.garnDocRefNbr, garnishmentDetails.garnDocRefNbr) &&
        Objects.equals(this.garnOrigAmount, garnishmentDetails.garnOrigAmount) &&
        Objects.equals(this.garnPaidAmount, garnishmentDetails.garnPaidAmount) &&
        Objects.equals(this.garnVendorID, garnishmentDetails.garnVendorID) &&
        Objects.equals(this.garnVendorInvDescr, garnishmentDetails.garnVendorInvDescr) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(garnCourtDate, garnCourtName, garnDocRefNbr, garnOrigAmount, garnPaidAmount, garnVendorID, garnVendorInvDescr, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GarnishmentDetails {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    garnCourtDate: ").append(toIndentedString(garnCourtDate)).append("\n");
    sb.append("    garnCourtName: ").append(toIndentedString(garnCourtName)).append("\n");
    sb.append("    garnDocRefNbr: ").append(toIndentedString(garnDocRefNbr)).append("\n");
    sb.append("    garnOrigAmount: ").append(toIndentedString(garnOrigAmount)).append("\n");
    sb.append("    garnPaidAmount: ").append(toIndentedString(garnPaidAmount)).append("\n");
    sb.append("    garnVendorID: ").append(toIndentedString(garnVendorID)).append("\n");
    sb.append("    garnVendorInvDescr: ").append(toIndentedString(garnVendorInvDescr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

