/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * InvoiceDiscountDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class InvoiceDiscountDetail extends Entity {
  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("DiscountableAmount")
  private DecimalValue discountableAmount = null;

  @SerializedName("DiscountableQty")
  private DecimalValue discountableQty = null;

  @SerializedName("DiscountAmount")
  private DecimalValue discountAmount = null;

  @SerializedName("DiscountCode")
  private StringValue discountCode = null;

  @SerializedName("DiscountPercent")
  private DecimalValue discountPercent = null;

  @SerializedName("ExternalDiscountCode")
  private StringValue externalDiscountCode = null;

  @SerializedName("ManualDiscount")
  private BooleanValue manualDiscount = null;

  @SerializedName("OrderNbr")
  private StringValue orderNbr = null;

  @SerializedName("OrderType")
  private StringValue orderType = null;

  @SerializedName("RetainedDiscount")
  private DecimalValue retainedDiscount = null;

  @SerializedName("SequenceID")
  private StringValue sequenceID = null;

  @SerializedName("SkipDiscount")
  private BooleanValue skipDiscount = null;

  @SerializedName("Type")
  private StringValue type = null;

  public InvoiceDiscountDetail description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public InvoiceDiscountDetail discountableAmount(DecimalValue discountableAmount) {
    this.discountableAmount = discountableAmount;
    return this;
  }

   /**
   * Get discountableAmount
   * @return discountableAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getDiscountableAmount() {
    return discountableAmount;
  }

  public void setDiscountableAmount(DecimalValue discountableAmount) {
    this.discountableAmount = discountableAmount;
  }

  public InvoiceDiscountDetail discountableQty(DecimalValue discountableQty) {
    this.discountableQty = discountableQty;
    return this;
  }

   /**
   * Get discountableQty
   * @return discountableQty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getDiscountableQty() {
    return discountableQty;
  }

  public void setDiscountableQty(DecimalValue discountableQty) {
    this.discountableQty = discountableQty;
  }

  public InvoiceDiscountDetail discountAmount(DecimalValue discountAmount) {
    this.discountAmount = discountAmount;
    return this;
  }

   /**
   * Get discountAmount
   * @return discountAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getDiscountAmount() {
    return discountAmount;
  }

  public void setDiscountAmount(DecimalValue discountAmount) {
    this.discountAmount = discountAmount;
  }

  public InvoiceDiscountDetail discountCode(StringValue discountCode) {
    this.discountCode = discountCode;
    return this;
  }

   /**
   * Get discountCode
   * @return discountCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getDiscountCode() {
    return discountCode;
  }

  public void setDiscountCode(StringValue discountCode) {
    this.discountCode = discountCode;
  }

  public InvoiceDiscountDetail discountPercent(DecimalValue discountPercent) {
    this.discountPercent = discountPercent;
    return this;
  }

   /**
   * Get discountPercent
   * @return discountPercent
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getDiscountPercent() {
    return discountPercent;
  }

  public void setDiscountPercent(DecimalValue discountPercent) {
    this.discountPercent = discountPercent;
  }

  public InvoiceDiscountDetail externalDiscountCode(StringValue externalDiscountCode) {
    this.externalDiscountCode = externalDiscountCode;
    return this;
  }

   /**
   * Get externalDiscountCode
   * @return externalDiscountCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getExternalDiscountCode() {
    return externalDiscountCode;
  }

  public void setExternalDiscountCode(StringValue externalDiscountCode) {
    this.externalDiscountCode = externalDiscountCode;
  }

  public InvoiceDiscountDetail manualDiscount(BooleanValue manualDiscount) {
    this.manualDiscount = manualDiscount;
    return this;
  }

   /**
   * Get manualDiscount
   * @return manualDiscount
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getManualDiscount() {
    return manualDiscount;
  }

  public void setManualDiscount(BooleanValue manualDiscount) {
    this.manualDiscount = manualDiscount;
  }

  public InvoiceDiscountDetail orderNbr(StringValue orderNbr) {
    this.orderNbr = orderNbr;
    return this;
  }

   /**
   * Get orderNbr
   * @return orderNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getOrderNbr() {
    return orderNbr;
  }

  public void setOrderNbr(StringValue orderNbr) {
    this.orderNbr = orderNbr;
  }

  public InvoiceDiscountDetail orderType(StringValue orderType) {
    this.orderType = orderType;
    return this;
  }

   /**
   * Get orderType
   * @return orderType
  **/
  @ApiModelProperty(value = "")
  public StringValue getOrderType() {
    return orderType;
  }

  public void setOrderType(StringValue orderType) {
    this.orderType = orderType;
  }

  public InvoiceDiscountDetail retainedDiscount(DecimalValue retainedDiscount) {
    this.retainedDiscount = retainedDiscount;
    return this;
  }

   /**
   * Get retainedDiscount
   * @return retainedDiscount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getRetainedDiscount() {
    return retainedDiscount;
  }

  public void setRetainedDiscount(DecimalValue retainedDiscount) {
    this.retainedDiscount = retainedDiscount;
  }

  public InvoiceDiscountDetail sequenceID(StringValue sequenceID) {
    this.sequenceID = sequenceID;
    return this;
  }

   /**
   * Get sequenceID
   * @return sequenceID
  **/
  @ApiModelProperty(value = "")
  public StringValue getSequenceID() {
    return sequenceID;
  }

  public void setSequenceID(StringValue sequenceID) {
    this.sequenceID = sequenceID;
  }

  public InvoiceDiscountDetail skipDiscount(BooleanValue skipDiscount) {
    this.skipDiscount = skipDiscount;
    return this;
  }

   /**
   * Get skipDiscount
   * @return skipDiscount
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getSkipDiscount() {
    return skipDiscount;
  }

  public void setSkipDiscount(BooleanValue skipDiscount) {
    this.skipDiscount = skipDiscount;
  }

  public InvoiceDiscountDetail type(StringValue type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public StringValue getType() {
    return type;
  }

  public void setType(StringValue type) {
    this.type = type;
  }

}

