/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * KitAssemblyNonStockComponent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class KitAssemblyNonStockComponent extends Entity {
  @SerializedName("ComponentQty")
  private DecimalValue componentQty = null;

  @SerializedName("LineNbr")
  private IntValue lineNbr = null;

  @SerializedName("NonStockInventoryID")
  private StringValue nonStockInventoryID = null;

  @SerializedName("Qty")
  private DecimalValue qty = null;

  @SerializedName("ReasonCode")
  private StringValue reasonCode = null;

  @SerializedName("UnitCost")
  private DecimalValue unitCost = null;

  @SerializedName("UOM")
  private StringValue UOM = null;

  public KitAssemblyNonStockComponent componentQty(DecimalValue componentQty) {
    this.componentQty = componentQty;
    return this;
  }

   /**
   * Get componentQty
   * @return componentQty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getComponentQty() {
    return componentQty;
  }

  public void setComponentQty(DecimalValue componentQty) {
    this.componentQty = componentQty;
  }

  public KitAssemblyNonStockComponent lineNbr(IntValue lineNbr) {
    this.lineNbr = lineNbr;
    return this;
  }

   /**
   * Get lineNbr
   * @return lineNbr
  **/
  @ApiModelProperty(value = "")
  public IntValue getLineNbr() {
    return lineNbr;
  }

  public void setLineNbr(IntValue lineNbr) {
    this.lineNbr = lineNbr;
  }

  public KitAssemblyNonStockComponent nonStockInventoryID(StringValue nonStockInventoryID) {
    this.nonStockInventoryID = nonStockInventoryID;
    return this;
  }

   /**
   * Get nonStockInventoryID
   * @return nonStockInventoryID
  **/
  @ApiModelProperty(value = "")
  public StringValue getNonStockInventoryID() {
    return nonStockInventoryID;
  }

  public void setNonStockInventoryID(StringValue nonStockInventoryID) {
    this.nonStockInventoryID = nonStockInventoryID;
  }

  public KitAssemblyNonStockComponent qty(DecimalValue qty) {
    this.qty = qty;
    return this;
  }

   /**
   * Get qty
   * @return qty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getQty() {
    return qty;
  }

  public void setQty(DecimalValue qty) {
    this.qty = qty;
  }

  public KitAssemblyNonStockComponent reasonCode(StringValue reasonCode) {
    this.reasonCode = reasonCode;
    return this;
  }

   /**
   * Get reasonCode
   * @return reasonCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getReasonCode() {
    return reasonCode;
  }

  public void setReasonCode(StringValue reasonCode) {
    this.reasonCode = reasonCode;
  }

  public KitAssemblyNonStockComponent unitCost(DecimalValue unitCost) {
    this.unitCost = unitCost;
    return this;
  }

   /**
   * Get unitCost
   * @return unitCost
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getUnitCost() {
    return unitCost;
  }

  public void setUnitCost(DecimalValue unitCost) {
    this.unitCost = unitCost;
  }

  public KitAssemblyNonStockComponent UOM(StringValue UOM) {
    this.UOM = UOM;
    return this;
  }

   /**
   * Get UOM
   * @return UOM
  **/
  @ApiModelProperty(value = "")
  public StringValue getUOM() {
    return UOM;
  }

  public void setUOM(StringValue UOM) {
    this.UOM = UOM;
  }

}

