/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * KitAssembly
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class KitAssembly extends Entity {
  @SerializedName("Allocations")
  private List<KitAssemblyAllocation> allocations = null;

  @SerializedName("Date")
  private DateTimeValue date = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("Hold")
  private BooleanValue hold = null;

  @SerializedName("KitInventoryID")
  private StringValue kitInventoryID = null;

  @SerializedName("LocationID")
  private StringValue locationID = null;

  @SerializedName("NonStockComponents")
  private List<KitAssemblyNonStockComponent> nonStockComponents = null;

  @SerializedName("PostPeriod")
  private StringValue postPeriod = null;

  @SerializedName("Qty")
  private DecimalValue qty = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("ReasonCode")
  private StringValue reasonCode = null;

  @SerializedName("ReferenceNbr")
  private StringValue referenceNbr = null;

  @SerializedName("Revision")
  private StringValue revision = null;

  @SerializedName("Status")
  private StringValue status = null;

  @SerializedName("StockComponents")
  private List<KitAssemblyStockComponent> stockComponents = null;

  @SerializedName("Subitem")
  private StringValue subitem = null;

  @SerializedName("Type")
  private StringValue type = null;

  @SerializedName("UOM")
  private StringValue UOM = null;

  @SerializedName("WarehouseID")
  private StringValue warehouseID = null;

  public KitAssembly allocations(List<KitAssemblyAllocation> allocations) {
    this.allocations = allocations;
    return this;
  }

  public KitAssembly addAllocationsItem(KitAssemblyAllocation allocationsItem) {
    if (this.allocations == null) {
      this.allocations = new ArrayList<>();
    }
    this.allocations.add(allocationsItem);
    return this;
  }

   /**
   * Get allocations
   * @return allocations
  **/
  @ApiModelProperty(value = "")
  public List<KitAssemblyAllocation> getAllocations() {
    return allocations;
  }

  public void setAllocations(List<KitAssemblyAllocation> allocations) {
    this.allocations = allocations;
  }

  public KitAssembly date(DateTimeValue date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getDate() {
    return date;
  }

  public void setDate(DateTimeValue date) {
    this.date = date;
  }

  public KitAssembly description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public KitAssembly hold(BooleanValue hold) {
    this.hold = hold;
    return this;
  }

   /**
   * Get hold
   * @return hold
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getHold() {
    return hold;
  }

  public void setHold(BooleanValue hold) {
    this.hold = hold;
  }

  public KitAssembly kitInventoryID(StringValue kitInventoryID) {
    this.kitInventoryID = kitInventoryID;
    return this;
  }

   /**
   * Get kitInventoryID
   * @return kitInventoryID
  **/
  @ApiModelProperty(value = "")
  public StringValue getKitInventoryID() {
    return kitInventoryID;
  }

  public void setKitInventoryID(StringValue kitInventoryID) {
    this.kitInventoryID = kitInventoryID;
  }

  public KitAssembly locationID(StringValue locationID) {
    this.locationID = locationID;
    return this;
  }

   /**
   * Get locationID
   * @return locationID
  **/
  @ApiModelProperty(value = "")
  public StringValue getLocationID() {
    return locationID;
  }

  public void setLocationID(StringValue locationID) {
    this.locationID = locationID;
  }

  public KitAssembly nonStockComponents(List<KitAssemblyNonStockComponent> nonStockComponents) {
    this.nonStockComponents = nonStockComponents;
    return this;
  }

  public KitAssembly addNonStockComponentsItem(KitAssemblyNonStockComponent nonStockComponentsItem) {
    if (this.nonStockComponents == null) {
      this.nonStockComponents = new ArrayList<>();
    }
    this.nonStockComponents.add(nonStockComponentsItem);
    return this;
  }

   /**
   * Get nonStockComponents
   * @return nonStockComponents
  **/
  @ApiModelProperty(value = "")
  public List<KitAssemblyNonStockComponent> getNonStockComponents() {
    return nonStockComponents;
  }

  public void setNonStockComponents(List<KitAssemblyNonStockComponent> nonStockComponents) {
    this.nonStockComponents = nonStockComponents;
  }

  public KitAssembly postPeriod(StringValue postPeriod) {
    this.postPeriod = postPeriod;
    return this;
  }

   /**
   * Get postPeriod
   * @return postPeriod
  **/
  @ApiModelProperty(value = "")
  public StringValue getPostPeriod() {
    return postPeriod;
  }

  public void setPostPeriod(StringValue postPeriod) {
    this.postPeriod = postPeriod;
  }

  public KitAssembly qty(DecimalValue qty) {
    this.qty = qty;
    return this;
  }

   /**
   * Get qty
   * @return qty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getQty() {
    return qty;
  }

  public void setQty(DecimalValue qty) {
    this.qty = qty;
  }

  public KitAssembly lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public KitAssembly reasonCode(StringValue reasonCode) {
    this.reasonCode = reasonCode;
    return this;
  }

   /**
   * Get reasonCode
   * @return reasonCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getReasonCode() {
    return reasonCode;
  }

  public void setReasonCode(StringValue reasonCode) {
    this.reasonCode = reasonCode;
  }

  public KitAssembly referenceNbr(StringValue referenceNbr) {
    this.referenceNbr = referenceNbr;
    return this;
  }

   /**
   * Get referenceNbr
   * @return referenceNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getReferenceNbr() {
    return referenceNbr;
  }

  public void setReferenceNbr(StringValue referenceNbr) {
    this.referenceNbr = referenceNbr;
  }

  public KitAssembly revision(StringValue revision) {
    this.revision = revision;
    return this;
  }

   /**
   * Get revision
   * @return revision
  **/
  @ApiModelProperty(value = "")
  public StringValue getRevision() {
    return revision;
  }

  public void setRevision(StringValue revision) {
    this.revision = revision;
  }

  public KitAssembly status(StringValue status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StringValue getStatus() {
    return status;
  }

  public void setStatus(StringValue status) {
    this.status = status;
  }

  public KitAssembly stockComponents(List<KitAssemblyStockComponent> stockComponents) {
    this.stockComponents = stockComponents;
    return this;
  }

  public KitAssembly addStockComponentsItem(KitAssemblyStockComponent stockComponentsItem) {
    if (this.stockComponents == null) {
      this.stockComponents = new ArrayList<>();
    }
    this.stockComponents.add(stockComponentsItem);
    return this;
  }

   /**
   * Get stockComponents
   * @return stockComponents
  **/
  @ApiModelProperty(value = "")
  public List<KitAssemblyStockComponent> getStockComponents() {
    return stockComponents;
  }

  public void setStockComponents(List<KitAssemblyStockComponent> stockComponents) {
    this.stockComponents = stockComponents;
  }

  public KitAssembly subitem(StringValue subitem) {
    this.subitem = subitem;
    return this;
  }

   /**
   * Get subitem
   * @return subitem
  **/
  @ApiModelProperty(value = "")
  public StringValue getSubitem() {
    return subitem;
  }

  public void setSubitem(StringValue subitem) {
    this.subitem = subitem;
  }

  public KitAssembly type(StringValue type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public StringValue getType() {
    return type;
  }

  public void setType(StringValue type) {
    this.type = type;
  }

  public KitAssembly UOM(StringValue UOM) {
    this.UOM = UOM;
    return this;
  }

   /**
   * Get UOM
   * @return UOM
  **/
  @ApiModelProperty(value = "")
  public StringValue getUOM() {
    return UOM;
  }

  public void setUOM(StringValue UOM) {
    this.UOM = UOM;
  }

  public KitAssembly warehouseID(StringValue warehouseID) {
    this.warehouseID = warehouseID;
    return this;
  }

   /**
   * Get warehouseID
   * @return warehouseID
  **/
  @ApiModelProperty(value = "")
  public StringValue getWarehouseID() {
    return warehouseID;
  }

  public void setWarehouseID(StringValue warehouseID) {
    this.warehouseID = warehouseID;
  }

}

