/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * KitAssemblyStockComponent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class KitAssemblyStockComponent extends Entity {
  @SerializedName("Allocations")
  private List<KitAssemblyStockComponentAllocation> allocations = null;

  @SerializedName("ComponentQty")
  private DecimalValue componentQty = null;

  @SerializedName("LineNbr")
  private IntValue lineNbr = null;

  @SerializedName("LocationID")
  private StringValue locationID = null;

  @SerializedName("Qty")
  private DecimalValue qty = null;

  @SerializedName("ReasonCode")
  private StringValue reasonCode = null;

  @SerializedName("StockInventoryID")
  private StringValue stockInventoryID = null;

  @SerializedName("Subitem")
  private StringValue subitem = null;

  @SerializedName("UnitCost")
  private DecimalValue unitCost = null;

  @SerializedName("UOM")
  private StringValue UOM = null;

  public KitAssemblyStockComponent allocations(List<KitAssemblyStockComponentAllocation> allocations) {
    this.allocations = allocations;
    return this;
  }

  public KitAssemblyStockComponent addAllocationsItem(KitAssemblyStockComponentAllocation allocationsItem) {
    if (this.allocations == null) {
      this.allocations = new ArrayList<>();
    }
    this.allocations.add(allocationsItem);
    return this;
  }

   /**
   * Get allocations
   * @return allocations
  **/
  @ApiModelProperty(value = "")
  public List<KitAssemblyStockComponentAllocation> getAllocations() {
    return allocations;
  }

  public void setAllocations(List<KitAssemblyStockComponentAllocation> allocations) {
    this.allocations = allocations;
  }

  public KitAssemblyStockComponent componentQty(DecimalValue componentQty) {
    this.componentQty = componentQty;
    return this;
  }

   /**
   * Get componentQty
   * @return componentQty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getComponentQty() {
    return componentQty;
  }

  public void setComponentQty(DecimalValue componentQty) {
    this.componentQty = componentQty;
  }

  public KitAssemblyStockComponent lineNbr(IntValue lineNbr) {
    this.lineNbr = lineNbr;
    return this;
  }

   /**
   * Get lineNbr
   * @return lineNbr
  **/
  @ApiModelProperty(value = "")
  public IntValue getLineNbr() {
    return lineNbr;
  }

  public void setLineNbr(IntValue lineNbr) {
    this.lineNbr = lineNbr;
  }

  public KitAssemblyStockComponent locationID(StringValue locationID) {
    this.locationID = locationID;
    return this;
  }

   /**
   * Get locationID
   * @return locationID
  **/
  @ApiModelProperty(value = "")
  public StringValue getLocationID() {
    return locationID;
  }

  public void setLocationID(StringValue locationID) {
    this.locationID = locationID;
  }

  public KitAssemblyStockComponent qty(DecimalValue qty) {
    this.qty = qty;
    return this;
  }

   /**
   * Get qty
   * @return qty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getQty() {
    return qty;
  }

  public void setQty(DecimalValue qty) {
    this.qty = qty;
  }

  public KitAssemblyStockComponent reasonCode(StringValue reasonCode) {
    this.reasonCode = reasonCode;
    return this;
  }

   /**
   * Get reasonCode
   * @return reasonCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getReasonCode() {
    return reasonCode;
  }

  public void setReasonCode(StringValue reasonCode) {
    this.reasonCode = reasonCode;
  }

  public KitAssemblyStockComponent stockInventoryID(StringValue stockInventoryID) {
    this.stockInventoryID = stockInventoryID;
    return this;
  }

   /**
   * Get stockInventoryID
   * @return stockInventoryID
  **/
  @ApiModelProperty(value = "")
  public StringValue getStockInventoryID() {
    return stockInventoryID;
  }

  public void setStockInventoryID(StringValue stockInventoryID) {
    this.stockInventoryID = stockInventoryID;
  }

  public KitAssemblyStockComponent subitem(StringValue subitem) {
    this.subitem = subitem;
    return this;
  }

   /**
   * Get subitem
   * @return subitem
  **/
  @ApiModelProperty(value = "")
  public StringValue getSubitem() {
    return subitem;
  }

  public void setSubitem(StringValue subitem) {
    this.subitem = subitem;
  }

  public KitAssemblyStockComponent unitCost(DecimalValue unitCost) {
    this.unitCost = unitCost;
    return this;
  }

   /**
   * Get unitCost
   * @return unitCost
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getUnitCost() {
    return unitCost;
  }

  public void setUnitCost(DecimalValue unitCost) {
    this.unitCost = unitCost;
  }

  public KitAssemblyStockComponent UOM(StringValue UOM) {
    this.UOM = UOM;
    return this;
  }

   /**
   * Get UOM
   * @return UOM
  **/
  @ApiModelProperty(value = "")
  public StringValue getUOM() {
    return UOM;
  }

  public void setUOM(StringValue UOM) {
    this.UOM = UOM;
  }

}

