/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * OpportunityContact
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class OpportunityContact extends Entity {
  @SerializedName("Attention")
  private StringValue attention = null;

  @SerializedName("CompanyName")
  private StringValue companyName = null;

  @SerializedName("Email")
  private StringValue email = null;

  @SerializedName("Fax")
  private StringValue fax = null;

  @SerializedName("FaxType")
  private StringValue faxType = null;

  @SerializedName("FirstName")
  private StringValue firstName = null;

  @SerializedName("LastName")
  private StringValue lastName = null;

  @SerializedName("Phone1")
  private StringValue phone1 = null;

  @SerializedName("Phone1Type")
  private StringValue phone1Type = null;

  @SerializedName("Phone2")
  private StringValue phone2 = null;

  @SerializedName("Phone2Type")
  private StringValue phone2Type = null;

  @SerializedName("Phone3")
  private StringValue phone3 = null;

  @SerializedName("Phone3Type")
  private StringValue phone3Type = null;

  @SerializedName("Position")
  private StringValue position = null;

  @SerializedName("Title")
  private StringValue title = null;

  @SerializedName("WebSite")
  private StringValue webSite = null;

  public OpportunityContact attention(StringValue attention) {
    this.attention = attention;
    return this;
  }

   /**
   * Get attention
   * @return attention
  **/
  @ApiModelProperty(value = "")
  public StringValue getAttention() {
    return attention;
  }

  public void setAttention(StringValue attention) {
    this.attention = attention;
  }

  public OpportunityContact companyName(StringValue companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @ApiModelProperty(value = "")
  public StringValue getCompanyName() {
    return companyName;
  }

  public void setCompanyName(StringValue companyName) {
    this.companyName = companyName;
  }

  public OpportunityContact email(StringValue email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public StringValue getEmail() {
    return email;
  }

  public void setEmail(StringValue email) {
    this.email = email;
  }

  public OpportunityContact fax(StringValue fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Get fax
   * @return fax
  **/
  @ApiModelProperty(value = "")
  public StringValue getFax() {
    return fax;
  }

  public void setFax(StringValue fax) {
    this.fax = fax;
  }

  public OpportunityContact faxType(StringValue faxType) {
    this.faxType = faxType;
    return this;
  }

   /**
   * Get faxType
   * @return faxType
  **/
  @ApiModelProperty(value = "")
  public StringValue getFaxType() {
    return faxType;
  }

  public void setFaxType(StringValue faxType) {
    this.faxType = faxType;
  }

  public OpportunityContact firstName(StringValue firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public StringValue getFirstName() {
    return firstName;
  }

  public void setFirstName(StringValue firstName) {
    this.firstName = firstName;
  }

  public OpportunityContact lastName(StringValue lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public StringValue getLastName() {
    return lastName;
  }

  public void setLastName(StringValue lastName) {
    this.lastName = lastName;
  }

  public OpportunityContact phone1(StringValue phone1) {
    this.phone1 = phone1;
    return this;
  }

   /**
   * Get phone1
   * @return phone1
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone1() {
    return phone1;
  }

  public void setPhone1(StringValue phone1) {
    this.phone1 = phone1;
  }

  public OpportunityContact phone1Type(StringValue phone1Type) {
    this.phone1Type = phone1Type;
    return this;
  }

   /**
   * Get phone1Type
   * @return phone1Type
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone1Type() {
    return phone1Type;
  }

  public void setPhone1Type(StringValue phone1Type) {
    this.phone1Type = phone1Type;
  }

  public OpportunityContact phone2(StringValue phone2) {
    this.phone2 = phone2;
    return this;
  }

   /**
   * Get phone2
   * @return phone2
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone2() {
    return phone2;
  }

  public void setPhone2(StringValue phone2) {
    this.phone2 = phone2;
  }

  public OpportunityContact phone2Type(StringValue phone2Type) {
    this.phone2Type = phone2Type;
    return this;
  }

   /**
   * Get phone2Type
   * @return phone2Type
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone2Type() {
    return phone2Type;
  }

  public void setPhone2Type(StringValue phone2Type) {
    this.phone2Type = phone2Type;
  }

  public OpportunityContact phone3(StringValue phone3) {
    this.phone3 = phone3;
    return this;
  }

   /**
   * Get phone3
   * @return phone3
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone3() {
    return phone3;
  }

  public void setPhone3(StringValue phone3) {
    this.phone3 = phone3;
  }

  public OpportunityContact phone3Type(StringValue phone3Type) {
    this.phone3Type = phone3Type;
    return this;
  }

   /**
   * Get phone3Type
   * @return phone3Type
  **/
  @ApiModelProperty(value = "")
  public StringValue getPhone3Type() {
    return phone3Type;
  }

  public void setPhone3Type(StringValue phone3Type) {
    this.phone3Type = phone3Type;
  }

  public OpportunityContact position(StringValue position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(value = "")
  public StringValue getPosition() {
    return position;
  }

  public void setPosition(StringValue position) {
    this.position = position;
  }

  public OpportunityContact title(StringValue title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public StringValue getTitle() {
    return title;
  }

  public void setTitle(StringValue title) {
    this.title = title;
  }

  public OpportunityContact webSite(StringValue webSite) {
    this.webSite = webSite;
    return this;
  }

   /**
   * Get webSite
   * @return webSite
  **/
  @ApiModelProperty(value = "")
  public StringValue getWebSite() {
    return webSite;
  }

  public void setWebSite(StringValue webSite) {
    this.webSite = webSite;
  }

}

