/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * PaymentMethod
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class PaymentMethod extends Entity {
  @SerializedName("Active")
  private BooleanValue active = null;

  @SerializedName("AllowedCashAccounts")
  private List<PaymentMethodAllowedCashAccountDetail> allowedCashAccounts = null;

  @SerializedName("CreatedDateTime")
  private DateTimeValue createdDateTime = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("IntegratedProcessing")
  private BooleanValue integratedProcessing = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("MeansOfPayment")
  private StringValue meansOfPayment = null;

  @SerializedName("PaymentMethodID")
  private StringValue paymentMethodID = null;

  @SerializedName("ProcessingCenters")
  private List<PaymentMethodProcessingCenterDetail> processingCenters = null;

  @SerializedName("RequireRemittanceInformationforCashAccount")
  private BooleanValue requireRemittanceInformationforCashAccount = null;

  @SerializedName("UseInAP")
  private BooleanValue useInAP = null;

  @SerializedName("UseInAR")
  private BooleanValue useInAR = null;

  public PaymentMethod active(BooleanValue active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getActive() {
    return active;
  }

  public void setActive(BooleanValue active) {
    this.active = active;
  }

  public PaymentMethod allowedCashAccounts(List<PaymentMethodAllowedCashAccountDetail> allowedCashAccounts) {
    this.allowedCashAccounts = allowedCashAccounts;
    return this;
  }

  public PaymentMethod addAllowedCashAccountsItem(PaymentMethodAllowedCashAccountDetail allowedCashAccountsItem) {
    if (this.allowedCashAccounts == null) {
      this.allowedCashAccounts = new ArrayList<>();
    }
    this.allowedCashAccounts.add(allowedCashAccountsItem);
    return this;
  }

   /**
   * Get allowedCashAccounts
   * @return allowedCashAccounts
  **/
  @ApiModelProperty(value = "")
  public List<PaymentMethodAllowedCashAccountDetail> getAllowedCashAccounts() {
    return allowedCashAccounts;
  }

  public void setAllowedCashAccounts(List<PaymentMethodAllowedCashAccountDetail> allowedCashAccounts) {
    this.allowedCashAccounts = allowedCashAccounts;
  }

  public PaymentMethod createdDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public PaymentMethod description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public PaymentMethod integratedProcessing(BooleanValue integratedProcessing) {
    this.integratedProcessing = integratedProcessing;
    return this;
  }

   /**
   * Get integratedProcessing
   * @return integratedProcessing
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getIntegratedProcessing() {
    return integratedProcessing;
  }

  public void setIntegratedProcessing(BooleanValue integratedProcessing) {
    this.integratedProcessing = integratedProcessing;
  }

  public PaymentMethod lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public PaymentMethod meansOfPayment(StringValue meansOfPayment) {
    this.meansOfPayment = meansOfPayment;
    return this;
  }

   /**
   * Get meansOfPayment
   * @return meansOfPayment
  **/
  @ApiModelProperty(value = "")
  public StringValue getMeansOfPayment() {
    return meansOfPayment;
  }

  public void setMeansOfPayment(StringValue meansOfPayment) {
    this.meansOfPayment = meansOfPayment;
  }

  public PaymentMethod paymentMethodID(StringValue paymentMethodID) {
    this.paymentMethodID = paymentMethodID;
    return this;
  }

   /**
   * Get paymentMethodID
   * @return paymentMethodID
  **/
  @ApiModelProperty(value = "")
  public StringValue getPaymentMethodID() {
    return paymentMethodID;
  }

  public void setPaymentMethodID(StringValue paymentMethodID) {
    this.paymentMethodID = paymentMethodID;
  }

  public PaymentMethod processingCenters(List<PaymentMethodProcessingCenterDetail> processingCenters) {
    this.processingCenters = processingCenters;
    return this;
  }

  public PaymentMethod addProcessingCentersItem(PaymentMethodProcessingCenterDetail processingCentersItem) {
    if (this.processingCenters == null) {
      this.processingCenters = new ArrayList<>();
    }
    this.processingCenters.add(processingCentersItem);
    return this;
  }

   /**
   * Get processingCenters
   * @return processingCenters
  **/
  @ApiModelProperty(value = "")
  public List<PaymentMethodProcessingCenterDetail> getProcessingCenters() {
    return processingCenters;
  }

  public void setProcessingCenters(List<PaymentMethodProcessingCenterDetail> processingCenters) {
    this.processingCenters = processingCenters;
  }

  public PaymentMethod requireRemittanceInformationforCashAccount(BooleanValue requireRemittanceInformationforCashAccount) {
    this.requireRemittanceInformationforCashAccount = requireRemittanceInformationforCashAccount;
    return this;
  }

   /**
   * Get requireRemittanceInformationforCashAccount
   * @return requireRemittanceInformationforCashAccount
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getRequireRemittanceInformationforCashAccount() {
    return requireRemittanceInformationforCashAccount;
  }

  public void setRequireRemittanceInformationforCashAccount(BooleanValue requireRemittanceInformationforCashAccount) {
    this.requireRemittanceInformationforCashAccount = requireRemittanceInformationforCashAccount;
  }

  public PaymentMethod useInAP(BooleanValue useInAP) {
    this.useInAP = useInAP;
    return this;
  }

   /**
   * Get useInAP
   * @return useInAP
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getUseInAP() {
    return useInAP;
  }

  public void setUseInAP(BooleanValue useInAP) {
    this.useInAP = useInAP;
  }

  public PaymentMethod useInAR(BooleanValue useInAR) {
    this.useInAR = useInAR;
    return this;
  }

   /**
   * Get useInAR
   * @return useInAR
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getUseInAR() {
    return useInAR;
  }

  public void setUseInAR(BooleanValue useInAR) {
    this.useInAR = useInAR;
  }

}

