/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Payment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class Payment extends Entity {
  @SerializedName("ApplicationDate")
  private DateTimeValue applicationDate = null;

  @SerializedName("ApplicationHistory")
  private List<PaymentApplicationHistoryDetail> applicationHistory = null;

  @SerializedName("AppliedToDocuments")
  private DecimalValue appliedToDocuments = null;

  @SerializedName("Branch")
  private StringValue branch = null;

  @SerializedName("CardAccountNbr")
  private IntValue cardAccountNbr = null;

  @SerializedName("CashAccount")
  private StringValue cashAccount = null;

  @SerializedName("CreditCardProcessingInfo")
  private List<CreditCardProcessingDetail> creditCardProcessingInfo = null;

  @SerializedName("CurrencyID")
  private StringValue currencyID = null;

  @SerializedName("CustomerID")
  private StringValue customerID = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("DocumentsToApply")
  private List<PaymentDetail> documentsToApply = null;

  @SerializedName("Hold")
  private BooleanValue hold = null;

  @SerializedName("OrdersToApply")
  private List<PaymentOrderDetail> ordersToApply = null;

  @SerializedName("PaymentAmount")
  private DecimalValue paymentAmount = null;

  @SerializedName("PaymentMethod")
  private StringValue paymentMethod = null;

  @SerializedName("PaymentRef")
  private StringValue paymentRef = null;

  @SerializedName("ReferenceNbr")
  private StringValue referenceNbr = null;

  @SerializedName("Status")
  private StringValue status = null;

  @SerializedName("Type")
  private StringValue type = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("ProcessingCenterID")
  private StringValue processingCenterID = null;

  @SerializedName("SaveCard")
  private BooleanValue saveCard = null;

  @SerializedName("CreditCardTransactionInfo")
  private List<CreditCardTransactionDetail> creditCardTransactionInfo = null;

  public Payment applicationDate(DateTimeValue applicationDate) {
    this.applicationDate = applicationDate;
    return this;
  }

   /**
   * Get applicationDate
   * @return applicationDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getApplicationDate() {
    return applicationDate;
  }

  public void setApplicationDate(DateTimeValue applicationDate) {
    this.applicationDate = applicationDate;
  }

  public Payment applicationHistory(List<PaymentApplicationHistoryDetail> applicationHistory) {
    this.applicationHistory = applicationHistory;
    return this;
  }

  public Payment addApplicationHistoryItem(PaymentApplicationHistoryDetail applicationHistoryItem) {
    if (this.applicationHistory == null) {
      this.applicationHistory = new ArrayList<>();
    }
    this.applicationHistory.add(applicationHistoryItem);
    return this;
  }

   /**
   * Get applicationHistory
   * @return applicationHistory
  **/
  @ApiModelProperty(value = "")
  public List<PaymentApplicationHistoryDetail> getApplicationHistory() {
    return applicationHistory;
  }

  public void setApplicationHistory(List<PaymentApplicationHistoryDetail> applicationHistory) {
    this.applicationHistory = applicationHistory;
  }

  public Payment appliedToDocuments(DecimalValue appliedToDocuments) {
    this.appliedToDocuments = appliedToDocuments;
    return this;
  }

   /**
   * Get appliedToDocuments
   * @return appliedToDocuments
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getAppliedToDocuments() {
    return appliedToDocuments;
  }

  public void setAppliedToDocuments(DecimalValue appliedToDocuments) {
    this.appliedToDocuments = appliedToDocuments;
  }

  public Payment branch(StringValue branch) {
    this.branch = branch;
    return this;
  }

   /**
   * Get branch
   * @return branch
  **/
  @ApiModelProperty(value = "")
  public StringValue getBranch() {
    return branch;
  }

  public void setBranch(StringValue branch) {
    this.branch = branch;
  }

  public Payment cardAccountNbr(IntValue cardAccountNbr) {
    this.cardAccountNbr = cardAccountNbr;
    return this;
  }

   /**
   * Get cardAccountNbr
   * @return cardAccountNbr
  **/
  @ApiModelProperty(value = "")
  public IntValue getCardAccountNbr() {
    return cardAccountNbr;
  }

  public void setCardAccountNbr(IntValue cardAccountNbr) {
    this.cardAccountNbr = cardAccountNbr;
  }

  public Payment cashAccount(StringValue cashAccount) {
    this.cashAccount = cashAccount;
    return this;
  }

   /**
   * Get cashAccount
   * @return cashAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getCashAccount() {
    return cashAccount;
  }

  public void setCashAccount(StringValue cashAccount) {
    this.cashAccount = cashAccount;
  }

  public Payment creditCardProcessingInfo(List<CreditCardProcessingDetail> creditCardProcessingInfo) {
    this.creditCardProcessingInfo = creditCardProcessingInfo;
    return this;
  }

  public Payment addCreditCardProcessingInfoItem(CreditCardProcessingDetail creditCardProcessingInfoItem) {
    if (this.creditCardProcessingInfo == null) {
      this.creditCardProcessingInfo = new ArrayList<>();
    }
    this.creditCardProcessingInfo.add(creditCardProcessingInfoItem);
    return this;
  }

   /**
   * Get creditCardProcessingInfo
   * @return creditCardProcessingInfo
  **/
  @ApiModelProperty(value = "")
  public List<CreditCardProcessingDetail> getCreditCardProcessingInfo() {
    return creditCardProcessingInfo;
  }

  public void setCreditCardProcessingInfo(List<CreditCardProcessingDetail> creditCardProcessingInfo) {
    this.creditCardProcessingInfo = creditCardProcessingInfo;
  }

  public Payment currencyID(StringValue currencyID) {
    this.currencyID = currencyID;
    return this;
  }

   /**
   * Get currencyID
   * @return currencyID
  **/
  @ApiModelProperty(value = "")
  public StringValue getCurrencyID() {
    return currencyID;
  }

  public void setCurrencyID(StringValue currencyID) {
    this.currencyID = currencyID;
  }

  public Payment customerID(StringValue customerID) {
    this.customerID = customerID;
    return this;
  }

   /**
   * Get customerID
   * @return customerID
  **/
  @ApiModelProperty(value = "")
  public StringValue getCustomerID() {
    return customerID;
  }

  public void setCustomerID(StringValue customerID) {
    this.customerID = customerID;
  }

  public Payment description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public Payment documentsToApply(List<PaymentDetail> documentsToApply) {
    this.documentsToApply = documentsToApply;
    return this;
  }

  public Payment addDocumentsToApplyItem(PaymentDetail documentsToApplyItem) {
    if (this.documentsToApply == null) {
      this.documentsToApply = new ArrayList<>();
    }
    this.documentsToApply.add(documentsToApplyItem);
    return this;
  }

   /**
   * Get documentsToApply
   * @return documentsToApply
  **/
  @ApiModelProperty(value = "")
  public List<PaymentDetail> getDocumentsToApply() {
    return documentsToApply;
  }

  public void setDocumentsToApply(List<PaymentDetail> documentsToApply) {
    this.documentsToApply = documentsToApply;
  }

  public Payment hold(BooleanValue hold) {
    this.hold = hold;
    return this;
  }

   /**
   * Get hold
   * @return hold
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getHold() {
    return hold;
  }

  public void setHold(BooleanValue hold) {
    this.hold = hold;
  }

  public Payment ordersToApply(List<PaymentOrderDetail> ordersToApply) {
    this.ordersToApply = ordersToApply;
    return this;
  }

  public Payment addOrdersToApplyItem(PaymentOrderDetail ordersToApplyItem) {
    if (this.ordersToApply == null) {
      this.ordersToApply = new ArrayList<>();
    }
    this.ordersToApply.add(ordersToApplyItem);
    return this;
  }

   /**
   * Get ordersToApply
   * @return ordersToApply
  **/
  @ApiModelProperty(value = "")
  public List<PaymentOrderDetail> getOrdersToApply() {
    return ordersToApply;
  }

  public void setOrdersToApply(List<PaymentOrderDetail> ordersToApply) {
    this.ordersToApply = ordersToApply;
  }

  public Payment paymentAmount(DecimalValue paymentAmount) {
    this.paymentAmount = paymentAmount;
    return this;
  }

   /**
   * Get paymentAmount
   * @return paymentAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getPaymentAmount() {
    return paymentAmount;
  }

  public void setPaymentAmount(DecimalValue paymentAmount) {
    this.paymentAmount = paymentAmount;
  }

  public Payment paymentMethod(StringValue paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  @ApiModelProperty(value = "")
  public StringValue getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(StringValue paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public Payment paymentRef(StringValue paymentRef) {
    this.paymentRef = paymentRef;
    return this;
  }

   /**
   * Get paymentRef
   * @return paymentRef
  **/
  @ApiModelProperty(value = "")
  public StringValue getPaymentRef() {
    return paymentRef;
  }

  public void setPaymentRef(StringValue paymentRef) {
    this.paymentRef = paymentRef;
  }

  public Payment referenceNbr(StringValue referenceNbr) {
    this.referenceNbr = referenceNbr;
    return this;
  }

   /**
   * Get referenceNbr
   * @return referenceNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getReferenceNbr() {
    return referenceNbr;
  }

  public void setReferenceNbr(StringValue referenceNbr) {
    this.referenceNbr = referenceNbr;
  }

  public Payment status(StringValue status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StringValue getStatus() {
    return status;
  }

  public void setStatus(StringValue status) {
    this.status = status;
  }

  public Payment type(StringValue type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public StringValue getType() {
    return type;
  }

  public void setType(StringValue type) {
    this.type = type;
  }

  public Payment lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public Payment processingCenterID(StringValue processingCenterID) {
    this.processingCenterID = processingCenterID;
    return this;
  }

   /**
   * Get processingCenterID
   * @return processingCenterID
  **/
  @ApiModelProperty(value = "")
  public StringValue getProcessingCenterID() {
    return processingCenterID;
  }

  public void setProcessingCenterID(StringValue processingCenterID) {
    this.processingCenterID = processingCenterID;
  }

  public Payment saveCard(BooleanValue saveCard) {
    this.saveCard = saveCard;
    return this;
  }

   /**
   * Get saveCard
   * @return saveCard
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getSaveCard() {
    return saveCard;
  }

  public void setSaveCard(BooleanValue saveCard) {
    this.saveCard = saveCard;
  }

  public Payment creditCardTransactionInfo(List<CreditCardTransactionDetail> creditCardTransactionInfo) {
    this.creditCardTransactionInfo = creditCardTransactionInfo;
    return this;
  }

  public Payment addCreditCardTransactionInfoItem(CreditCardTransactionDetail creditCardTransactionInfoItem) {
    if (this.creditCardTransactionInfo == null) {
      this.creditCardTransactionInfo = new ArrayList<>();
    }
    this.creditCardTransactionInfo.add(creditCardTransactionInfoItem);
    return this;
  }

   /**
   * Get creditCardTransactionInfo
   * @return creditCardTransactionInfo
  **/
  @ApiModelProperty(value = "")
  public List<CreditCardTransactionDetail> getCreditCardTransactionInfo() {
    return creditCardTransactionInfo;
  }

  public void setCreditCardTransactionInfo(List<CreditCardTransactionDetail> creditCardTransactionInfo) {
    this.creditCardTransactionInfo = creditCardTransactionInfo;
  }

}

