/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * ProgressBilling
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class ProgressBilling extends Entity {
  @SerializedName("ActualAmount")
  private DecimalValue actualAmount = null;

  @SerializedName("Amount")
  private DecimalValue amount = null;

  @SerializedName("AmountToInvoice")
  private DecimalValue amountToInvoice = null;

  @SerializedName("Branch")
  private StringValue branch = null;

  @SerializedName("CostCode")
  private StringValue costCode = null;

  @SerializedName("CurrentInvoiced")
  private DecimalValue currentInvoiced = null;

  @SerializedName("DeferralCode")
  private StringValue deferralCode = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("DraftInvoicesAmount")
  private DecimalValue draftInvoicesAmount = null;

  @SerializedName("InventoryID")
  private StringValue inventoryID = null;

  @SerializedName("PreviouslyInvoiced")
  private DecimalValue previouslyInvoiced = null;

  @SerializedName("ProjectTaskID")
  private StringValue projectTaskID = null;

  @SerializedName("Retainage")
  private DecimalValue retainage = null;

  @SerializedName("RetainageAmount")
  private DecimalValue retainageAmount = null;

  @SerializedName("RevisedBudgetedAmount")
  private DecimalValue revisedBudgetedAmount = null;

  @SerializedName("SalesAccount")
  private StringValue salesAccount = null;

  @SerializedName("SalesSubaccount")
  private StringValue salesSubaccount = null;

  @SerializedName("StoredMaterial")
  private DecimalValue storedMaterial = null;

  @SerializedName("TaxCategory")
  private StringValue taxCategory = null;

  @SerializedName("TotalCompleted")
  private DecimalValue totalCompleted = null;

  public ProgressBilling actualAmount(DecimalValue actualAmount) {
    this.actualAmount = actualAmount;
    return this;
  }

   /**
   * Get actualAmount
   * @return actualAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getActualAmount() {
    return actualAmount;
  }

  public void setActualAmount(DecimalValue actualAmount) {
    this.actualAmount = actualAmount;
  }

  public ProgressBilling amount(DecimalValue amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getAmount() {
    return amount;
  }

  public void setAmount(DecimalValue amount) {
    this.amount = amount;
  }

  public ProgressBilling amountToInvoice(DecimalValue amountToInvoice) {
    this.amountToInvoice = amountToInvoice;
    return this;
  }

   /**
   * Get amountToInvoice
   * @return amountToInvoice
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getAmountToInvoice() {
    return amountToInvoice;
  }

  public void setAmountToInvoice(DecimalValue amountToInvoice) {
    this.amountToInvoice = amountToInvoice;
  }

  public ProgressBilling branch(StringValue branch) {
    this.branch = branch;
    return this;
  }

   /**
   * Get branch
   * @return branch
  **/
  @ApiModelProperty(value = "")
  public StringValue getBranch() {
    return branch;
  }

  public void setBranch(StringValue branch) {
    this.branch = branch;
  }

  public ProgressBilling costCode(StringValue costCode) {
    this.costCode = costCode;
    return this;
  }

   /**
   * Get costCode
   * @return costCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getCostCode() {
    return costCode;
  }

  public void setCostCode(StringValue costCode) {
    this.costCode = costCode;
  }

  public ProgressBilling currentInvoiced(DecimalValue currentInvoiced) {
    this.currentInvoiced = currentInvoiced;
    return this;
  }

   /**
   * Get currentInvoiced
   * @return currentInvoiced
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getCurrentInvoiced() {
    return currentInvoiced;
  }

  public void setCurrentInvoiced(DecimalValue currentInvoiced) {
    this.currentInvoiced = currentInvoiced;
  }

  public ProgressBilling deferralCode(StringValue deferralCode) {
    this.deferralCode = deferralCode;
    return this;
  }

   /**
   * Get deferralCode
   * @return deferralCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getDeferralCode() {
    return deferralCode;
  }

  public void setDeferralCode(StringValue deferralCode) {
    this.deferralCode = deferralCode;
  }

  public ProgressBilling description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public ProgressBilling draftInvoicesAmount(DecimalValue draftInvoicesAmount) {
    this.draftInvoicesAmount = draftInvoicesAmount;
    return this;
  }

   /**
   * Get draftInvoicesAmount
   * @return draftInvoicesAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getDraftInvoicesAmount() {
    return draftInvoicesAmount;
  }

  public void setDraftInvoicesAmount(DecimalValue draftInvoicesAmount) {
    this.draftInvoicesAmount = draftInvoicesAmount;
  }

  public ProgressBilling inventoryID(StringValue inventoryID) {
    this.inventoryID = inventoryID;
    return this;
  }

   /**
   * Get inventoryID
   * @return inventoryID
  **/
  @ApiModelProperty(value = "")
  public StringValue getInventoryID() {
    return inventoryID;
  }

  public void setInventoryID(StringValue inventoryID) {
    this.inventoryID = inventoryID;
  }

  public ProgressBilling previouslyInvoiced(DecimalValue previouslyInvoiced) {
    this.previouslyInvoiced = previouslyInvoiced;
    return this;
  }

   /**
   * Get previouslyInvoiced
   * @return previouslyInvoiced
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getPreviouslyInvoiced() {
    return previouslyInvoiced;
  }

  public void setPreviouslyInvoiced(DecimalValue previouslyInvoiced) {
    this.previouslyInvoiced = previouslyInvoiced;
  }

  public ProgressBilling projectTaskID(StringValue projectTaskID) {
    this.projectTaskID = projectTaskID;
    return this;
  }

   /**
   * Get projectTaskID
   * @return projectTaskID
  **/
  @ApiModelProperty(value = "")
  public StringValue getProjectTaskID() {
    return projectTaskID;
  }

  public void setProjectTaskID(StringValue projectTaskID) {
    this.projectTaskID = projectTaskID;
  }

  public ProgressBilling retainage(DecimalValue retainage) {
    this.retainage = retainage;
    return this;
  }

   /**
   * Get retainage
   * @return retainage
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getRetainage() {
    return retainage;
  }

  public void setRetainage(DecimalValue retainage) {
    this.retainage = retainage;
  }

  public ProgressBilling retainageAmount(DecimalValue retainageAmount) {
    this.retainageAmount = retainageAmount;
    return this;
  }

   /**
   * Get retainageAmount
   * @return retainageAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getRetainageAmount() {
    return retainageAmount;
  }

  public void setRetainageAmount(DecimalValue retainageAmount) {
    this.retainageAmount = retainageAmount;
  }

  public ProgressBilling revisedBudgetedAmount(DecimalValue revisedBudgetedAmount) {
    this.revisedBudgetedAmount = revisedBudgetedAmount;
    return this;
  }

   /**
   * Get revisedBudgetedAmount
   * @return revisedBudgetedAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getRevisedBudgetedAmount() {
    return revisedBudgetedAmount;
  }

  public void setRevisedBudgetedAmount(DecimalValue revisedBudgetedAmount) {
    this.revisedBudgetedAmount = revisedBudgetedAmount;
  }

  public ProgressBilling salesAccount(StringValue salesAccount) {
    this.salesAccount = salesAccount;
    return this;
  }

   /**
   * Get salesAccount
   * @return salesAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getSalesAccount() {
    return salesAccount;
  }

  public void setSalesAccount(StringValue salesAccount) {
    this.salesAccount = salesAccount;
  }

  public ProgressBilling salesSubaccount(StringValue salesSubaccount) {
    this.salesSubaccount = salesSubaccount;
    return this;
  }

   /**
   * Get salesSubaccount
   * @return salesSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getSalesSubaccount() {
    return salesSubaccount;
  }

  public void setSalesSubaccount(StringValue salesSubaccount) {
    this.salesSubaccount = salesSubaccount;
  }

  public ProgressBilling storedMaterial(DecimalValue storedMaterial) {
    this.storedMaterial = storedMaterial;
    return this;
  }

   /**
   * Get storedMaterial
   * @return storedMaterial
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getStoredMaterial() {
    return storedMaterial;
  }

  public void setStoredMaterial(DecimalValue storedMaterial) {
    this.storedMaterial = storedMaterial;
  }

  public ProgressBilling taxCategory(StringValue taxCategory) {
    this.taxCategory = taxCategory;
    return this;
  }

   /**
   * Get taxCategory
   * @return taxCategory
  **/
  @ApiModelProperty(value = "")
  public StringValue getTaxCategory() {
    return taxCategory;
  }

  public void setTaxCategory(StringValue taxCategory) {
    this.taxCategory = taxCategory;
  }

  public ProgressBilling totalCompleted(DecimalValue totalCompleted) {
    this.totalCompleted = totalCompleted;
    return this;
  }

   /**
   * Get totalCompleted
   * @return totalCompleted
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getTotalCompleted() {
    return totalCompleted;
  }

  public void setTotalCompleted(DecimalValue totalCompleted) {
    this.totalCompleted = totalCompleted;
  }

}

