/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * ProjectTaskDefaultValues
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class ProjectTaskDefaultValues extends Entity {
  @SerializedName("AccrualAccount")
  private StringValue accrualAccount = null;

  @SerializedName("AccrualSubaccount")
  private StringValue accrualSubaccount = null;

  @SerializedName("DefaultAccount")
  private StringValue defaultAccount = null;

  @SerializedName("DefaultSubaccount")
  private StringValue defaultSubaccount = null;

  @SerializedName("TaxCategory")
  private StringValue taxCategory = null;

  public ProjectTaskDefaultValues accrualAccount(StringValue accrualAccount) {
    this.accrualAccount = accrualAccount;
    return this;
  }

   /**
   * Get accrualAccount
   * @return accrualAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getAccrualAccount() {
    return accrualAccount;
  }

  public void setAccrualAccount(StringValue accrualAccount) {
    this.accrualAccount = accrualAccount;
  }

  public ProjectTaskDefaultValues accrualSubaccount(StringValue accrualSubaccount) {
    this.accrualSubaccount = accrualSubaccount;
    return this;
  }

   /**
   * Get accrualSubaccount
   * @return accrualSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getAccrualSubaccount() {
    return accrualSubaccount;
  }

  public void setAccrualSubaccount(StringValue accrualSubaccount) {
    this.accrualSubaccount = accrualSubaccount;
  }

  public ProjectTaskDefaultValues defaultAccount(StringValue defaultAccount) {
    this.defaultAccount = defaultAccount;
    return this;
  }

   /**
   * Get defaultAccount
   * @return defaultAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getDefaultAccount() {
    return defaultAccount;
  }

  public void setDefaultAccount(StringValue defaultAccount) {
    this.defaultAccount = defaultAccount;
  }

  public ProjectTaskDefaultValues defaultSubaccount(StringValue defaultSubaccount) {
    this.defaultSubaccount = defaultSubaccount;
    return this;
  }

   /**
   * Get defaultSubaccount
   * @return defaultSubaccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getDefaultSubaccount() {
    return defaultSubaccount;
  }

  public void setDefaultSubaccount(StringValue defaultSubaccount) {
    this.defaultSubaccount = defaultSubaccount;
  }

  public ProjectTaskDefaultValues taxCategory(StringValue taxCategory) {
    this.taxCategory = taxCategory;
    return this;
  }

   /**
   * Get taxCategory
   * @return taxCategory
  **/
  @ApiModelProperty(value = "")
  public StringValue getTaxCategory() {
    return taxCategory;
  }

  public void setTaxCategory(StringValue taxCategory) {
    this.taxCategory = taxCategory;
  }

}

