/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * ProjectTransaction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class ProjectTransaction extends Entity {
  @SerializedName("CreatedDateTime")
  private DateTimeValue createdDateTime = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("Details")
  private List<ProjectTransactionDetail> details = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("Module")
  private StringValue module = null;

  @SerializedName("OriginalDocNbr")
  private StringValue originalDocNbr = null;

  @SerializedName("OriginalDocType")
  private StringValue originalDocType = null;

  @SerializedName("ReferenceNbr")
  private StringValue referenceNbr = null;

  @SerializedName("Status")
  private StringValue status = null;

  @SerializedName("TotalAmount")
  private DecimalValue totalAmount = null;

  @SerializedName("TotalBillableQty")
  private DecimalValue totalBillableQty = null;

  @SerializedName("TotalQty")
  private DecimalValue totalQty = null;

  public ProjectTransaction createdDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public ProjectTransaction description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public ProjectTransaction details(List<ProjectTransactionDetail> details) {
    this.details = details;
    return this;
  }

  public ProjectTransaction addDetailsItem(ProjectTransactionDetail detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @ApiModelProperty(value = "")
  public List<ProjectTransactionDetail> getDetails() {
    return details;
  }

  public void setDetails(List<ProjectTransactionDetail> details) {
    this.details = details;
  }

  public ProjectTransaction lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public ProjectTransaction module(StringValue module) {
    this.module = module;
    return this;
  }

   /**
   * Get module
   * @return module
  **/
  @ApiModelProperty(value = "")
  public StringValue getModule() {
    return module;
  }

  public void setModule(StringValue module) {
    this.module = module;
  }

  public ProjectTransaction originalDocNbr(StringValue originalDocNbr) {
    this.originalDocNbr = originalDocNbr;
    return this;
  }

   /**
   * Get originalDocNbr
   * @return originalDocNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getOriginalDocNbr() {
    return originalDocNbr;
  }

  public void setOriginalDocNbr(StringValue originalDocNbr) {
    this.originalDocNbr = originalDocNbr;
  }

  public ProjectTransaction originalDocType(StringValue originalDocType) {
    this.originalDocType = originalDocType;
    return this;
  }

   /**
   * Get originalDocType
   * @return originalDocType
  **/
  @ApiModelProperty(value = "")
  public StringValue getOriginalDocType() {
    return originalDocType;
  }

  public void setOriginalDocType(StringValue originalDocType) {
    this.originalDocType = originalDocType;
  }

  public ProjectTransaction referenceNbr(StringValue referenceNbr) {
    this.referenceNbr = referenceNbr;
    return this;
  }

   /**
   * Get referenceNbr
   * @return referenceNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getReferenceNbr() {
    return referenceNbr;
  }

  public void setReferenceNbr(StringValue referenceNbr) {
    this.referenceNbr = referenceNbr;
  }

  public ProjectTransaction status(StringValue status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StringValue getStatus() {
    return status;
  }

  public void setStatus(StringValue status) {
    this.status = status;
  }

  public ProjectTransaction totalAmount(DecimalValue totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

   /**
   * Get totalAmount
   * @return totalAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getTotalAmount() {
    return totalAmount;
  }

  public void setTotalAmount(DecimalValue totalAmount) {
    this.totalAmount = totalAmount;
  }

  public ProjectTransaction totalBillableQty(DecimalValue totalBillableQty) {
    this.totalBillableQty = totalBillableQty;
    return this;
  }

   /**
   * Get totalBillableQty
   * @return totalBillableQty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getTotalBillableQty() {
    return totalBillableQty;
  }

  public void setTotalBillableQty(DecimalValue totalBillableQty) {
    this.totalBillableQty = totalBillableQty;
  }

  public ProjectTransaction totalQty(DecimalValue totalQty) {
    this.totalQty = totalQty;
    return this;
  }

   /**
   * Get totalQty
   * @return totalQty
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getTotalQty() {
    return totalQty;
  }

  public void setTotalQty(DecimalValue totalQty) {
    this.totalQty = totalQty;
  }

}

