/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * PurchaseSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class PurchaseSettings extends Entity {
  @SerializedName("POSiteID")
  private StringValue poSiteID = null;

  @SerializedName("POSource")
  private StringValue poSource = null;

  @SerializedName("VendorID")
  private StringValue vendorID = null;

  public PurchaseSettings poSiteID(StringValue poSiteID) {
    this.poSiteID = poSiteID;
    return this;
  }

   /**
   * Get poSiteID
   * @return poSiteID
  **/
  @ApiModelProperty(value = "")
  public StringValue getPoSiteID() {
    return poSiteID;
  }

  public void setPoSiteID(StringValue poSiteID) {
    this.poSiteID = poSiteID;
  }

  public PurchaseSettings poSource(StringValue poSource) {
    this.poSource = poSource;
    return this;
  }

   /**
   * Get poSource
   * @return poSource
  **/
  @ApiModelProperty(value = "")
  public StringValue getPoSource() {
    return poSource;
  }

  public void setPoSource(StringValue poSource) {
    this.poSource = poSource;
  }

  public PurchaseSettings vendorID(StringValue vendorID) {
    this.vendorID = vendorID;
    return this;
  }

   /**
   * Get vendorID
   * @return vendorID
  **/
  @ApiModelProperty(value = "")
  public StringValue getVendorID() {
    return vendorID;
  }

  public void setVendorID(StringValue vendorID) {
    this.vendorID = vendorID;
  }

}

