/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * SalesOrderCreditCardTransactionDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class SalesOrderCreditCardTransactionDetail extends Entity {
  @SerializedName("AuthNbr")
  private StringValue authNbr = null;

  @SerializedName("ExtProfileId")
  private StringValue extProfileId = null;

  @SerializedName("NeedValidation")
  private BooleanValue needValidation = null;

  @SerializedName("TranDate")
  private DateTimeValue tranDate = null;

  @SerializedName("TranNbr")
  private StringValue tranNbr = null;

  @SerializedName("TranType")
  private StringValue tranType = null;

  public SalesOrderCreditCardTransactionDetail authNbr(StringValue authNbr) {
    this.authNbr = authNbr;
    return this;
  }

   /**
   * Get authNbr
   * @return authNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getAuthNbr() {
    return authNbr;
  }

  public void setAuthNbr(StringValue authNbr) {
    this.authNbr = authNbr;
  }

  public SalesOrderCreditCardTransactionDetail extProfileId(StringValue extProfileId) {
    this.extProfileId = extProfileId;
    return this;
  }

   /**
   * Get extProfileId
   * @return extProfileId
  **/
  @ApiModelProperty(value = "")
  public StringValue getExtProfileId() {
    return extProfileId;
  }

  public void setExtProfileId(StringValue extProfileId) {
    this.extProfileId = extProfileId;
  }

  public SalesOrderCreditCardTransactionDetail needValidation(BooleanValue needValidation) {
    this.needValidation = needValidation;
    return this;
  }

   /**
   * Get needValidation
   * @return needValidation
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getNeedValidation() {
    return needValidation;
  }

  public void setNeedValidation(BooleanValue needValidation) {
    this.needValidation = needValidation;
  }

  public SalesOrderCreditCardTransactionDetail tranDate(DateTimeValue tranDate) {
    this.tranDate = tranDate;
    return this;
  }

   /**
   * Get tranDate
   * @return tranDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getTranDate() {
    return tranDate;
  }

  public void setTranDate(DateTimeValue tranDate) {
    this.tranDate = tranDate;
  }

  public SalesOrderCreditCardTransactionDetail tranNbr(StringValue tranNbr) {
    this.tranNbr = tranNbr;
    return this;
  }

   /**
   * Get tranNbr
   * @return tranNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getTranNbr() {
    return tranNbr;
  }

  public void setTranNbr(StringValue tranNbr) {
    this.tranNbr = tranNbr;
  }

  public SalesOrderCreditCardTransactionDetail tranType(StringValue tranType) {
    this.tranType = tranType;
    return this;
  }

   /**
   * Get tranType
   * @return tranType
  **/
  @ApiModelProperty(value = "")
  public StringValue getTranType() {
    return tranType;
  }

  public void setTranType(StringValue tranType) {
    this.tranType = tranType;
  }

}

