/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import java.util.ArrayList;
import java.util.List;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * SalesOrderPayment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class SalesOrderPayment extends Entity {
  @SerializedName("ApplicationDate")
  private DateTimeValue applicationDate = null;

  @SerializedName("AppliedToOrder")
  private DecimalValue appliedToOrder = null;

  @SerializedName("Authorize")
  private BooleanValue authorize = null;

  @SerializedName("Balance")
  private DecimalValue balance = null;

  @SerializedName("CardAccountNbr")
  private StringValue cardAccountNbr = null;

  @SerializedName("Capture")
  private BooleanValue capture = null;

  @SerializedName("CashAccount")
  private StringValue cashAccount = null;

  @SerializedName("Currency")
  private StringValue currency = null;

  @SerializedName("CreditCardTransactionInfo")
  private List<SalesOrderCreditCardTransactionDetail> creditCardTransactionInfo = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("DocType")
  private StringValue docType = null;

  @SerializedName("Hold")
  private BooleanValue hold = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("OrigTransactionNbr")
  private StringValue origTransactionNbr = null;

  @SerializedName("PaymentAmount")
  private DecimalValue paymentAmount = null;

  @SerializedName("PaymentMethod")
  private StringValue paymentMethod = null;

  @SerializedName("PaymentRef")
  private StringValue paymentRef = null;

  @SerializedName("ProcessingCenterID")
  private StringValue processingCenterID = null;

  @SerializedName("ReferenceNbr")
  private StringValue referenceNbr = null;

  @SerializedName("Refund")
  private BooleanValue refund = null;

  @SerializedName("SaveCard")
  private BooleanValue saveCard = null;

  @SerializedName("Status")
  private StringValue status = null;

  @SerializedName("TransferredtoInvoice")
  private DecimalValue transferredtoInvoice = null;

  @SerializedName("ValidateCCRefundOrigTransaction")
  private BooleanValue validateCCRefundOrigTransaction = null;

  public SalesOrderPayment applicationDate(DateTimeValue applicationDate) {
    this.applicationDate = applicationDate;
    return this;
  }

   /**
   * Get applicationDate
   * @return applicationDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getApplicationDate() {
    return applicationDate;
  }

  public void setApplicationDate(DateTimeValue applicationDate) {
    this.applicationDate = applicationDate;
  }

  public SalesOrderPayment appliedToOrder(DecimalValue appliedToOrder) {
    this.appliedToOrder = appliedToOrder;
    return this;
  }

   /**
   * Get appliedToOrder
   * @return appliedToOrder
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getAppliedToOrder() {
    return appliedToOrder;
  }

  public void setAppliedToOrder(DecimalValue appliedToOrder) {
    this.appliedToOrder = appliedToOrder;
  }

  public SalesOrderPayment authorize(BooleanValue authorize) {
    this.authorize = authorize;
    return this;
  }

   /**
   * Get authorize
   * @return authorize
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getAuthorize() {
    return authorize;
  }

  public void setAuthorize(BooleanValue authorize) {
    this.authorize = authorize;
  }

  public SalesOrderPayment balance(DecimalValue balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getBalance() {
    return balance;
  }

  public void setBalance(DecimalValue balance) {
    this.balance = balance;
  }

  public SalesOrderPayment cardAccountNbr(StringValue cardAccountNbr) {
    this.cardAccountNbr = cardAccountNbr;
    return this;
  }

   /**
   * Get cardAccountNbr
   * @return cardAccountNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getCardAccountNbr() {
    return cardAccountNbr;
  }

  public void setCardAccountNbr(StringValue cardAccountNbr) {
    this.cardAccountNbr = cardAccountNbr;
  }

  public SalesOrderPayment capture(BooleanValue capture) {
    this.capture = capture;
    return this;
  }

   /**
   * Get capture
   * @return capture
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getCapture() {
    return capture;
  }

  public void setCapture(BooleanValue capture) {
    this.capture = capture;
  }

  public SalesOrderPayment cashAccount(StringValue cashAccount) {
    this.cashAccount = cashAccount;
    return this;
  }

   /**
   * Get cashAccount
   * @return cashAccount
  **/
  @ApiModelProperty(value = "")
  public StringValue getCashAccount() {
    return cashAccount;
  }

  public void setCashAccount(StringValue cashAccount) {
    this.cashAccount = cashAccount;
  }

  public SalesOrderPayment currency(StringValue currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public StringValue getCurrency() {
    return currency;
  }

  public void setCurrency(StringValue currency) {
    this.currency = currency;
  }

  public SalesOrderPayment creditCardTransactionInfo(List<SalesOrderCreditCardTransactionDetail> creditCardTransactionInfo) {
    this.creditCardTransactionInfo = creditCardTransactionInfo;
    return this;
  }

  public SalesOrderPayment addCreditCardTransactionInfoItem(SalesOrderCreditCardTransactionDetail creditCardTransactionInfoItem) {
    if (this.creditCardTransactionInfo == null) {
      this.creditCardTransactionInfo = new ArrayList<>();
    }
    this.creditCardTransactionInfo.add(creditCardTransactionInfoItem);
    return this;
  }

   /**
   * Get creditCardTransactionInfo
   * @return creditCardTransactionInfo
  **/
  @ApiModelProperty(value = "")
  public List<SalesOrderCreditCardTransactionDetail> getCreditCardTransactionInfo() {
    return creditCardTransactionInfo;
  }

  public void setCreditCardTransactionInfo(List<SalesOrderCreditCardTransactionDetail> creditCardTransactionInfo) {
    this.creditCardTransactionInfo = creditCardTransactionInfo;
  }

  public SalesOrderPayment description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public SalesOrderPayment docType(StringValue docType) {
    this.docType = docType;
    return this;
  }

   /**
   * Get docType
   * @return docType
  **/
  @ApiModelProperty(value = "")
  public StringValue getDocType() {
    return docType;
  }

  public void setDocType(StringValue docType) {
    this.docType = docType;
  }

  public SalesOrderPayment hold(BooleanValue hold) {
    this.hold = hold;
    return this;
  }

   /**
   * Get hold
   * @return hold
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getHold() {
    return hold;
  }

  public void setHold(BooleanValue hold) {
    this.hold = hold;
  }

  public SalesOrderPayment lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public SalesOrderPayment origTransactionNbr(StringValue origTransactionNbr) {
    this.origTransactionNbr = origTransactionNbr;
    return this;
  }

   /**
   * Get origTransactionNbr
   * @return origTransactionNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getOrigTransactionNbr() {
    return origTransactionNbr;
  }

  public void setOrigTransactionNbr(StringValue origTransactionNbr) {
    this.origTransactionNbr = origTransactionNbr;
  }

  public SalesOrderPayment paymentAmount(DecimalValue paymentAmount) {
    this.paymentAmount = paymentAmount;
    return this;
  }

   /**
   * Get paymentAmount
   * @return paymentAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getPaymentAmount() {
    return paymentAmount;
  }

  public void setPaymentAmount(DecimalValue paymentAmount) {
    this.paymentAmount = paymentAmount;
  }

  public SalesOrderPayment paymentMethod(StringValue paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  @ApiModelProperty(value = "")
  public StringValue getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(StringValue paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public SalesOrderPayment paymentRef(StringValue paymentRef) {
    this.paymentRef = paymentRef;
    return this;
  }

   /**
   * Get paymentRef
   * @return paymentRef
  **/
  @ApiModelProperty(value = "")
  public StringValue getPaymentRef() {
    return paymentRef;
  }

  public void setPaymentRef(StringValue paymentRef) {
    this.paymentRef = paymentRef;
  }

  public SalesOrderPayment processingCenterID(StringValue processingCenterID) {
    this.processingCenterID = processingCenterID;
    return this;
  }

   /**
   * Get processingCenterID
   * @return processingCenterID
  **/
  @ApiModelProperty(value = "")
  public StringValue getProcessingCenterID() {
    return processingCenterID;
  }

  public void setProcessingCenterID(StringValue processingCenterID) {
    this.processingCenterID = processingCenterID;
  }

  public SalesOrderPayment referenceNbr(StringValue referenceNbr) {
    this.referenceNbr = referenceNbr;
    return this;
  }

   /**
   * Get referenceNbr
   * @return referenceNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getReferenceNbr() {
    return referenceNbr;
  }

  public void setReferenceNbr(StringValue referenceNbr) {
    this.referenceNbr = referenceNbr;
  }

  public SalesOrderPayment refund(BooleanValue refund) {
    this.refund = refund;
    return this;
  }

   /**
   * Get refund
   * @return refund
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getRefund() {
    return refund;
  }

  public void setRefund(BooleanValue refund) {
    this.refund = refund;
  }

  public SalesOrderPayment saveCard(BooleanValue saveCard) {
    this.saveCard = saveCard;
    return this;
  }

   /**
   * Get saveCard
   * @return saveCard
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getSaveCard() {
    return saveCard;
  }

  public void setSaveCard(BooleanValue saveCard) {
    this.saveCard = saveCard;
  }

  public SalesOrderPayment status(StringValue status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StringValue getStatus() {
    return status;
  }

  public void setStatus(StringValue status) {
    this.status = status;
  }

  public SalesOrderPayment transferredtoInvoice(DecimalValue transferredtoInvoice) {
    this.transferredtoInvoice = transferredtoInvoice;
    return this;
  }

   /**
   * Get transferredtoInvoice
   * @return transferredtoInvoice
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getTransferredtoInvoice() {
    return transferredtoInvoice;
  }

  public void setTransferredtoInvoice(DecimalValue transferredtoInvoice) {
    this.transferredtoInvoice = transferredtoInvoice;
  }

  public SalesOrderPayment validateCCRefundOrigTransaction(BooleanValue validateCCRefundOrigTransaction) {
    this.validateCCRefundOrigTransaction = validateCCRefundOrigTransaction;
    return this;
  }

   /**
   * Get validateCCRefundOrigTransaction
   * @return validateCCRefundOrigTransaction
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getValidateCCRefundOrigTransaction() {
    return validateCCRefundOrigTransaction;
  }

  public void setValidateCCRefundOrigTransaction(BooleanValue validateCCRefundOrigTransaction) {
    this.validateCCRefundOrigTransaction = validateCCRefundOrigTransaction;
  }

}

