/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * SalesInvoiceTaxDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class SalesInvoiceTaxDetail extends Entity {
  @SerializedName("TaxableAmount")
  private DecimalValue taxableAmount = null;

  @SerializedName("TaxAmount")
  private DecimalValue taxAmount = null;

  @SerializedName("TaxID")
  private StringValue taxID = null;

  public SalesInvoiceTaxDetail taxableAmount(DecimalValue taxableAmount) {
    this.taxableAmount = taxableAmount;
    return this;
  }

   /**
   * Get taxableAmount
   * @return taxableAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getTaxableAmount() {
    return taxableAmount;
  }

  public void setTaxableAmount(DecimalValue taxableAmount) {
    this.taxableAmount = taxableAmount;
  }

  public SalesInvoiceTaxDetail taxAmount(DecimalValue taxAmount) {
    this.taxAmount = taxAmount;
    return this;
  }

   /**
   * Get taxAmount
   * @return taxAmount
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getTaxAmount() {
    return taxAmount;
  }

  public void setTaxAmount(DecimalValue taxAmount) {
    this.taxAmount = taxAmount;
  }

  public SalesInvoiceTaxDetail taxID(StringValue taxID) {
    this.taxID = taxID;
    return this;
  }

   /**
   * Get taxID
   * @return taxID
  **/
  @ApiModelProperty(value = "")
  public StringValue getTaxID() {
    return taxID;
  }

  public void setTaxID(StringValue taxID) {
    this.taxID = taxID;
  }

}

