/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * SalesInvoiceFinancialDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class SalesInvoiceFinancialDetails extends Entity {
  @SerializedName("BatchNbr")
  private StringValue batchNbr = null;

  @SerializedName("Branch")
  private StringValue branch = null;

  @SerializedName("CustomerTaxZone")
  private StringValue customerTaxZone = null;

  public SalesInvoiceFinancialDetails batchNbr(StringValue batchNbr) {
    this.batchNbr = batchNbr;
    return this;
  }

   /**
   * Get batchNbr
   * @return batchNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getBatchNbr() {
    return batchNbr;
  }

  public void setBatchNbr(StringValue batchNbr) {
    this.batchNbr = batchNbr;
  }

  public SalesInvoiceFinancialDetails branch(StringValue branch) {
    this.branch = branch;
    return this;
  }

   /**
   * Get branch
   * @return branch
  **/
  @ApiModelProperty(value = "")
  public StringValue getBranch() {
    return branch;
  }

  public void setBranch(StringValue branch) {
    this.branch = branch;
  }

  public SalesInvoiceFinancialDetails customerTaxZone(StringValue customerTaxZone) {
    this.customerTaxZone = customerTaxZone;
    return this;
  }

   /**
   * Get customerTaxZone
   * @return customerTaxZone
  **/
  @ApiModelProperty(value = "")
  public StringValue getCustomerTaxZone() {
    return customerTaxZone;
  }

  public void setCustomerTaxZone(StringValue customerTaxZone) {
    this.customerTaxZone = customerTaxZone;
  }

}

