/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * StatementCycle
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class StatementCycle extends Entity {
  @SerializedName("AgingPeriod1EndDay")
  private ShortValue agingPeriod1EndDay = null;

  @SerializedName("AgingPeriod1Message")
  private StringValue agingPeriod1Message = null;

  @SerializedName("AgingPeriod2EndDay")
  private ShortValue agingPeriod2EndDay = null;

  @SerializedName("AgingPeriod2Message")
  private StringValue agingPeriod2Message = null;

  @SerializedName("AgingPeriod3EndDay")
  private ShortValue agingPeriod3EndDay = null;

  @SerializedName("AgingPeriod3Message")
  private StringValue agingPeriod3Message = null;

  @SerializedName("AgingPeriod4Message")
  private StringValue agingPeriod4Message = null;

  @SerializedName("ApplyOverdueCharges")
  private BooleanValue applyOverdueCharges = null;

  @SerializedName("CreatedDateTime")
  private DateTimeValue createdDateTime = null;

  @SerializedName("CycleID")
  private StringValue cycleID = null;

  @SerializedName("DayOfMonth")
  private ShortValue dayOfMonth = null;

  @SerializedName("DayOfMonth1")
  private ShortValue dayOfMonth1 = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("LastStatementDate")
  private DateTimeValue lastStatementDate = null;

  @SerializedName("OverdueChargeID")
  private StringValue overdueChargeID = null;

  @SerializedName("PrepareOn")
  private StringValue prepareOn = null;

  @SerializedName("RequireOverdueChargesCalculationBeforeStatement")
  private BooleanValue requireOverdueChargesCalculationBeforeStatement = null;

  @SerializedName("RequirePaymentApplicationBeforeStatementProcessing")
  private BooleanValue requirePaymentApplicationBeforeStatementProcessing = null;

  public StatementCycle agingPeriod1EndDay(ShortValue agingPeriod1EndDay) {
    this.agingPeriod1EndDay = agingPeriod1EndDay;
    return this;
  }

   /**
   * Get agingPeriod1EndDay
   * @return agingPeriod1EndDay
  **/
  @ApiModelProperty(value = "")
  public ShortValue getAgingPeriod1EndDay() {
    return agingPeriod1EndDay;
  }

  public void setAgingPeriod1EndDay(ShortValue agingPeriod1EndDay) {
    this.agingPeriod1EndDay = agingPeriod1EndDay;
  }

  public StatementCycle agingPeriod1Message(StringValue agingPeriod1Message) {
    this.agingPeriod1Message = agingPeriod1Message;
    return this;
  }

   /**
   * Get agingPeriod1Message
   * @return agingPeriod1Message
  **/
  @ApiModelProperty(value = "")
  public StringValue getAgingPeriod1Message() {
    return agingPeriod1Message;
  }

  public void setAgingPeriod1Message(StringValue agingPeriod1Message) {
    this.agingPeriod1Message = agingPeriod1Message;
  }

  public StatementCycle agingPeriod2EndDay(ShortValue agingPeriod2EndDay) {
    this.agingPeriod2EndDay = agingPeriod2EndDay;
    return this;
  }

   /**
   * Get agingPeriod2EndDay
   * @return agingPeriod2EndDay
  **/
  @ApiModelProperty(value = "")
  public ShortValue getAgingPeriod2EndDay() {
    return agingPeriod2EndDay;
  }

  public void setAgingPeriod2EndDay(ShortValue agingPeriod2EndDay) {
    this.agingPeriod2EndDay = agingPeriod2EndDay;
  }

  public StatementCycle agingPeriod2Message(StringValue agingPeriod2Message) {
    this.agingPeriod2Message = agingPeriod2Message;
    return this;
  }

   /**
   * Get agingPeriod2Message
   * @return agingPeriod2Message
  **/
  @ApiModelProperty(value = "")
  public StringValue getAgingPeriod2Message() {
    return agingPeriod2Message;
  }

  public void setAgingPeriod2Message(StringValue agingPeriod2Message) {
    this.agingPeriod2Message = agingPeriod2Message;
  }

  public StatementCycle agingPeriod3EndDay(ShortValue agingPeriod3EndDay) {
    this.agingPeriod3EndDay = agingPeriod3EndDay;
    return this;
  }

   /**
   * Get agingPeriod3EndDay
   * @return agingPeriod3EndDay
  **/
  @ApiModelProperty(value = "")
  public ShortValue getAgingPeriod3EndDay() {
    return agingPeriod3EndDay;
  }

  public void setAgingPeriod3EndDay(ShortValue agingPeriod3EndDay) {
    this.agingPeriod3EndDay = agingPeriod3EndDay;
  }

  public StatementCycle agingPeriod3Message(StringValue agingPeriod3Message) {
    this.agingPeriod3Message = agingPeriod3Message;
    return this;
  }

   /**
   * Get agingPeriod3Message
   * @return agingPeriod3Message
  **/
  @ApiModelProperty(value = "")
  public StringValue getAgingPeriod3Message() {
    return agingPeriod3Message;
  }

  public void setAgingPeriod3Message(StringValue agingPeriod3Message) {
    this.agingPeriod3Message = agingPeriod3Message;
  }

  public StatementCycle agingPeriod4Message(StringValue agingPeriod4Message) {
    this.agingPeriod4Message = agingPeriod4Message;
    return this;
  }

   /**
   * Get agingPeriod4Message
   * @return agingPeriod4Message
  **/
  @ApiModelProperty(value = "")
  public StringValue getAgingPeriod4Message() {
    return agingPeriod4Message;
  }

  public void setAgingPeriod4Message(StringValue agingPeriod4Message) {
    this.agingPeriod4Message = agingPeriod4Message;
  }

  public StatementCycle applyOverdueCharges(BooleanValue applyOverdueCharges) {
    this.applyOverdueCharges = applyOverdueCharges;
    return this;
  }

   /**
   * Get applyOverdueCharges
   * @return applyOverdueCharges
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getApplyOverdueCharges() {
    return applyOverdueCharges;
  }

  public void setApplyOverdueCharges(BooleanValue applyOverdueCharges) {
    this.applyOverdueCharges = applyOverdueCharges;
  }

  public StatementCycle createdDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(DateTimeValue createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public StatementCycle cycleID(StringValue cycleID) {
    this.cycleID = cycleID;
    return this;
  }

   /**
   * Get cycleID
   * @return cycleID
  **/
  @ApiModelProperty(value = "")
  public StringValue getCycleID() {
    return cycleID;
  }

  public void setCycleID(StringValue cycleID) {
    this.cycleID = cycleID;
  }

  public StatementCycle dayOfMonth(ShortValue dayOfMonth) {
    this.dayOfMonth = dayOfMonth;
    return this;
  }

   /**
   * Get dayOfMonth
   * @return dayOfMonth
  **/
  @ApiModelProperty(value = "")
  public ShortValue getDayOfMonth() {
    return dayOfMonth;
  }

  public void setDayOfMonth(ShortValue dayOfMonth) {
    this.dayOfMonth = dayOfMonth;
  }

  public StatementCycle dayOfMonth1(ShortValue dayOfMonth1) {
    this.dayOfMonth1 = dayOfMonth1;
    return this;
  }

   /**
   * Get dayOfMonth1
   * @return dayOfMonth1
  **/
  @ApiModelProperty(value = "")
  public ShortValue getDayOfMonth1() {
    return dayOfMonth1;
  }

  public void setDayOfMonth1(ShortValue dayOfMonth1) {
    this.dayOfMonth1 = dayOfMonth1;
  }

  public StatementCycle description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public StatementCycle lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public StatementCycle lastStatementDate(DateTimeValue lastStatementDate) {
    this.lastStatementDate = lastStatementDate;
    return this;
  }

   /**
   * Get lastStatementDate
   * @return lastStatementDate
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastStatementDate() {
    return lastStatementDate;
  }

  public void setLastStatementDate(DateTimeValue lastStatementDate) {
    this.lastStatementDate = lastStatementDate;
  }

  public StatementCycle overdueChargeID(StringValue overdueChargeID) {
    this.overdueChargeID = overdueChargeID;
    return this;
  }

   /**
   * Get overdueChargeID
   * @return overdueChargeID
  **/
  @ApiModelProperty(value = "")
  public StringValue getOverdueChargeID() {
    return overdueChargeID;
  }

  public void setOverdueChargeID(StringValue overdueChargeID) {
    this.overdueChargeID = overdueChargeID;
  }

  public StatementCycle prepareOn(StringValue prepareOn) {
    this.prepareOn = prepareOn;
    return this;
  }

   /**
   * Get prepareOn
   * @return prepareOn
  **/
  @ApiModelProperty(value = "")
  public StringValue getPrepareOn() {
    return prepareOn;
  }

  public void setPrepareOn(StringValue prepareOn) {
    this.prepareOn = prepareOn;
  }

  public StatementCycle requireOverdueChargesCalculationBeforeStatement(BooleanValue requireOverdueChargesCalculationBeforeStatement) {
    this.requireOverdueChargesCalculationBeforeStatement = requireOverdueChargesCalculationBeforeStatement;
    return this;
  }

   /**
   * Get requireOverdueChargesCalculationBeforeStatement
   * @return requireOverdueChargesCalculationBeforeStatement
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getRequireOverdueChargesCalculationBeforeStatement() {
    return requireOverdueChargesCalculationBeforeStatement;
  }

  public void setRequireOverdueChargesCalculationBeforeStatement(BooleanValue requireOverdueChargesCalculationBeforeStatement) {
    this.requireOverdueChargesCalculationBeforeStatement = requireOverdueChargesCalculationBeforeStatement;
  }

  public StatementCycle requirePaymentApplicationBeforeStatementProcessing(BooleanValue requirePaymentApplicationBeforeStatementProcessing) {
    this.requirePaymentApplicationBeforeStatementProcessing = requirePaymentApplicationBeforeStatementProcessing;
    return this;
  }

   /**
   * Get requirePaymentApplicationBeforeStatementProcessing
   * @return requirePaymentApplicationBeforeStatementProcessing
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getRequirePaymentApplicationBeforeStatementProcessing() {
    return requirePaymentApplicationBeforeStatementProcessing;
  }

  public void setRequirePaymentApplicationBeforeStatementProcessing(BooleanValue requirePaymentApplicationBeforeStatementProcessing) {
    this.requirePaymentApplicationBeforeStatementProcessing = requirePaymentApplicationBeforeStatementProcessing;
  }

}

