/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * TimeEntry
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class TimeEntry extends Entity {
  @SerializedName("ApprovalStatus")
  private StringValue approvalStatus = null;

  @SerializedName("Approver")
  private StringValue approver = null;

  @SerializedName("Billable")
  private BooleanValue billable = null;

  @SerializedName("BillableOvertime")
  private StringValue billableOvertime = null;

  @SerializedName("BillableTime")
  private StringValue billableTime = null;

  @SerializedName("CertifiedJob")
  private BooleanValue certifiedJob = null;

  @SerializedName("CostCode")
  private StringValue costCode = null;

  @SerializedName("CostRate")
  private DecimalValue costRate = null;

  @SerializedName("Date")
  private DateTimeValue date = null;

  @SerializedName("EarningType")
  private StringValue earningType = null;

  @SerializedName("Employee")
  private StringValue employee = null;

  @SerializedName("ExternalRefNbr")
  private StringValue externalRefNbr = null;

  @SerializedName("LaborItem")
  private StringValue laborItem = null;

  @SerializedName("LastModifiedDateTime")
  private DateTimeValue lastModifiedDateTime = null;

  @SerializedName("Overtime")
  private StringValue overtime = null;

  @SerializedName("ProjectID")
  private StringValue projectID = null;

  @SerializedName("ProjectTaskID")
  private StringValue projectTaskID = null;

  @SerializedName("Summary")
  private StringValue summary = null;

  @SerializedName("Time")
  private DateTimeValue time = null;

  @SerializedName("TimeEntryID")
  private GuidValue timeEntryID = null;

  @SerializedName("TimeSpent")
  private StringValue timeSpent = null;

  @SerializedName("UnionLocal")
  private StringValue unionLocal = null;

  @SerializedName("WCCCode")
  private StringValue wcCCode = null;

  public TimeEntry approvalStatus(StringValue approvalStatus) {
    this.approvalStatus = approvalStatus;
    return this;
  }

   /**
   * Get approvalStatus
   * @return approvalStatus
  **/
  @ApiModelProperty(value = "")
  public StringValue getApprovalStatus() {
    return approvalStatus;
  }

  public void setApprovalStatus(StringValue approvalStatus) {
    this.approvalStatus = approvalStatus;
  }

  public TimeEntry approver(StringValue approver) {
    this.approver = approver;
    return this;
  }

   /**
   * Get approver
   * @return approver
  **/
  @ApiModelProperty(value = "")
  public StringValue getApprover() {
    return approver;
  }

  public void setApprover(StringValue approver) {
    this.approver = approver;
  }

  public TimeEntry billable(BooleanValue billable) {
    this.billable = billable;
    return this;
  }

   /**
   * Get billable
   * @return billable
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getBillable() {
    return billable;
  }

  public void setBillable(BooleanValue billable) {
    this.billable = billable;
  }

  public TimeEntry billableOvertime(StringValue billableOvertime) {
    this.billableOvertime = billableOvertime;
    return this;
  }

   /**
   * Get billableOvertime
   * @return billableOvertime
  **/
  @ApiModelProperty(value = "")
  public StringValue getBillableOvertime() {
    return billableOvertime;
  }

  public void setBillableOvertime(StringValue billableOvertime) {
    this.billableOvertime = billableOvertime;
  }

  public TimeEntry billableTime(StringValue billableTime) {
    this.billableTime = billableTime;
    return this;
  }

   /**
   * Get billableTime
   * @return billableTime
  **/
  @ApiModelProperty(value = "")
  public StringValue getBillableTime() {
    return billableTime;
  }

  public void setBillableTime(StringValue billableTime) {
    this.billableTime = billableTime;
  }

  public TimeEntry certifiedJob(BooleanValue certifiedJob) {
    this.certifiedJob = certifiedJob;
    return this;
  }

   /**
   * Get certifiedJob
   * @return certifiedJob
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getCertifiedJob() {
    return certifiedJob;
  }

  public void setCertifiedJob(BooleanValue certifiedJob) {
    this.certifiedJob = certifiedJob;
  }

  public TimeEntry costCode(StringValue costCode) {
    this.costCode = costCode;
    return this;
  }

   /**
   * Get costCode
   * @return costCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getCostCode() {
    return costCode;
  }

  public void setCostCode(StringValue costCode) {
    this.costCode = costCode;
  }

  public TimeEntry costRate(DecimalValue costRate) {
    this.costRate = costRate;
    return this;
  }

   /**
   * Get costRate
   * @return costRate
  **/
  @ApiModelProperty(value = "")
  public DecimalValue getCostRate() {
    return costRate;
  }

  public void setCostRate(DecimalValue costRate) {
    this.costRate = costRate;
  }

  public TimeEntry date(DateTimeValue date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getDate() {
    return date;
  }

  public void setDate(DateTimeValue date) {
    this.date = date;
  }

  public TimeEntry earningType(StringValue earningType) {
    this.earningType = earningType;
    return this;
  }

   /**
   * Get earningType
   * @return earningType
  **/
  @ApiModelProperty(value = "")
  public StringValue getEarningType() {
    return earningType;
  }

  public void setEarningType(StringValue earningType) {
    this.earningType = earningType;
  }

  public TimeEntry employee(StringValue employee) {
    this.employee = employee;
    return this;
  }

   /**
   * Get employee
   * @return employee
  **/
  @ApiModelProperty(value = "")
  public StringValue getEmployee() {
    return employee;
  }

  public void setEmployee(StringValue employee) {
    this.employee = employee;
  }

  public TimeEntry externalRefNbr(StringValue externalRefNbr) {
    this.externalRefNbr = externalRefNbr;
    return this;
  }

   /**
   * Get externalRefNbr
   * @return externalRefNbr
  **/
  @ApiModelProperty(value = "")
  public StringValue getExternalRefNbr() {
    return externalRefNbr;
  }

  public void setExternalRefNbr(StringValue externalRefNbr) {
    this.externalRefNbr = externalRefNbr;
  }

  public TimeEntry laborItem(StringValue laborItem) {
    this.laborItem = laborItem;
    return this;
  }

   /**
   * Get laborItem
   * @return laborItem
  **/
  @ApiModelProperty(value = "")
  public StringValue getLaborItem() {
    return laborItem;
  }

  public void setLaborItem(StringValue laborItem) {
    this.laborItem = laborItem;
  }

  public TimeEntry lastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
    return this;
  }

   /**
   * Get lastModifiedDateTime
   * @return lastModifiedDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getLastModifiedDateTime() {
    return lastModifiedDateTime;
  }

  public void setLastModifiedDateTime(DateTimeValue lastModifiedDateTime) {
    this.lastModifiedDateTime = lastModifiedDateTime;
  }

  public TimeEntry overtime(StringValue overtime) {
    this.overtime = overtime;
    return this;
  }

   /**
   * Get overtime
   * @return overtime
  **/
  @ApiModelProperty(value = "")
  public StringValue getOvertime() {
    return overtime;
  }

  public void setOvertime(StringValue overtime) {
    this.overtime = overtime;
  }

  public TimeEntry projectID(StringValue projectID) {
    this.projectID = projectID;
    return this;
  }

   /**
   * Get projectID
   * @return projectID
  **/
  @ApiModelProperty(value = "")
  public StringValue getProjectID() {
    return projectID;
  }

  public void setProjectID(StringValue projectID) {
    this.projectID = projectID;
  }

  public TimeEntry projectTaskID(StringValue projectTaskID) {
    this.projectTaskID = projectTaskID;
    return this;
  }

   /**
   * Get projectTaskID
   * @return projectTaskID
  **/
  @ApiModelProperty(value = "")
  public StringValue getProjectTaskID() {
    return projectTaskID;
  }

  public void setProjectTaskID(StringValue projectTaskID) {
    this.projectTaskID = projectTaskID;
  }

  public TimeEntry summary(StringValue summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @ApiModelProperty(value = "")
  public StringValue getSummary() {
    return summary;
  }

  public void setSummary(StringValue summary) {
    this.summary = summary;
  }

  public TimeEntry time(DateTimeValue time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @ApiModelProperty(value = "")
  public DateTimeValue getTime() {
    return time;
  }

  public void setTime(DateTimeValue time) {
    this.time = time;
  }

  public TimeEntry timeEntryID(GuidValue timeEntryID) {
    this.timeEntryID = timeEntryID;
    return this;
  }

   /**
   * Get timeEntryID
   * @return timeEntryID
  **/
  @ApiModelProperty(value = "")
  public GuidValue getTimeEntryID() {
    return timeEntryID;
  }

  public void setTimeEntryID(GuidValue timeEntryID) {
    this.timeEntryID = timeEntryID;
  }

  public TimeEntry timeSpent(StringValue timeSpent) {
    this.timeSpent = timeSpent;
    return this;
  }

   /**
   * Get timeSpent
   * @return timeSpent
  **/
  @ApiModelProperty(value = "")
  public StringValue getTimeSpent() {
    return timeSpent;
  }

  public void setTimeSpent(StringValue timeSpent) {
    this.timeSpent = timeSpent;
  }

  public TimeEntry unionLocal(StringValue unionLocal) {
    this.unionLocal = unionLocal;
    return this;
  }

   /**
   * Get unionLocal
   * @return unionLocal
  **/
  @ApiModelProperty(value = "")
  public StringValue getUnionLocal() {
    return unionLocal;
  }

  public void setUnionLocal(StringValue unionLocal) {
    this.unionLocal = unionLocal;
  }

  public TimeEntry wcCCode(StringValue wcCCode) {
    this.wcCCode = wcCCode;
    return this;
  }

   /**
   * Get wcCCode
   * @return wcCCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getWcCCode() {
    return wcCCode;
  }

  public void setWcCCode(StringValue wcCCode) {
    this.wcCCode = wcCCode;
  }

}

