/*
 * Default/20.200.001
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package model;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * WorkClassCompensationCode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-06-01T18:06:51.194Z")
public class WorkClassCompensationCode extends Entity {
  @SerializedName("Active")
  private BooleanValue active = null;

  @SerializedName("CostCodeFrom")
  private StringValue costCodeFrom = null;

  @SerializedName("CostCodeTo")
  private StringValue costCodeTo = null;

  @SerializedName("Description")
  private StringValue description = null;

  @SerializedName("WCCCode")
  private StringValue wcCCode = null;

  public WorkClassCompensationCode active(BooleanValue active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public BooleanValue getActive() {
    return active;
  }

  public void setActive(BooleanValue active) {
    this.active = active;
  }

  public WorkClassCompensationCode costCodeFrom(StringValue costCodeFrom) {
    this.costCodeFrom = costCodeFrom;
    return this;
  }

   /**
   * Get costCodeFrom
   * @return costCodeFrom
  **/
  @ApiModelProperty(value = "")
  public StringValue getCostCodeFrom() {
    return costCodeFrom;
  }

  public void setCostCodeFrom(StringValue costCodeFrom) {
    this.costCodeFrom = costCodeFrom;
  }

  public WorkClassCompensationCode costCodeTo(StringValue costCodeTo) {
    this.costCodeTo = costCodeTo;
    return this;
  }

   /**
   * Get costCodeTo
   * @return costCodeTo
  **/
  @ApiModelProperty(value = "")
  public StringValue getCostCodeTo() {
    return costCodeTo;
  }

  public void setCostCodeTo(StringValue costCodeTo) {
    this.costCodeTo = costCodeTo;
  }

  public WorkClassCompensationCode description(StringValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public StringValue getDescription() {
    return description;
  }

  public void setDescription(StringValue description) {
    this.description = description;
  }

  public WorkClassCompensationCode wcCCode(StringValue wcCCode) {
    this.wcCCode = wcCCode;
    return this;
  }

   /**
   * Get wcCCode
   * @return wcCCode
  **/
  @ApiModelProperty(value = "")
  public StringValue getWcCCode() {
    return wcCCode;
  }

  public void setWcCCode(StringValue wcCCode) {
    this.wcCCode = wcCCode;
  }

}

